<template>
	<Story
			group="stylesAndDesignTokens"
			title="Utilities/Global classes"
			:layout="{ type: 'single', iframe: true }"
	>
		<!--
			Phase 1 deliverable — visual regression scaffold for the global
			utility classes generated by `scripts/build-tokens.mjs` into
			`src/assets/css/tokens/origam-utilities.css`.

			The story renders a swatch per class so a human (or a future
			Playwright spec) can verify that:
			  • Every class resolves to a non-empty CSS var.
			  • Theme switching (`<html data-theme="dark">`) correctly
			    re-paints color/bg/shadow utilities without rebuild.
			  • The cascade keeps the utility layer below component-scoped
			    rules — none of these blocks should override an OrigamBtn
			    placed on top.

			Note: this is a passive showcase. The classes are NOT exposed as
			component props yet — Phase 2 (composable refactor) will start
			emitting them from `useColor`, `useElevation`, etc.
		-->

		<!-- ════════════ FOREGROUND COLOR ════════════ -->
		<Variant title="Foreground color (.origam--color-*)">
			<template #default>
				<div :style="rowStyle">
					<div
							v-for="intent in intents"
							:key="`fg-${intent}`"
							:class="`origam--color-${intent}`"
							:style="swatchStyle"
							:data-cy="`util-color-${intent}`"
					>
						.origam--color-{{ intent }}
					</div>
				</div>
			</template>
		</Variant>

		<!-- ════════════ BACKGROUND COLOR ════════════ -->
		<Variant title="Background color (.origam--bg-*)">
			<template #default>
				<div :style="rowStyle">
					<div
							v-for="intent in intents"
							:key="`bg-${intent}`"
							:class="`origam--bg-${intent}`"
							:style="bgSwatchStyle"
							:data-cy="`util-bg-${intent}`"
					>
						.origam--bg-{{ intent }}
					</div>
				</div>
			</template>
		</Variant>

		<!-- ════════════ ELEVATION ════════════ -->
		<Variant title="Elevation (.origam--shadow-*)">
			<template #default>
				<div :style="rowStyle">
					<div
							v-for="level in shadows"
							:key="`shadow-${level}`"
							:class="`origam--shadow-${level}`"
							:style="cardStyle"
							:data-cy="`util-shadow-${level}`"
					>
						.origam--shadow-{{ level }}
					</div>
				</div>
			</template>
		</Variant>

		<!-- ════════════ ROUNDED ════════════ -->
		<Variant title="Border radius (.origam--rounded-*)">
			<template #default>
				<div :style="rowStyle">
					<div
							v-for="r in roundeds"
							:key="`rounded-${r}`"
							:class="`origam--rounded-${r}`"
							:style="roundedSwatchStyle"
							:data-cy="`util-rounded-${r}`"
					>
						{{ r }}
					</div>
				</div>
			</template>
		</Variant>

		<!-- ════════════ BORDER WIDTH ════════════ -->
		<Variant title="Border width (.origam--border-*)">
			<template #default>
				<div :style="rowStyle">
					<div
							v-for="b in borders"
							:key="`border-${b}`"
							:class="`origam--border-${b}`"
							:style="borderSwatchStyle"
							:data-cy="`util-border-${b}`"
					>
						.origam--border-{{ b }}
					</div>
				</div>
			</template>
		</Variant>

		<!-- ════════════ SPACING (padding) ════════════ -->
		<Variant title="Padding (.origam--p-*)">
			<template #default>
				<div :style="stackStyle">
					<div
							v-for="n in spaces"
							:key="`p-${n}`"
							:class="`origam--p-${n}`"
							:style="paddingFrameStyle"
							:data-cy="`util-p-${n}`"
					>
						<span :style="innerBlockStyle">.origam--p-{{ n }}</span>
					</div>
				</div>
			</template>
		</Variant>

		<!-- ════════════ SPACING (margin) ════════════ -->
		<Variant title="Margin (.origam--m-*)">
			<template #default>
				<div :style="marginFrameWrapStyle">
					<div
							v-for="n in spaces"
							:key="`m-${n}`"
							:class="`origam--m-${n}`"
							:style="marginFrameStyle"
							:data-cy="`util-m-${n}`"
					>
						.origam--m-{{ n }}
					</div>
				</div>
			</template>
		</Variant>

		<!-- ════════════ GAP ════════════ -->
		<Variant title="Gap (.origam--gap-*)">
			<template #default>
				<div :style="stackStyle">
					<div
							v-for="n in spaces"
							:key="`gap-${n}`"
							:class="`origam--gap-${n}`"
							style="display: flex;"
							:data-cy="`util-gap-${n}`"
					>
						<span :style="gapBoxStyle">A</span>
						<span :style="gapBoxStyle">B</span>
						<span :style="gapBoxStyle">C</span>
						<span :style="gapLabelStyle">.origam--gap-{{ n }}</span>
					</div>
				</div>
			</template>
		</Variant>

		<!-- ════════════ FONT SIZE ════════════ -->
		<Variant title="Font size (.origam--text-*)">
			<template #default>
				<div :style="stackStyle">
					<div
							v-for="size in textSizes"
							:key="`text-${size}`"
							:class="`origam--text-${size}`"
							:data-cy="`util-text-${size}`"
					>
						.origam--text-{{ size }} — The quick brown fox.
					</div>
				</div>
			</template>
		</Variant>
	</Story>
</template>

<script lang="ts" setup>
// SCREAMING_SNAKE constants for the matrix the story renders. These mirror
// the manifest declared in `scripts/build-tokens.mjs > UTILITY_GROUPS`.
// If a class is added/removed from the generator, update this list (and the
// matching Playwright spec under `tests/e2e/utilities.spec.ts` once Phase 4
// ships) so the visual scaffold stays accurate.

const intents = ['primary', 'secondary', 'success', 'warning', 'danger', 'info', 'neutral'] as const
const shadows = ['none', 'xs', 'sm', 'md', 'lg', 'xl'] as const
const roundeds = ['none', 'xs', 'sm', 'md', 'lg', 'xl', 'full'] as const
const borders = ['none', 'thin', 'thick'] as const
const spaces = ['0', '1', '2', '3', '4', '5', '6', '8', '10', '12'] as const
const textSizes = ['xs', 'sm', 'md', 'lg', 'xl', '2xl'] as const

// Layout primitives — kept inline (and intentionally NOT going through the
// utility classes themselves) to avoid hiding regressions: the swatch
// scaffolding must work even if a utility CSS rule is broken.
const rowStyle = 'display: flex; flex-wrap: wrap; gap: 12px; padding: 16px;'
const stackStyle = 'display: flex; flex-direction: column; gap: 12px; padding: 16px;'

const swatchStyle = 'min-width: 160px; padding: 12px 16px; background: #fafafa; border: 1px solid #ddd; border-radius: 4px; font-family: monospace; font-size: 13px;'
const bgSwatchStyle = 'min-width: 160px; padding: 16px; color: #fff; border-radius: 4px; font-family: monospace; font-size: 13px; text-shadow: 0 1px 2px rgba(0,0,0,0.4);'
const cardStyle = 'min-width: 140px; padding: 20px; background: #fff; border-radius: 8px; font-family: monospace; font-size: 13px; text-align: center;'
const roundedSwatchStyle = 'min-width: 100px; min-height: 100px; display: flex; align-items: center; justify-content: center; background: #c4b5fd; color: #4c1d95; font-family: monospace; font-size: 13px; font-weight: 600;'
const borderSwatchStyle = 'min-width: 140px; padding: 12px 16px; background: #fff; border-color: #7c3aed; font-family: monospace; font-size: 13px;'
const paddingFrameStyle = 'background: #ede9fe; border: 1px dashed #7c3aed; font-family: monospace; font-size: 13px; max-width: 480px;'
const innerBlockStyle = 'display: block; background: #fff; padding: 4px 6px; border-radius: 2px;'

const marginFrameWrapStyle = 'background: #f5f5f5; padding: 16px; max-width: 600px;'
const marginFrameStyle = 'background: #ede9fe; border: 1px dashed #7c3aed; padding: 8px; font-family: monospace; font-size: 13px;'

const gapBoxStyle = 'background: #c4b5fd; color: #4c1d95; padding: 4px 10px; border-radius: 2px; font-family: monospace; font-size: 13px;'
const gapLabelStyle = 'align-self: center; padding-left: 12px; font-family: monospace; font-size: 12px; color: #555;'
</script>
