import type { IComposableEntry } from '~/interfaces/composables-catalog.interface'

export const COMPOSABLES_DOMAINS = [
    'Commons',
    'Theme',
    'CssSupport',
] as const

export const COMPOSABLES_CATALOG: IComposableEntry[] = [
    /* ── Commons ─────────────────────────────────────────────────── */
    {
        slug: 'use-color',
        name: 'useColor',
        icon: 'mdi-palette',
        descriptionKey: '',
        descriptionFallback: 'Resolve background and text colors from intent tokens or raw CSS values, with classes-first utility output.',
        domain: 'Commons',
        related: ['use-background-color', 'use-text-color', 'use-color-effect'],
    },
    {
        slug: 'use-background-color',
        name: 'useBackgroundColor',
        icon: 'mdi-format-color-fill',
        descriptionKey: '',
        descriptionFallback: 'Surface-only color helper. Resolves the `bgColor` prop to a utility class or inline background-color declaration.',
        domain: 'Commons',
        related: ['use-color', 'use-text-color', 'use-color-effect'],
    },
    {
        slug: 'use-text-color',
        name: 'useTextColor',
        icon: 'mdi-format-color-text',
        descriptionKey: '',
        descriptionFallback: 'Foreground-only color helper. Resolves the `color` prop to a utility class or inline color declaration.',
        domain: 'Commons',
        related: ['use-color', 'use-background-color', 'use-color-effect'],
    },
    {
        slug: 'use-color-effect',
        name: 'useColorEffect',
        icon: 'mdi-palette-swatch',
        descriptionKey: '',
        descriptionFallback: 'State-aware (hover / active / disabled) color resolution for components that paint a surface. Auto-contrasts foreground when only `bgColor` is set.',
        domain: 'Commons',
        related: ['use-color', 'use-hover', 'use-active'],
    },
    {
        slug: 'use-dimension',
        name: 'useDimension',
        icon: 'mdi-resize',
        descriptionKey: '',
        descriptionFallback: 'Resolves the six dimension props (width, height, minWidth, maxWidth, minHeight, maxHeight) into inline CSS declarations via `convertToUnit`.',
        domain: 'Commons',
        related: ['use-size'],
    },
    {
        slug: 'use-margin',
        name: 'useMargin',
        icon: 'mdi-arrow-expand-all',
        descriptionKey: '',
        descriptionFallback: 'Resolves the `margin` shorthand prop into utility classes (scale steps) or inline margin declarations (custom values).',
        domain: 'Commons',
        related: ['use-padding'],
    },
    {
        slug: 'use-padding',
        name: 'usePadding',
        icon: 'mdi-arrow-collapse-all',
        descriptionKey: '',
        descriptionFallback: 'Resolves the `padding` shorthand prop into utility classes (scale steps) or inline padding declarations (custom values).',
        domain: 'Commons',
        related: ['use-margin'],
    },
    {
        slug: 'use-border',
        name: 'useBorder',
        icon: 'mdi-border-all',
        descriptionKey: '',
        descriptionFallback: 'Resolves the `border` prop (boolean, keyword, string or number) into utility classes and inline border declarations.',
        domain: 'Commons',
        related: ['use-rounded', 'use-elevation'],
    },
    {
        slug: 'use-rounded',
        name: 'useRounded',
        icon: 'mdi-rounded-corner',
        descriptionKey: '',
        descriptionFallback: 'Resolves the `rounded` prop (named variant, utility rung, number or CSS value) into border-radius classes and inline styles.',
        domain: 'Commons',
        related: ['use-border'],
    },
    {
        slug: 'use-elevation',
        name: 'useElevation',
        icon: 'mdi-layers',
        descriptionKey: '',
        descriptionFallback: 'Maps the `elevation` prop (origam rung or Material 0–24 integer) to a `--origam-shadow-*` design token and emits the matching utility class.',
        domain: 'Commons',
        related: ['use-border'],
    },
    {
        slug: 'use-size',
        name: 'useSize',
        icon: 'mdi-magnify-plus-outline',
        descriptionKey: '',
        descriptionFallback: 'Resolves the `size` prop (named preset or custom value) into component-local classes and optional width/height inline styles.',
        domain: 'Commons',
        related: ['use-dimension', 'use-density'],
    },
    {
        slug: 'use-density',
        name: 'useDensity',
        icon: 'mdi-view-compact',
        descriptionKey: '',
        descriptionFallback: 'Emits the density modifier class (`compact`, `default`, `comfortable`) to drive spacing via component-local SCSS rules.',
        domain: 'Commons',
        related: ['use-size'],
    },
    {
        slug: 'use-active',
        name: 'useActive',
        icon: 'mdi-cursor-default-click',
        descriptionKey: '',
        descriptionFallback: 'Tracks the active (pressed / selected) state of a component. Supports boolean, forced-on, and IActiveState config objects with style overrides.',
        domain: 'Commons',
        related: ['use-hover', 'use-color-effect'],
    },
    {
        slug: 'use-hover',
        name: 'useHover',
        icon: 'mdi-cursor-pointer',
        descriptionKey: '',
        descriptionFallback: 'Tracks whether the host element is hovered. Supports forced-on (`hover=true`) and IHoverState config objects for style overrides per-axis.',
        domain: 'Commons',
        related: ['use-active', 'use-color-effect'],
    },
    /* ── Theme ────────────────────────────────────────────────────── */
    {
        slug: 'use-theme',
        name: 'useTheme',
        icon: 'mdi-theme-light-dark',
        descriptionKey: '',
        descriptionFallback: 'Module-level singleton that manages the brand theme axis (`data-theme`) and color-mode axis (`data-mode`). Persists to localStorage.',
        domain: 'Theme',
        related: [],
    },
    /* ── CssSupport ──────────────────────────────────────────────── */
    {
        slug: 'use-css-support',
        name: 'useCssSupport',
        icon: 'mdi-code-braces',
        descriptionKey: '',
        descriptionFallback: 'The single CSS feature-detection layer. Provides a reactive flag map and free-form `supports()` / `supportsAny()` helpers — never call CSS.supports() directly.',
        domain: 'CssSupport',
        related: [],
    },
]
