/**
 * THEME_BUILDER_BRAND_PRESETS — seed values for the /theming builder, one entry
 * per brand theme (light + dark bundled). Each map is the SUBSET of the brand
 * theme cssVars that the builder actually exposes (the keys in
 * THEME_BUILDER_PRESET_LIGHT_VARS from theme-builder-presets.const.ts).
 *
 * GÉNÉRÉ depuis packages/marketing/app/assets/css/themes/*.css
 * par scripts/generate-brand-presets.mjs. Valeurs RÉELLES extraites des CSS
 * de marque — ne PAS éditer à la main. Régénérer via:
 *   node scripts/generate-brand-presets.mjs
 */
import type { IThemeBuilderPreset } from '~/interfaces/theme-builder.interface'

export const THEME_BUILDER_PRESET_CARTOON_LIGHT_VARS: Record<string, string> = {
        "--origam-btn---border-color": "#171717",
        "--origam-btn---border-width-ghost": "3px",
        "--origam-btn---border-width-outlined": "3px",
        "--origam-card---border-bottom-width": "3px",
        "--origam-card---border-color": "var(--origam-color__border---default)",
        "--origam-card---border-left-width": "3px",
        "--origam-card---border-right-width": "3px",
        "--origam-card---border-style": "solid",
        "--origam-card---border-top-width": "3px",
        "--origam-chip---border-color": "#171717",
        "--origam-chip---border-style": "solid",
        "--origam-chip---border-width": "3px",
        "--origam-color__feedback--danger---bg": "#ef4444",
        "--origam-color__feedback--danger---bgSubtle": "#fecdd3",
        "--origam-color__feedback--danger---border": "#171717",
        "--origam-color__feedback--danger---fg": "#000000",
        "--origam-color__feedback--danger---fgSubtle": "#b91c1c",
        "--origam-color__feedback--info---bg": "#60a5fa",
        "--origam-color__feedback--info---bgSubtle": "#dbeafe",
        "--origam-color__feedback--info---border": "#171717",
        "--origam-color__feedback--info---fg": "#171717",
        "--origam-color__feedback--info---fgSubtle": "#1d4ed8",
        "--origam-color__feedback--success---bg": "#16a34a",
        "--origam-color__feedback--success---bgSubtle": "#bbf7d0",
        "--origam-color__feedback--success---border": "#171717",
        "--origam-color__feedback--success---fg": "#000000",
        "--origam-color__feedback--success---fgSubtle": "#166534",
        "--origam-color__feedback--warning---bg": "#fbbf24",
        "--origam-color__feedback--warning---bgSubtle": "#fef3c7",
        "--origam-color__feedback--warning---border": "#171717",
        "--origam-color__feedback--warning---fg": "#171717",
        "--origam-color__feedback--warning---fgSubtle": "#b45309",
        "--origam-field---border-color": "#171717",
        "--origam-field---border-opacity": "1",
        "--origam-field---border-width": "3px",
        "--origam-title---font-family": "Inter, -apple-system, 'system-ui', sans-serif"
    }

export const THEME_BUILDER_PRESET_CARTOON_DARK_VARS: Record<string, string> = {
        "--origam-btn---border-color": "#fffefb",
        "--origam-btn---border-width-ghost": "3px",
        "--origam-btn---border-width-outlined": "3px",
        "--origam-card---border-bottom-width": "3px",
        "--origam-card---border-color": "#fffefb",
        "--origam-card---border-left-width": "3px",
        "--origam-card---border-right-width": "3px",
        "--origam-card---border-style": "solid",
        "--origam-card---border-top-width": "3px",
        "--origam-chip---border-color": "#fffefb",
        "--origam-chip---border-style": "solid",
        "--origam-chip---border-width": "3px",
        "--origam-color__feedback--danger---bg": "#f87171",
        "--origam-color__feedback--danger---bgSubtle": "#7f1d1d",
        "--origam-color__feedback--danger---border": "#fffefb",
        "--origam-color__feedback--danger---fg": "#171717",
        "--origam-color__feedback--danger---fgSubtle": "#fca5a5",
        "--origam-color__feedback--info---bg": "#60a5fa",
        "--origam-color__feedback--info---bgSubtle": "#1e3a8a",
        "--origam-color__feedback--info---border": "#fffefb",
        "--origam-color__feedback--info---fg": "#171717",
        "--origam-color__feedback--info---fgSubtle": "#93c5fd",
        "--origam-color__feedback--success---bg": "#4ade80",
        "--origam-color__feedback--success---bgSubtle": "#14532d",
        "--origam-color__feedback--success---border": "#fffefb",
        "--origam-color__feedback--success---fg": "#171717",
        "--origam-color__feedback--success---fgSubtle": "#86efac",
        "--origam-color__feedback--warning---bg": "#fbbf24",
        "--origam-color__feedback--warning---bgSubtle": "#78350f",
        "--origam-color__feedback--warning---border": "#fffefb",
        "--origam-color__feedback--warning---fg": "#171717",
        "--origam-color__feedback--warning---fgSubtle": "#fcd34d",
        "--origam-field---border-color": "#fffefb",
        "--origam-title---font-family": "Inter, -apple-system, 'system-ui', sans-serif"
    }

export const THEME_BUILDER_PRESET_APPLE_LIGHT_VARS: Record<string, string> = {
        "--origam-btn---border-color": "#d2d2d7",
        "--origam-btn---border-width-ghost": "1px",
        "--origam-btn---border-width-outlined": "1px",
        "--origam-color__feedback--danger---bg": "#ff3b30",
        "--origam-color__feedback--danger---bgSubtle": "#ffe9e7",
        "--origam-color__feedback--danger---border": "#ff3b30",
        "--origam-color__feedback--danger---fg": "#000000",
        "--origam-color__feedback--danger---fgSubtle": "#c2271c",
        "--origam-color__feedback--info---bg": "#0071e3",
        "--origam-color__feedback--info---bgSubtle": "#f0f7ff",
        "--origam-color__feedback--info---border": "#0071e3",
        "--origam-color__feedback--info---fg": "#ffffff",
        "--origam-color__feedback--info---fgSubtle": "#0058b0",
        "--origam-color__feedback--success---bg": "#28cd41",
        "--origam-color__feedback--success---bgSubtle": "#e8f8ec",
        "--origam-color__feedback--success---border": "#28cd41",
        "--origam-color__feedback--success---fg": "#000000",
        "--origam-color__feedback--success---fgSubtle": "#166534",
        "--origam-color__feedback--warning---bg": "#ff9f0a",
        "--origam-color__feedback--warning---bgSubtle": "#fff4e5",
        "--origam-color__feedback--warning---border": "#ff9f0a",
        "--origam-color__feedback--warning---fg": "#000000",
        "--origam-color__feedback--warning---fgSubtle": "#78350f",
        "--origam-title---font-family": "-apple-system, BlinkMacSystemFont, 'SF Pro Display', 'Inter', sans-serif"
    }

export const THEME_BUILDER_PRESET_APPLE_DARK_VARS: Record<string, string> = {
        "--origam-btn---border-color": "#38383a",
        "--origam-btn---border-width-ghost": "1px",
        "--origam-btn---border-width-outlined": "1px",
        "--origam-color__feedback--danger---bg": "#ff453a",
        "--origam-color__feedback--danger---bgSubtle": "rgba(255, 69, 58, 0.16)",
        "--origam-color__feedback--danger---border": "#ff453a",
        "--origam-color__feedback--danger---fg": "#ffffff",
        "--origam-color__feedback--danger---fgSubtle": "#ff6961",
        "--origam-color__feedback--info---bg": "#0a84ff",
        "--origam-color__feedback--info---bgSubtle": "rgba(10, 132, 255, 0.16)",
        "--origam-color__feedback--info---border": "#0a84ff",
        "--origam-color__feedback--info---fg": "#ffffff",
        "--origam-color__feedback--info---fgSubtle": "#64b5ff",
        "--origam-color__feedback--success---bg": "#30d158",
        "--origam-color__feedback--success---bgSubtle": "rgba(48, 209, 88, 0.16)",
        "--origam-color__feedback--success---border": "#30d158",
        "--origam-color__feedback--success---fg": "#000000",
        "--origam-color__feedback--success---fgSubtle": "#64e47c",
        "--origam-color__feedback--warning---bg": "#ff9f0a",
        "--origam-color__feedback--warning---bgSubtle": "rgba(255, 159, 10, 0.16)",
        "--origam-color__feedback--warning---border": "#ff9f0a",
        "--origam-color__feedback--warning---fg": "#000000",
        "--origam-color__feedback--warning---fgSubtle": "#ffb445",
        "--origam-title---font-family": "-apple-system, BlinkMacSystemFont, 'SF Pro Display', 'Inter', sans-serif"
    }

export const THEME_BUILDER_PRESET_GEEK_LIGHT_VARS: Record<string, string> = {
        "--origam-btn---border-color": "rgba(217, 70, 239, 0.55)",
        "--origam-btn---border-width-ghost": "1px",
        "--origam-btn---border-width-outlined": "1px",
        "--origam-color__feedback--danger---bg": "#dc2626",
        "--origam-color__feedback--danger---bgSubtle": "rgba(220, 38, 38, 0.1)",
        "--origam-color__feedback--danger---border": "#dc2626",
        "--origam-color__feedback--danger---fg": "#ffffff",
        "--origam-color__feedback--danger---fgSubtle": "#b91c1c",
        "--origam-color__feedback--info---bg": "#2563eb",
        "--origam-color__feedback--info---bgSubtle": "rgba(37, 99, 235, 0.1)",
        "--origam-color__feedback--info---border": "#2563eb",
        "--origam-color__feedback--info---fg": "#ffffff",
        "--origam-color__feedback--info---fgSubtle": "#1d4ed8",
        "--origam-color__feedback--success---bg": "#16a34a",
        "--origam-color__feedback--success---bgSubtle": "rgba(22, 163, 74, 0.1)",
        "--origam-color__feedback--success---border": "#16a34a",
        "--origam-color__feedback--success---fg": "#000000",
        "--origam-color__feedback--success---fgSubtle": "#15803d",
        "--origam-color__feedback--warning---bg": "#d97706",
        "--origam-color__feedback--warning---bgSubtle": "rgba(217, 119, 6, 0.1)",
        "--origam-color__feedback--warning---border": "#d97706",
        "--origam-color__feedback--warning---fg": "#000000",
        "--origam-color__feedback--warning---fgSubtle": "#b45309",
        "--origam-title---font-family": "'JetBrains Mono', 'Fira Code', ui-monospace, monospace"
    }

export const THEME_BUILDER_PRESET_GEEK_DARK_VARS: Record<string, string> = {
        "--origam-btn---border-color": "rgba(0, 240, 255, 0.40)",
        "--origam-btn---border-width-ghost": "1px",
        "--origam-btn---border-width-outlined": "1px",
        "--origam-color__feedback--danger---bg": "#fca5a5",
        "--origam-color__feedback--danger---bgSubtle": "rgba(252, 165, 165, 0.1)",
        "--origam-color__feedback--danger---border": "#fca5a5",
        "--origam-color__feedback--danger---fg": "#050a05",
        "--origam-color__feedback--danger---fgSubtle": "#fca5a5",
        "--origam-color__feedback--info---bg": "#93c5fd",
        "--origam-color__feedback--info---bgSubtle": "rgba(147, 197, 253, 0.1)",
        "--origam-color__feedback--info---border": "#93c5fd",
        "--origam-color__feedback--info---fg": "#050a05",
        "--origam-color__feedback--info---fgSubtle": "#93c5fd",
        "--origam-color__feedback--success---bg": "#4ade80",
        "--origam-color__feedback--success---bgSubtle": "rgba(74, 222, 128, 0.1)",
        "--origam-color__feedback--success---border": "#4ade80",
        "--origam-color__feedback--success---fg": "#050a05",
        "--origam-color__feedback--success---fgSubtle": "#6ee7b7",
        "--origam-color__feedback--warning---bg": "#fbbf24",
        "--origam-color__feedback--warning---bgSubtle": "rgba(251, 191, 36, 0.1)",
        "--origam-color__feedback--warning---border": "#fbbf24",
        "--origam-color__feedback--warning---fg": "#050a05",
        "--origam-color__feedback--warning---fgSubtle": "#fbbf24",
        "--origam-title---font-family": "'JetBrains Mono', 'Fira Code', ui-monospace, monospace"
    }

export const THEME_BUILDER_PRESET_GLASS_LIGHT_VARS: Record<string, string> = {
        "--origam-btn---border-color": "rgba(124, 58, 237, 0.35)",
        "--origam-btn---border-width-ghost": "1px",
        "--origam-btn---border-width-outlined": "1px",
        "--origam-color__feedback--danger---bg": "#dc2626",
        "--origam-color__feedback--danger---bgSubtle": "rgba(220, 38, 38, 0.1)",
        "--origam-color__feedback--danger---border": "#dc2626",
        "--origam-color__feedback--danger---fg": "#ffffff",
        "--origam-color__feedback--danger---fgSubtle": "#b91c1c",
        "--origam-color__feedback--info---bg": "#2563eb",
        "--origam-color__feedback--info---bgSubtle": "rgba(37, 99, 235, 0.1)",
        "--origam-color__feedback--info---border": "#2563eb",
        "--origam-color__feedback--info---fg": "#ffffff",
        "--origam-color__feedback--info---fgSubtle": "#1d4ed8",
        "--origam-color__feedback--success---bg": "#16a34a",
        "--origam-color__feedback--success---bgSubtle": "rgba(22, 163, 74, 0.1)",
        "--origam-color__feedback--success---border": "#16a34a",
        "--origam-color__feedback--success---fg": "#000000",
        "--origam-color__feedback--success---fgSubtle": "#15803d",
        "--origam-color__feedback--warning---bg": "#d97706",
        "--origam-color__feedback--warning---bgSubtle": "rgba(217, 119, 6, 0.1)",
        "--origam-color__feedback--warning---border": "#d97706",
        "--origam-color__feedback--warning---fg": "#000000",
        "--origam-color__feedback--warning---fgSubtle": "#b45309"
    }

export const THEME_BUILDER_PRESET_GLASS_DARK_VARS: Record<string, string> = {
        "--origam-btn---border-color": "rgba(255, 255, 255, 0.20)",
        "--origam-btn---border-width-ghost": "1px",
        "--origam-btn---border-width-outlined": "1px",
        "--origam-color__feedback--danger---bg": "#fca5a5",
        "--origam-color__feedback--danger---bgSubtle": "rgba(252, 165, 165, 0.14)",
        "--origam-color__feedback--danger---border": "#fca5a5",
        "--origam-color__feedback--danger---fg": "#0f0e1a",
        "--origam-color__feedback--danger---fgSubtle": "#fca5a5",
        "--origam-color__feedback--info---bg": "#93c5fd",
        "--origam-color__feedback--info---bgSubtle": "rgba(147, 197, 253, 0.14)",
        "--origam-color__feedback--info---border": "#93c5fd",
        "--origam-color__feedback--info---fg": "#0f0e1a",
        "--origam-color__feedback--info---fgSubtle": "#93c5fd",
        "--origam-color__feedback--success---bg": "#6ee7b7",
        "--origam-color__feedback--success---bgSubtle": "rgba(110, 231, 183, 0.14)",
        "--origam-color__feedback--success---border": "#6ee7b7",
        "--origam-color__feedback--success---fg": "#0f0e1a",
        "--origam-color__feedback--success---fgSubtle": "#6ee7b7",
        "--origam-color__feedback--warning---bg": "#fcd34d",
        "--origam-color__feedback--warning---bgSubtle": "rgba(252, 211, 77, 0.14)",
        "--origam-color__feedback--warning---border": "#fcd34d",
        "--origam-color__feedback--warning---fg": "#0f0e1a",
        "--origam-color__feedback--warning---fgSubtle": "#fcd34d"
    }

export const THEME_BUILDER_PRESET_EDITORIAL_LIGHT_VARS: Record<string, string> = {
        "--origam-alert---border-radius": "0px",
        "--origam-btn---border-color": "rgba(26, 23, 20, 0.40)",
        "--origam-btn---border-radius": "0px",
        "--origam-btn---border-width-ghost": "1px",
        "--origam-btn---border-width-outlined": "1px",
        "--origam-card---background": "var(--origam-color__surface---raised)",
        "--origam-card---border-bottom-width": "1px",
        "--origam-card---border-color": "var(--origam-color__border---default)",
        "--origam-card---border-left-width": "1px",
        "--origam-card---border-right-width": "1px",
        "--origam-card---border-style": "solid",
        "--origam-card---border-top-width": "1px",
        "--origam-chip---background-color": "var(--origam-color__surface---raised)",
        "--origam-chip---border-color": "var(--origam-color__border---default)",
        "--origam-chip---border-radius": "0px",
        "--origam-chip---border-style": "solid",
        "--origam-chip---border-width": "1px",
        "--origam-color__feedback--danger---bg": "#b91c1c",
        "--origam-color__feedback--danger---bgSubtle": "rgba(185, 28, 28, 0.08)",
        "--origam-color__feedback--danger---border": "#b91c1c",
        "--origam-color__feedback--danger---fg": "#ffffff",
        "--origam-color__feedback--danger---fgSubtle": "#991b1b",
        "--origam-color__feedback--info---bg": "#1d4ed8",
        "--origam-color__feedback--info---bgSubtle": "rgba(29, 78, 216, 0.08)",
        "--origam-color__feedback--info---border": "#1d4ed8",
        "--origam-color__feedback--info---fg": "#ffffff",
        "--origam-color__feedback--info---fgSubtle": "#1e40af",
        "--origam-color__feedback--success---bg": "#15803d",
        "--origam-color__feedback--success---bgSubtle": "rgba(21, 128, 61, 0.08)",
        "--origam-color__feedback--success---border": "#15803d",
        "--origam-color__feedback--success---fg": "#ffffff",
        "--origam-color__feedback--success---fgSubtle": "#166534",
        "--origam-color__feedback--warning---bg": "#b45309",
        "--origam-color__feedback--warning---bgSubtle": "rgba(180, 83, 9, 0.08)",
        "--origam-color__feedback--warning---border": "#b45309",
        "--origam-color__feedback--warning---fg": "#ffffff",
        "--origam-color__feedback--warning---fgSubtle": "#92400e",
        "--origam-field---border-color": "rgba(26, 23, 20, 0.40)",
        "--origam-field---border-opacity": "1",
        "--origam-field---border-radius": "0px",
        "--origam-title---font-family": "'Fraunces', 'Playfair Display', Georgia, serif"
    }

export const THEME_BUILDER_PRESET_EDITORIAL_DARK_VARS: Record<string, string> = {
        "--origam-alert---border-radius": "0px",
        "--origam-btn---border-color": "rgba(255, 255, 255, 0.20)",
        "--origam-btn---border-radius": "0px",
        "--origam-btn---border-width-ghost": "1px",
        "--origam-btn---border-width-outlined": "1px",
        "--origam-card---background": "var(--origam-color__surface---raised)",
        "--origam-card---border-bottom-width": "1px",
        "--origam-card---border-color": "var(--origam-color__border---default)",
        "--origam-card---border-left-width": "1px",
        "--origam-card---border-right-width": "1px",
        "--origam-card---border-style": "solid",
        "--origam-card---border-top-width": "1px",
        "--origam-chip---background-color": "var(--origam-color__surface---raised)",
        "--origam-chip---border-color": "var(--origam-color__border---default)",
        "--origam-chip---border-radius": "0px",
        "--origam-chip---border-style": "solid",
        "--origam-chip---border-width": "1px",
        "--origam-color__feedback--danger---bg": "#fca5a5",
        "--origam-color__feedback--danger---bgSubtle": "rgba(252, 165, 165, 0.1)",
        "--origam-color__feedback--danger---border": "#fca5a5",
        "--origam-color__feedback--danger---fg": "#0a0a0a",
        "--origam-color__feedback--danger---fgSubtle": "#fca5a5",
        "--origam-color__feedback--info---bg": "#93c5fd",
        "--origam-color__feedback--info---bgSubtle": "rgba(147, 197, 253, 0.1)",
        "--origam-color__feedback--info---border": "#93c5fd",
        "--origam-color__feedback--info---fg": "#0a0a0a",
        "--origam-color__feedback--info---fgSubtle": "#93c5fd",
        "--origam-color__feedback--success---bg": "#6ee7b7",
        "--origam-color__feedback--success---bgSubtle": "rgba(110, 231, 183, 0.1)",
        "--origam-color__feedback--success---border": "#6ee7b7",
        "--origam-color__feedback--success---fg": "#0a0a0a",
        "--origam-color__feedback--success---fgSubtle": "#6ee7b7",
        "--origam-color__feedback--warning---bg": "#fcd34d",
        "--origam-color__feedback--warning---bgSubtle": "rgba(252, 211, 77, 0.1)",
        "--origam-color__feedback--warning---border": "#fcd34d",
        "--origam-color__feedback--warning---fg": "#0a0a0a",
        "--origam-color__feedback--warning---fgSubtle": "#fcd34d",
        "--origam-field---border-color": "rgba(255, 255, 255, 0.30)",
        "--origam-field---border-opacity": "1",
        "--origam-field---border-radius": "0px",
        "--origam-title---font-family": "'Fraunces', 'Playfair Display', Georgia, serif"
    }

export const THEME_BUILDER_PRESET_MATERIAL_LIGHT_VARS: Record<string, string> = {
        "--origam-alert---border-radius": "var(--origam-radius---lg, 12px)",
        "--origam-alert---box-shadow-elevated": "0 1px 2px rgba(0, 0, 0, 0.3), 0 1px 3px 1px rgba(0, 0, 0, 0.15)",
        "--origam-btn---border-color": "var(--origam-color__border---default)",
        "--origam-btn---border-radius": "999px",
        "--origam-btn---border-radius-rounded": "999px",
        "--origam-btn---border-width-ghost": "1px",
        "--origam-btn---border-width-outlined": "1px",
        "--origam-card---background": "var(--origam-color__surface---raised)",
        "--origam-card---border-color": "var(--origam-color__border---default)",
        "--origam-chip---background-color": "var(--origam-color__surface---raised)",
        "--origam-chip---border-color": "var(--origam-color__border---default)",
        "--origam-chip---border-radius": "999px",
        "--origam-color__feedback--danger---bg": "#b3261e",
        "--origam-color__feedback--danger---bgSubtle": "#f9dedc",
        "--origam-color__feedback--danger---border": "#b3261e",
        "--origam-color__feedback--danger---fg": "#ffffff",
        "--origam-color__feedback--danger---fgSubtle": "#601410",
        "--origam-color__feedback--info---bg": "#0288d1",
        "--origam-color__feedback--info---bgSubtle": "#e1f5fe",
        "--origam-color__feedback--info---border": "#0288d1",
        "--origam-color__feedback--info---fg": "#000000",
        "--origam-color__feedback--info---fgSubtle": "#01579b",
        "--origam-color__feedback--success---bg": "#388e3c",
        "--origam-color__feedback--success---bgSubtle": "#e8f5e9",
        "--origam-color__feedback--success---border": "#388e3c",
        "--origam-color__feedback--success---fg": "#000000",
        "--origam-color__feedback--success---fgSubtle": "#1b5e20",
        "--origam-color__feedback--warning---bg": "#f57c00",
        "--origam-color__feedback--warning---bgSubtle": "#fff3e0",
        "--origam-color__feedback--warning---border": "#f57c00",
        "--origam-color__feedback--warning---fg": "#000000",
        "--origam-color__feedback--warning---fgSubtle": "#9a3412",
        "--origam-title---font-family": "'Roboto', 'Inter', -apple-system, sans-serif"
    }

export const THEME_BUILDER_PRESET_MATERIAL_DARK_VARS: Record<string, string> = {
        "--origam-alert---border-radius": "var(--origam-radius---lg, 12px)",
        "--origam-alert---box-shadow-elevated": "0 1px 2px rgba(0, 0, 0, 0.3), 0 1px 3px 1px rgba(0, 0, 0, 0.15)",
        "--origam-btn---border-color": "var(--origam-color__border---default)",
        "--origam-btn---border-radius": "999px",
        "--origam-btn---border-radius-rounded": "999px",
        "--origam-btn---border-width-ghost": "1px",
        "--origam-btn---border-width-outlined": "1px",
        "--origam-card---background": "var(--origam-color__surface---raised)",
        "--origam-card---border-color": "var(--origam-color__border---default)",
        "--origam-chip---background-color": "var(--origam-color__surface---raised)",
        "--origam-chip---border-color": "var(--origam-color__border---default)",
        "--origam-chip---border-radius": "999px",
        "--origam-color__feedback--danger---bg": "#f2b8b5",
        "--origam-color__feedback--danger---bgSubtle": "#601410",
        "--origam-color__feedback--danger---border": "#f2b8b5",
        "--origam-color__feedback--danger---fg": "#601410",
        "--origam-color__feedback--danger---fgSubtle": "#f9dedc",
        "--origam-color__feedback--info---bg": "#80cefe",
        "--origam-color__feedback--info---bgSubtle": "#003c5c",
        "--origam-color__feedback--info---border": "#80cefe",
        "--origam-color__feedback--info---fg": "#1c1b1f",
        "--origam-color__feedback--info---fgSubtle": "#b3e5fc",
        "--origam-color__feedback--success---bg": "#9ccc65",
        "--origam-color__feedback--success---bgSubtle": "#33401c",
        "--origam-color__feedback--success---border": "#9ccc65",
        "--origam-color__feedback--success---fg": "#1c1b1f",
        "--origam-color__feedback--success---fgSubtle": "#c5e1a5",
        "--origam-color__feedback--warning---bg": "#ffd54f",
        "--origam-color__feedback--warning---bgSubtle": "#3d2f00",
        "--origam-color__feedback--warning---border": "#ffd54f",
        "--origam-color__feedback--warning---fg": "#1c1b1f",
        "--origam-color__feedback--warning---fgSubtle": "#ffe082",
        "--origam-title---font-family": "'Roboto', 'Inter', -apple-system, sans-serif"
    }

export const THEME_BUILDER_PRESET_ECOM_LIGHT_VARS: Record<string, string> = {
        "--origam-alert---border-radius": "6px",
        "--origam-btn---border-color": "#fed7aa",
        "--origam-btn---border-radius": "var(--origam-radius---btn, 6px)",
        "--origam-btn---border-width-ghost": "1px",
        "--origam-btn---border-width-outlined": "1px",
        "--origam-card---background": "#ffffff",
        "--origam-card---border-bottom-width": "1px",
        "--origam-card---border-color": "#fed7aa",
        "--origam-card---border-end-end-radius": "10px",
        "--origam-card---border-end-start-radius": "10px",
        "--origam-card---border-left-width": "1px",
        "--origam-card---border-right-width": "1px",
        "--origam-card---border-start-end-radius": "10px",
        "--origam-card---border-start-start-radius": "10px",
        "--origam-card---border-style": "solid",
        "--origam-card---border-top-width": "1px",
        "--origam-chip---background-color": "var(--origam-color__surface---sunken, #ffedd5)",
        "--origam-chip---border-color": "#fed7aa",
        "--origam-chip---border-radius": "6px",
        "--origam-chip---border-style": "solid",
        "--origam-chip---border-width": "1px",
        "--origam-color__feedback--danger---bg": "#dc2626",
        "--origam-color__feedback--danger---bgSubtle": "#fff1f2",
        "--origam-color__feedback--danger---border": "#dc2626",
        "--origam-color__feedback--danger---fg": "#ffffff",
        "--origam-color__feedback--danger---fgSubtle": "#b91c1c",
        "--origam-color__feedback--info---bg": "#1677ff",
        "--origam-color__feedback--info---bgSubtle": "#eff6ff",
        "--origam-color__feedback--info---border": "#1677ff",
        "--origam-color__feedback--info---fg": "#000000",
        "--origam-color__feedback--info---fgSubtle": "#1d4ed8",
        "--origam-color__feedback--success---bg": "#16a34a",
        "--origam-color__feedback--success---bgSubtle": "#f0fdf4",
        "--origam-color__feedback--success---border": "#16a34a",
        "--origam-color__feedback--success---fg": "#000000",
        "--origam-color__feedback--success---fgSubtle": "#15803d",
        "--origam-color__feedback--warning---bg": "#b45309",
        "--origam-color__feedback--warning---bgSubtle": "#fffbeb",
        "--origam-color__feedback--warning---border": "#b45309",
        "--origam-color__feedback--warning---fg": "#ffffff",
        "--origam-color__feedback--warning---fgSubtle": "#92400e",
        "--origam-field---border-color": "#fb923c",
        "--origam-field---border-opacity": "0.50",
        "--origam-field---border-radius": "6px",
        "--origam-title---font-family": "'Inter', -apple-system, BlinkMacSystemFont, sans-serif"
    }

export const THEME_BUILDER_PRESET_ECOM_DARK_VARS: Record<string, string> = {
        "--origam-alert---border-radius": "6px",
        "--origam-btn---border-color": "rgba(251, 146, 60, 0.30)",
        "--origam-btn---border-radius": "var(--origam-radius---btn, 6px)",
        "--origam-btn---border-width-ghost": "1px",
        "--origam-btn---border-width-outlined": "1px",
        "--origam-card---background": "#2e1b14",
        "--origam-card---border-bottom-width": "1px",
        "--origam-card---border-color": "rgba(251, 146, 60, 0.20)",
        "--origam-card---border-end-end-radius": "10px",
        "--origam-card---border-end-start-radius": "10px",
        "--origam-card---border-left-width": "1px",
        "--origam-card---border-right-width": "1px",
        "--origam-card---border-start-end-radius": "10px",
        "--origam-card---border-start-start-radius": "10px",
        "--origam-card---border-style": "solid",
        "--origam-card---border-top-width": "1px",
        "--origam-chip---background-color": "var(--origam-color__surface---sunken, #231510)",
        "--origam-chip---border-color": "rgba(251, 146, 60, 0.30)",
        "--origam-chip---border-radius": "6px",
        "--origam-chip---border-style": "solid",
        "--origam-chip---border-width": "1px",
        "--origam-color__feedback--danger---bg": "#ef4444",
        "--origam-color__feedback--danger---bgSubtle": "rgba(239, 68, 68, 0.14)",
        "--origam-color__feedback--danger---border": "#ef4444",
        "--origam-color__feedback--danger---fg": "#1a0f0a",
        "--origam-color__feedback--danger---fgSubtle": "#fca5a5",
        "--origam-color__feedback--info---bg": "#60a5fa",
        "--origam-color__feedback--info---bgSubtle": "rgba(96, 165, 250, 0.14)",
        "--origam-color__feedback--info---border": "#60a5fa",
        "--origam-color__feedback--info---fg": "#1a0f0a",
        "--origam-color__feedback--info---fgSubtle": "#93c5fd",
        "--origam-color__feedback--success---bg": "#4ade80",
        "--origam-color__feedback--success---bgSubtle": "rgba(74, 222, 128, 0.14)",
        "--origam-color__feedback--success---border": "#4ade80",
        "--origam-color__feedback--success---fg": "#1a0f0a",
        "--origam-color__feedback--success---fgSubtle": "#86efac",
        "--origam-color__feedback--warning---bg": "#fbbf24",
        "--origam-color__feedback--warning---bgSubtle": "rgba(251, 191, 36, 0.14)",
        "--origam-color__feedback--warning---border": "#fbbf24",
        "--origam-color__feedback--warning---fg": "#1a0f0a",
        "--origam-color__feedback--warning---fgSubtle": "#fcd34d",
        "--origam-field---border-color": "#fb923c",
        "--origam-field---border-opacity": "0.40",
        "--origam-field---border-radius": "6px",
        "--origam-title---font-family": "'Inter', -apple-system, BlinkMacSystemFont, sans-serif"
    }

export const THEME_BUILDER_PRESET_SOBRE_LIGHT_VARS: Record<string, string> = {
        "--origam-alert---border-radius": "10px",
        "--origam-alert---box-shadow-elevated": "0 1px 3px rgba(0, 0, 0, 0.04), 0 8px 24px -16px rgba(0, 0, 0, 0.18)",
        "--origam-btn---border-color": "var(--origam-color__border---strong)",
        "--origam-btn---border-width-ghost": "1px",
        "--origam-btn---border-width-outlined": "1px",
        "--origam-card---background": "var(--origam-color__surface---raised)",
        "--origam-card---border-color": "var(--origam-color__border---default)",
        "--origam-card---border-radius-rounded": "12px",
        "--origam-chip---background-color": "var(--origam-color__surface---raised)",
        "--origam-chip---border-color": "var(--origam-color__border---default)",
        "--origam-color__feedback--danger---bg": "#dc2626",
        "--origam-color__feedback--danger---bgSubtle": "rgba(220, 38, 38, 0.08)",
        "--origam-color__feedback--danger---border": "#dc2626",
        "--origam-color__feedback--danger---fg": "#ffffff",
        "--origam-color__feedback--danger---fgSubtle": "#b91c1c",
        "--origam-color__feedback--info---bg": "#2563eb",
        "--origam-color__feedback--info---bgSubtle": "rgba(37, 99, 235, 0.08)",
        "--origam-color__feedback--info---border": "#2563eb",
        "--origam-color__feedback--info---fg": "#ffffff",
        "--origam-color__feedback--info---fgSubtle": "#1d4ed8",
        "--origam-color__feedback--success---bg": "#16a34a",
        "--origam-color__feedback--success---bgSubtle": "rgba(22, 163, 74, 0.08)",
        "--origam-color__feedback--success---border": "#16a34a",
        "--origam-color__feedback--success---fg": "#000000",
        "--origam-color__feedback--success---fgSubtle": "#15803d",
        "--origam-color__feedback--warning---bg": "#d97706",
        "--origam-color__feedback--warning---bgSubtle": "rgba(217, 119, 6, 0.08)",
        "--origam-color__feedback--warning---border": "#d97706",
        "--origam-color__feedback--warning---fg": "#000000",
        "--origam-color__feedback--warning---fgSubtle": "#b45309"
    }

export const THEME_BUILDER_PRESET_SOBRE_DARK_VARS: Record<string, string> = {
        "--origam-alert---border-radius": "10px",
        "--origam-alert---box-shadow-elevated": "inset 0 1px 0 rgba(255, 255, 255, 0.03), 0 8px 24px -16px rgba(0, 0, 0, 0.6)",
        "--origam-btn---border-color": "var(--origam-color__border---strong)",
        "--origam-btn---border-width-ghost": "1px",
        "--origam-btn---border-width-outlined": "1px",
        "--origam-card---background": "var(--origam-color__surface---raised)",
        "--origam-card---border-color": "var(--origam-color__border---default)",
        "--origam-card---border-radius-rounded": "12px",
        "--origam-chip---background-color": "var(--origam-color__surface---raised)",
        "--origam-chip---border-color": "var(--origam-color__border---default)",
        "--origam-color__feedback--danger---bg": "#f87171",
        "--origam-color__feedback--danger---bgSubtle": "rgba(248, 113, 113, 0.12)",
        "--origam-color__feedback--danger---border": "#f87171",
        "--origam-color__feedback--danger---fg": "#ffffff",
        "--origam-color__feedback--danger---fgSubtle": "#f87171",
        "--origam-color__feedback--info---bg": "#60a5fa",
        "--origam-color__feedback--info---bgSubtle": "rgba(96, 165, 250, 0.12)",
        "--origam-color__feedback--info---border": "#60a5fa",
        "--origam-color__feedback--info---fg": "#0a0a0a",
        "--origam-color__feedback--info---fgSubtle": "#60a5fa",
        "--origam-color__feedback--success---bg": "#6ee7b7",
        "--origam-color__feedback--success---bgSubtle": "rgba(110, 231, 183, 0.12)",
        "--origam-color__feedback--success---border": "#6ee7b7",
        "--origam-color__feedback--success---fg": "#0a0a0a",
        "--origam-color__feedback--success---fgSubtle": "#6ee7b7",
        "--origam-color__feedback--warning---bg": "#fbbf24",
        "--origam-color__feedback--warning---bgSubtle": "rgba(251, 191, 36, 0.12)",
        "--origam-color__feedback--warning---border": "#fbbf24",
        "--origam-color__feedback--warning---fg": "#0a0a0a",
        "--origam-color__feedback--warning---fgSubtle": "#fbbf24"
    }

export const THEME_BUILDER_BRAND_PRESETS: IThemeBuilderPreset[] = [
    {
        key: 'cartoon',
        labelKey: 'theming.preset.cartoon',
        labelFallback: 'Cartoon',
        light: THEME_BUILDER_PRESET_CARTOON_LIGHT_VARS,
        dark: THEME_BUILDER_PRESET_CARTOON_DARK_VARS
    },
    {
        key: 'apple',
        labelKey: 'theming.preset.apple',
        labelFallback: 'Apple',
        light: THEME_BUILDER_PRESET_APPLE_LIGHT_VARS,
        dark: THEME_BUILDER_PRESET_APPLE_DARK_VARS
    },
    {
        key: 'geek',
        labelKey: 'theming.preset.geek',
        labelFallback: 'Geek',
        light: THEME_BUILDER_PRESET_GEEK_LIGHT_VARS,
        dark: THEME_BUILDER_PRESET_GEEK_DARK_VARS
    },
    {
        key: 'glass',
        labelKey: 'theming.preset.glass',
        labelFallback: 'Glass',
        light: THEME_BUILDER_PRESET_GLASS_LIGHT_VARS,
        dark: THEME_BUILDER_PRESET_GLASS_DARK_VARS
    },
    {
        key: 'editorial',
        labelKey: 'theming.preset.editorial',
        labelFallback: 'Editorial',
        light: THEME_BUILDER_PRESET_EDITORIAL_LIGHT_VARS,
        dark: THEME_BUILDER_PRESET_EDITORIAL_DARK_VARS
    },
    {
        key: 'material',
        labelKey: 'theming.preset.material',
        labelFallback: 'Material',
        light: THEME_BUILDER_PRESET_MATERIAL_LIGHT_VARS,
        dark: THEME_BUILDER_PRESET_MATERIAL_DARK_VARS
    },
    {
        key: 'ecom',
        labelKey: 'theming.preset.ecom',
        labelFallback: 'E-commerce',
        light: THEME_BUILDER_PRESET_ECOM_LIGHT_VARS,
        dark: THEME_BUILDER_PRESET_ECOM_DARK_VARS
    },
    {
        key: 'sobre',
        labelKey: 'theming.preset.sobre',
        labelFallback: 'Sobre',
        light: THEME_BUILDER_PRESET_SOBRE_LIGHT_VARS,
        dark: THEME_BUILDER_PRESET_SOBRE_DARK_VARS
    }
]
