export enum CHART_TYPE {
    LINE = 'line',
    AREA = 'area',
    BAR = 'bar',
    COLUMN = 'column',
    PIE = 'pie',
    DONUT = 'donut',
    SCATTER = 'scatter',
    RADAR = 'radar',
    SPLINE = 'spline',
    STEPPED_LINE = 'stepped-line',
    GAUGE = 'gauge',
    PYRAMID = 'pyramid',
    FUNNEL = 'funnel',
    HONEYCOMB = 'honeycomb',
    TREEMAP = 'treemap',
    SANKEY = 'sankey',
    WORD_CLOUD = 'word-cloud',
    HEATMAP = 'heatmap',
    SUNBURST = 'sunburst',
    BOX_PLOT = 'box-plot',
    PICTORIAL = 'pictorial'
}
