import type { IEnumDoc } from '~/interfaces/enums-catalog.interface'

export const CHART_TYPE_ENUM_DOC: IEnumDoc = {
    slug: 'chart-type',
    name: 'CHART_TYPE',
    category: 'Chart',
    descriptionKey: 'enums.catalog.chart_type.description',
    descriptionFallback: 'Master enum of all chart types supported by the Origam chart component family.',
    definition: `export enum CHART_TYPE {
    LINE         = 'line',
    AREA         = 'area',
    BAR          = 'bar',
    COLUMN       = 'column',
    PIE          = 'pie',
    DONUT        = 'donut',
    SCATTER      = 'scatter',
    RADAR        = 'radar',
    SPLINE       = 'spline',
    STEPPED_LINE = 'stepped-line',
    GAUGE        = 'gauge',
    PYRAMID      = 'pyramid',
    FUNNEL       = 'funnel',
    HONEYCOMB    = 'honeycomb',
    TREEMAP      = 'treemap',
    SANKEY       = 'sankey',
    WORD_CLOUD   = 'word-cloud',
    HEATMAP      = 'heatmap',
    SUNBURST     = 'sunburst',
    BOX_PLOT     = 'box-plot',
    PICTORIAL    = 'pictorial',
    CANDLESTICK  = 'candlestick',
    STREAMGRAPH  = 'streamgraph',
    VARIWIDE     = 'variwide',
    POLAR_BAR    = 'polar-bar',
    BULLET       = 'bullet',
    PARETO       = 'pareto',
    MAP          = 'map',
    SPARKLINE    = 'sparkline',
}`,
    values: [
        { value: 'CHART_TYPE.LINE', descriptionKey: 'enums.detail.chart_type.line', descriptionFallback: 'Standard line chart.' },
        { value: 'CHART_TYPE.AREA', descriptionKey: 'enums.detail.chart_type.area', descriptionFallback: 'Area chart with filled region.' },
        { value: 'CHART_TYPE.BAR', descriptionKey: 'enums.detail.chart_type.bar', descriptionFallback: 'Horizontal bar chart.' },
        { value: 'CHART_TYPE.COLUMN', descriptionKey: 'enums.detail.chart_type.column', descriptionFallback: 'Vertical column chart.' },
        { value: 'CHART_TYPE.PIE', descriptionKey: 'enums.detail.chart_type.pie', descriptionFallback: 'Full pie chart.' },
        { value: 'CHART_TYPE.DONUT', descriptionKey: 'enums.detail.chart_type.donut', descriptionFallback: 'Donut chart (pie with hollow center).' },
        { value: 'CHART_TYPE.SCATTER', descriptionKey: 'enums.detail.chart_type.scatter', descriptionFallback: 'Scatter plot.' },
        { value: 'CHART_TYPE.RADAR', descriptionKey: 'enums.detail.chart_type.radar', descriptionFallback: 'Radar / spider chart.' },
        { value: 'CHART_TYPE.SPLINE', descriptionKey: 'enums.detail.chart_type.spline', descriptionFallback: 'Smooth curved line chart.' },
        { value: 'CHART_TYPE.STEPPED_LINE', descriptionKey: 'enums.detail.chart_type.stepped_line', descriptionFallback: 'Step line chart.' },
        { value: 'CHART_TYPE.GAUGE', descriptionKey: 'enums.detail.chart_type.gauge', descriptionFallback: 'Gauge chart (speedometer style).' },
        { value: 'CHART_TYPE.PYRAMID', descriptionKey: 'enums.detail.chart_type.pyramid', descriptionFallback: 'Pyramid chart.' },
        { value: 'CHART_TYPE.FUNNEL', descriptionKey: 'enums.detail.chart_type.funnel', descriptionFallback: 'Funnel chart for conversion steps.' },
        { value: 'CHART_TYPE.HONEYCOMB', descriptionKey: 'enums.detail.chart_type.honeycomb', descriptionFallback: 'Hexagonal honeycomb chart.' },
        { value: 'CHART_TYPE.TREEMAP', descriptionKey: 'enums.detail.chart_type.treemap', descriptionFallback: 'Treemap layout chart.' },
        { value: 'CHART_TYPE.SANKEY', descriptionKey: 'enums.detail.chart_type.sankey', descriptionFallback: 'Sankey flow diagram.' },
        { value: 'CHART_TYPE.WORD_CLOUD', descriptionKey: 'enums.detail.chart_type.word_cloud', descriptionFallback: 'Word cloud visualization.' },
        { value: 'CHART_TYPE.HEATMAP', descriptionKey: 'enums.detail.chart_type.heatmap', descriptionFallback: 'Heatmap grid chart.' },
        { value: 'CHART_TYPE.SUNBURST', descriptionKey: 'enums.detail.chart_type.sunburst', descriptionFallback: 'Sunburst hierarchical chart.' },
        { value: 'CHART_TYPE.BOX_PLOT', descriptionKey: 'enums.detail.chart_type.box_plot', descriptionFallback: 'Box-and-whisker plot.' },
        { value: 'CHART_TYPE.PICTORIAL', descriptionKey: 'enums.detail.chart_type.pictorial', descriptionFallback: 'Pictorial bar chart using symbols.' },
        { value: 'CHART_TYPE.CANDLESTICK', descriptionKey: 'enums.detail.chart_type.candlestick', descriptionFallback: 'OHLC candlestick chart.' },
        { value: 'CHART_TYPE.STREAMGRAPH', descriptionKey: 'enums.detail.chart_type.streamgraph', descriptionFallback: 'Streamgraph (flowing area chart).' },
        { value: 'CHART_TYPE.VARIWIDE', descriptionKey: 'enums.detail.chart_type.variwide', descriptionFallback: 'Variwide chart with variable column widths.' },
        { value: 'CHART_TYPE.POLAR_BAR', descriptionKey: 'enums.detail.chart_type.polar_bar', descriptionFallback: 'Polar bar chart (radial bars).' },
        { value: 'CHART_TYPE.BULLET', descriptionKey: 'enums.detail.chart_type.bullet', descriptionFallback: 'Bullet chart for performance vs. target.' },
        { value: 'CHART_TYPE.PARETO', descriptionKey: 'enums.detail.chart_type.pareto', descriptionFallback: 'Pareto chart (bars + cumulative line).' },
        { value: 'CHART_TYPE.MAP', descriptionKey: 'enums.detail.chart_type.map', descriptionFallback: 'Geographic map chart.' },
        { value: 'CHART_TYPE.SPARKLINE', descriptionKey: 'enums.detail.chart_type.sparkline', descriptionFallback: 'Compact inline sparkline widget.' },
    ],
    usedBy: [],
    sourceFile: 'packages/ds/src/enums/Chart/chart.enum.ts',
    examples: [
        {
            titleKey: 'enums.detail.chart_type.example',
            titleFallback: 'Using the enum in script setup',
            code: `import { CHART_TYPE } from 'origam'

const type = CHART_TYPE.TREEMAP`,
            lang: 'typescript',
        },
    ],
}
