import type { IEnumDoc } from '~/interfaces/enums-catalog.interface'

export const CODE_LANG_ENUM_DOC: IEnumDoc = {
    slug: 'code-lang',
    name: 'CODE_LANG',
    category: 'Code',
    descriptionKey: 'enums.catalog.code_lang.description',
    descriptionFallback: 'Supported syntax-highlighting languages for OrigamCode. Each value maps to a shiki grammar bundle shipped with the component.',
    definition: `export enum CODE_LANG {
    PLAINTEXT = 'plaintext',
    VUE       = 'vue',
    TS        = 'ts',
    JS        = 'js',
    TSX       = 'tsx',
    JSX       = 'jsx',
    SCSS      = 'scss',
    CSS       = 'css',
    JSON      = 'json',
    BASH      = 'bash',
    HTML      = 'html',
    XML       = 'xml',
    YAML      = 'yaml',
    MD        = 'md',
}`,
    values: [
        { value: 'CODE_LANG.PLAINTEXT', descriptionKey: 'enums.detail.code_lang.plaintext', descriptionFallback: 'No syntax highlighting — raw plain text.' },
        { value: 'CODE_LANG.VUE', descriptionKey: 'enums.detail.code_lang.vue', descriptionFallback: 'Vue SFC syntax (template, script, style blocks).' },
        { value: 'CODE_LANG.TS', descriptionKey: 'enums.detail.code_lang.ts', descriptionFallback: 'TypeScript.' },
        { value: 'CODE_LANG.JS', descriptionKey: 'enums.detail.code_lang.js', descriptionFallback: 'JavaScript.' },
        { value: 'CODE_LANG.TSX', descriptionKey: 'enums.detail.code_lang.tsx', descriptionFallback: 'TypeScript with JSX.' },
        { value: 'CODE_LANG.JSX', descriptionKey: 'enums.detail.code_lang.jsx', descriptionFallback: 'JavaScript with JSX.' },
        { value: 'CODE_LANG.SCSS', descriptionKey: 'enums.detail.code_lang.scss', descriptionFallback: 'SCSS (Sass).' },
        { value: 'CODE_LANG.CSS', descriptionKey: 'enums.detail.code_lang.css', descriptionFallback: 'CSS.' },
        { value: 'CODE_LANG.JSON', descriptionKey: 'enums.detail.code_lang.json', descriptionFallback: 'JSON.' },
        { value: 'CODE_LANG.BASH', descriptionKey: 'enums.detail.code_lang.bash', descriptionFallback: 'Bash / shell script.' },
        { value: 'CODE_LANG.HTML', descriptionKey: 'enums.detail.code_lang.html', descriptionFallback: 'HTML.' },
        { value: 'CODE_LANG.XML', descriptionKey: 'enums.detail.code_lang.xml', descriptionFallback: 'XML.' },
        { value: 'CODE_LANG.YAML', descriptionKey: 'enums.detail.code_lang.yaml', descriptionFallback: 'YAML.' },
        { value: 'CODE_LANG.MD', descriptionKey: 'enums.detail.code_lang.md', descriptionFallback: 'Markdown.' },
    ],
    usedBy: [
        { slug: 'code', name: 'Code', propName: 'lang' },
    ],
    sourceFile: 'packages/ds/src/enums/Code/code-lang.enum.ts',
    examples: [
        {
            titleKey: 'enums.detail.code_lang.example',
            titleFallback: 'Rendering a TypeScript snippet',
            code: `<origam-code :lang="CODE_LANG.TS" :code="snippet" />`,
            lang: 'vue',
        },
    ],
}
