import type { IEnumDoc } from '~/interfaces/enums-catalog.interface'

export const MDI_ICONS_ENUM_DOC: IEnumDoc = {
    slug: 'mdi-icons',
    name: 'MDI_ICONS',
    category: 'Icon',
    descriptionKey: 'enums.catalog.mdi_icons.description',
    descriptionFallback: 'Complete Material Design Icons (MDI) catalogue — 7 297 icon identifiers for use with OrigamIcon.',
    definition: `export enum MDI_ICONS {
    AB_TESTING = 'mdi:mdi-ab-testing',
    ABACUS = 'mdi:mdi-abacus',
    ABJAD_ARABIC = 'mdi:mdi-abjad-arabic',
    ABJAD_HEBREW = 'mdi:mdi-abjad-hebrew',
    ABUGIDA_DEVANAGARI = 'mdi:mdi-abugida-devanagari',
    ABUGIDA_THAI = 'mdi:mdi-abugida-thai',
    ACCESS_POINT = 'mdi:mdi-access-point',
    ACCESS_POINT_CHECK = 'mdi:mdi-access-point-check',
    ACCESS_POINT_MINUS = 'mdi:mdi-access-point-minus',
    ACCESS_POINT_NETWORK = 'mdi:mdi-access-point-network',
    ACCESS_POINT_NETWORK_OFF = 'mdi:mdi-access-point-network-off',
    ACCESS_POINT_OFF = 'mdi:mdi-access-point-off',
    ACCESS_POINT_PLUS = 'mdi:mdi-access-point-plus',
    ACCESS_POINT_REMOVE = 'mdi:mdi-access-point-remove',
    ACCOUNT = 'mdi:mdi-account',
    ACCOUNT_ALERT = 'mdi:mdi-account-alert',
    ACCOUNT_ALERT_OUTLINE = 'mdi:mdi-account-alert-outline',
    ACCOUNT_ARROW_DOWN = 'mdi:mdi-account-arrow-down',
    ACCOUNT_ARROW_DOWN_OUTLINE = 'mdi:mdi-account-arrow-down-outline',
    ACCOUNT_ARROW_LEFT = 'mdi:mdi-account-arrow-left',
    // … 7 277 more members …
    ZODIAC_SAGITTARIUS = 'mdi:mdi-zodiac-sagittarius',
    ZODIAC_SCORPIO = 'mdi:mdi-zodiac-scorpio',
    ZODIAC_TAURUS = 'mdi:mdi-zodiac-taurus',
    ZODIAC_VIRGO = 'mdi:mdi-zodiac-virgo',
    BLANK = 'mdi:mdi-blank',
}`,
    values: [
        { value: 'MDI_ICONS.AB_TESTING', descriptionKey: 'enums.detail.mdi_icons.ab_testing', descriptionFallback: 'MDI icon: mdi:mdi-ab-testing.' },
        { value: 'MDI_ICONS.ABACUS', descriptionKey: 'enums.detail.mdi_icons.abacus', descriptionFallback: 'MDI icon: mdi:mdi-abacus.' },
        { value: 'MDI_ICONS.ABJAD_ARABIC', descriptionKey: 'enums.detail.mdi_icons.abjad_arabic', descriptionFallback: 'MDI icon: mdi:mdi-abjad-arabic.' },
        { value: 'MDI_ICONS.ABJAD_HEBREW', descriptionKey: 'enums.detail.mdi_icons.abjad_hebrew', descriptionFallback: 'MDI icon: mdi:mdi-abjad-hebrew.' },
        { value: 'MDI_ICONS.ABUGIDA_DEVANAGARI', descriptionKey: 'enums.detail.mdi_icons.abugida_devanagari', descriptionFallback: 'MDI icon: mdi:mdi-abugida-devanagari.' },
        { value: 'MDI_ICONS.ABUGIDA_THAI', descriptionKey: 'enums.detail.mdi_icons.abugida_thai', descriptionFallback: 'MDI icon: mdi:mdi-abugida-thai.' },
        { value: 'MDI_ICONS.ACCESS_POINT', descriptionKey: 'enums.detail.mdi_icons.access_point', descriptionFallback: 'MDI icon: mdi:mdi-access-point.' },
        { value: 'MDI_ICONS.ACCESS_POINT_CHECK', descriptionKey: 'enums.detail.mdi_icons.access_point_check', descriptionFallback: 'MDI icon: mdi:mdi-access-point-check.' },
        { value: 'MDI_ICONS.ACCESS_POINT_MINUS', descriptionKey: 'enums.detail.mdi_icons.access_point_minus', descriptionFallback: 'MDI icon: mdi:mdi-access-point-minus.' },
        { value: 'MDI_ICONS.ACCESS_POINT_NETWORK', descriptionKey: 'enums.detail.mdi_icons.access_point_network', descriptionFallback: 'MDI icon: mdi:mdi-access-point-network.' },
        { value: 'MDI_ICONS.ACCESS_POINT_NETWORK_OFF', descriptionKey: 'enums.detail.mdi_icons.access_point_network_off', descriptionFallback: 'MDI icon: mdi:mdi-access-point-network-off.' },
        { value: 'MDI_ICONS.ACCESS_POINT_OFF', descriptionKey: 'enums.detail.mdi_icons.access_point_off', descriptionFallback: 'MDI icon: mdi:mdi-access-point-off.' },
        { value: 'MDI_ICONS.ACCESS_POINT_PLUS', descriptionKey: 'enums.detail.mdi_icons.access_point_plus', descriptionFallback: 'MDI icon: mdi:mdi-access-point-plus.' },
        { value: 'MDI_ICONS.ACCESS_POINT_REMOVE', descriptionKey: 'enums.detail.mdi_icons.access_point_remove', descriptionFallback: 'MDI icon: mdi:mdi-access-point-remove.' },
        { value: 'MDI_ICONS.ACCOUNT', descriptionKey: 'enums.detail.mdi_icons.account', descriptionFallback: 'MDI icon: mdi:mdi-account.' },
        { value: 'MDI_ICONS.ACCOUNT_ALERT', descriptionKey: 'enums.detail.mdi_icons.account_alert', descriptionFallback: 'MDI icon: mdi:mdi-account-alert.' },
        { value: 'MDI_ICONS.ACCOUNT_ALERT_OUTLINE', descriptionKey: 'enums.detail.mdi_icons.account_alert_outline', descriptionFallback: 'MDI icon: mdi:mdi-account-alert-outline.' },
        { value: 'MDI_ICONS.ACCOUNT_ARROW_DOWN', descriptionKey: 'enums.detail.mdi_icons.account_arrow_down', descriptionFallback: 'MDI icon: mdi:mdi-account-arrow-down.' },
        { value: 'MDI_ICONS.ACCOUNT_ARROW_DOWN_OUTLINE', descriptionKey: 'enums.detail.mdi_icons.account_arrow_down_outline', descriptionFallback: 'MDI icon: mdi:mdi-account-arrow-down-outline.' },
        { value: 'MDI_ICONS.ACCOUNT_ARROW_LEFT', descriptionKey: 'enums.detail.mdi_icons.account_arrow_left', descriptionFallback: 'MDI icon: mdi:mdi-account-arrow-left.' },
        { value: 'MDI_ICONS.ACCOUNT_ARROW_LEFT_OUTLINE', descriptionKey: 'enums.detail.mdi_icons.account_arrow_left_outline', descriptionFallback: 'MDI icon: mdi:mdi-account-arrow-left-outline.' },
        { value: 'MDI_ICONS.ACCOUNT_ARROW_RIGHT', descriptionKey: 'enums.detail.mdi_icons.account_arrow_right', descriptionFallback: 'MDI icon: mdi:mdi-account-arrow-right.' },
        { value: 'MDI_ICONS.ACCOUNT_ARROW_RIGHT_OUTLINE', descriptionKey: 'enums.detail.mdi_icons.account_arrow_right_outline', descriptionFallback: 'MDI icon: mdi:mdi-account-arrow-right-outline.' },
        { value: 'MDI_ICONS.ACCOUNT_ARROW_UP', descriptionKey: 'enums.detail.mdi_icons.account_arrow_up', descriptionFallback: 'MDI icon: mdi:mdi-account-arrow-up.' },
        { value: 'MDI_ICONS.ACCOUNT_ARROW_UP_OUTLINE', descriptionKey: 'enums.detail.mdi_icons.account_arrow_up_outline', descriptionFallback: 'MDI icon: mdi:mdi-account-arrow-up-outline.' },
        { value: 'MDI_ICONS.ACCOUNT_BADGE', descriptionKey: 'enums.detail.mdi_icons.account_badge', descriptionFallback: 'MDI icon: mdi:mdi-account-badge.' },
        { value: 'MDI_ICONS.ACCOUNT_BADGE_OUTLINE', descriptionKey: 'enums.detail.mdi_icons.account_badge_outline', descriptionFallback: 'MDI icon: mdi:mdi-account-badge-outline.' },
        { value: 'MDI_ICONS.ACCOUNT_BOX', descriptionKey: 'enums.detail.mdi_icons.account_box', descriptionFallback: 'MDI icon: mdi:mdi-account-box.' },
        { value: 'MDI_ICONS.ACCOUNT_BOX_MULTIPLE', descriptionKey: 'enums.detail.mdi_icons.account_box_multiple', descriptionFallback: 'MDI icon: mdi:mdi-account-box-multiple.' },
        { value: 'MDI_ICONS.ACCOUNT_BOX_MULTIPLE_OUTLINE', descriptionKey: 'enums.detail.mdi_icons.account_box_multiple_outline', descriptionFallback: 'MDI icon: mdi:mdi-account-box-multiple-outline.' },
        { value: 'MDI_ICONS.…', descriptionKey: 'enums.detail.mdi_icons.more', descriptionFallback: '…and 7267 more icon members — see the source enum for the full registry.' },
    ],
    usedBy: [
        { slug: 'expansion-panel-header', name: 'ExpansionPanelHeader', propName: 'icon' },
        { slug: 'pagination', name: 'Pagination', propName: 'icon' },
        { slug: 'video', name: 'Video', propName: 'icon' },
        { slug: 'radio-btn', name: 'RadioBtn', propName: 'icon' },
        { slug: 'slide-group', name: 'SlideGroup', propName: 'icon' },
        { slug: 'rich-toolbar', name: 'RichToolbar', propName: 'icon' },
        { slug: 'textarea-field', name: 'TextareaField', propName: 'icon' },
        { slug: 'alert', name: 'Alert', propName: 'icon' },
        { slug: 'snackbar-item', name: 'SnackbarItem', propName: 'icon' },
        { slug: 'date-picker-controls', name: 'DatePickerControls', propName: 'icon' },
    ],
    sourceFile: 'packages/ds/src/enums/Icon/mdi.enum.ts',
    examples: [
        {
            titleKey: 'enums.detail.mdi_icons.example',
            titleFallback: 'Using MDI_ICONS with OrigamIcon',
            code: `import { MDI_ICONS } from 'origam'

// Pass directly to the icon prop
// <origam-icon :icon="MDI_ICONS.ACCOUNT" />`,
            lang: 'typescript',
        },
    ],
}

