import type { IEnumDoc } from '~/interfaces/enums-catalog.interface'

export const TEXT_FIELD_TYPE_ENUM_DOC: IEnumDoc = {
    slug: 'text-field-type',
    name: 'TEXT_FIELD_TYPE',
    category: 'Form & Input',
    descriptionKey: 'enums.catalog.text_field_type.description',
    descriptionFallback: 'TypeScript enum for the HTML input type attribute values supported by OrigamTextField and related field components.',
    definition: `export enum TEXT_FIELD_TYPE {
    TEXT           = 'text',
    NUMBER         = 'number',
    EMAIL          = 'email',
    PASSWORD       = 'password',
    HIDDEN         = 'hidden',
    SEARCH         = 'search',
    TEL            = 'tel',
    URL            = 'url',
    IMAGE          = 'image',
    RANGE          = 'range',
    FILE           = 'file',
    COLOR          = 'color',
    SUBMIT         = 'submit',
    BUTTON         = 'button',
    RESET          = 'reset',
    CHECKBOX       = 'checkbox',
    RADIO          = 'radio',
    TIME           = 'time',
    DATETIME       = 'datetime-local',
    DATE           = 'date',
    MONTH          = 'month',
    WEEK           = 'week',
}`,
    values: [
        { value: 'TEXT_FIELD_TYPE.TEXT', descriptionKey: 'enums.detail.text_field_type.text', descriptionFallback: 'Single-line plain text input.' },
        { value: 'TEXT_FIELD_TYPE.NUMBER', descriptionKey: 'enums.detail.text_field_type.number', descriptionFallback: 'Numeric input with optional stepper controls.' },
        { value: 'TEXT_FIELD_TYPE.EMAIL', descriptionKey: 'enums.detail.text_field_type.email', descriptionFallback: 'Email address input — browser validates basic format.' },
        { value: 'TEXT_FIELD_TYPE.PASSWORD', descriptionKey: 'enums.detail.text_field_type.password', descriptionFallback: 'Password input — characters are masked.' },
        { value: 'TEXT_FIELD_TYPE.HIDDEN', descriptionKey: 'enums.detail.text_field_type.hidden', descriptionFallback: 'Hidden input — not rendered visually, used for form data.' },
        { value: 'TEXT_FIELD_TYPE.SEARCH', descriptionKey: 'enums.detail.text_field_type.search', descriptionFallback: 'Search input — may display a clear button in some browsers.' },
        { value: 'TEXT_FIELD_TYPE.TEL', descriptionKey: 'enums.detail.text_field_type.tel', descriptionFallback: 'Telephone number input — shows numeric keyboard on mobile.' },
        { value: 'TEXT_FIELD_TYPE.URL', descriptionKey: 'enums.detail.text_field_type.url', descriptionFallback: 'URL input — browser may validate format.' },
        { value: 'TEXT_FIELD_TYPE.IMAGE', descriptionKey: 'enums.detail.text_field_type.image', descriptionFallback: 'Image submit button.' },
        { value: 'TEXT_FIELD_TYPE.RANGE', descriptionKey: 'enums.detail.text_field_type.range', descriptionFallback: 'Range slider input.' },
        { value: 'TEXT_FIELD_TYPE.FILE', descriptionKey: 'enums.detail.text_field_type.file', descriptionFallback: 'File picker input.' },
        { value: 'TEXT_FIELD_TYPE.COLOR', descriptionKey: 'enums.detail.text_field_type.color', descriptionFallback: 'Colour picker input.' },
        { value: 'TEXT_FIELD_TYPE.SUBMIT', descriptionKey: 'enums.detail.text_field_type.submit', descriptionFallback: 'Form submit button.' },
        { value: 'TEXT_FIELD_TYPE.BUTTON', descriptionKey: 'enums.detail.text_field_type.button', descriptionFallback: 'Generic button (no default behaviour).' },
        { value: 'TEXT_FIELD_TYPE.RESET', descriptionKey: 'enums.detail.text_field_type.reset', descriptionFallback: 'Form reset button — clears all fields to their default values.' },
        { value: 'TEXT_FIELD_TYPE.CHECKBOX', descriptionKey: 'enums.detail.text_field_type.checkbox', descriptionFallback: 'Checkbox toggle input.' },
        { value: 'TEXT_FIELD_TYPE.RADIO', descriptionKey: 'enums.detail.text_field_type.radio', descriptionFallback: 'Radio button input.' },
        { value: 'TEXT_FIELD_TYPE.TIME', descriptionKey: 'enums.detail.text_field_type.time', descriptionFallback: 'Time input (HH:MM).' },
        { value: 'TEXT_FIELD_TYPE.DATETIME', descriptionKey: 'enums.detail.text_field_type.datetime', descriptionFallback: 'Date-and-time input (datetime-local).' },
        { value: 'TEXT_FIELD_TYPE.DATE', descriptionKey: 'enums.detail.text_field_type.date', descriptionFallback: 'Date input (YYYY-MM-DD).' },
        { value: 'TEXT_FIELD_TYPE.MONTH', descriptionKey: 'enums.detail.text_field_type.month', descriptionFallback: 'Month and year input.' },
        { value: 'TEXT_FIELD_TYPE.WEEK', descriptionKey: 'enums.detail.text_field_type.week', descriptionFallback: 'ISO week number input.' },
    ],
    usedBy: [
        { slug: 'text-field', name: 'TextField', propName: 'type' },
        { slug: 'number-field', name: 'NumberField', propName: 'type' },
        { slug: 'password-field', name: 'PasswordField', propName: 'type' },
        { slug: 'color-picker-field', name: 'ColorPickerField', propName: 'type' },
        { slug: 'date-picker-field', name: 'DatePickerField', propName: 'type' },
        { slug: 'select', name: 'Select', propName: 'type' },
    ],
    sourceFile: 'packages/ds/src/enums/TextField/text-field.enum.ts',
    examples: [
        {
            titleKey: 'enums.detail.text_field_type.example',
            titleFallback: 'Using the enum in script setup',
            code: `import { TEXT_FIELD_TYPE } from 'origam'

const fieldType: TEXT_FIELD_TYPE = TEXT_FIELD_TYPE.EMAIL`,
            lang: 'typescript',
        },
    ],
}
