import { MDI_ICONS } from '@origam/enums'
import type { IOptions } from '@origam/interfaces'

export const iconList: Array<IOptions<string>> = [
    { label: '(none)', value: undefined },
    { label: 'Home', value: MDI_ICONS.HOME },
    { label: 'Account', value: MDI_ICONS.ACCOUNT },
    { label: 'Magnify (Search)', value: MDI_ICONS.MAGNIFY },
    { label: 'Close', value: MDI_ICONS.CLOSE },
    { label: 'Check', value: MDI_ICONS.CHECK },
    { label: 'Alert', value: MDI_ICONS.ALERT },
    { label: 'Information', value: MDI_ICONS.INFORMATION },
    { label: 'Plus', value: MDI_ICONS.PLUS },
    { label: 'Minus', value: MDI_ICONS.MINUS },
    { label: 'Pencil (Edit)', value: MDI_ICONS.PENCIL },
    { label: 'Delete', value: MDI_ICONS.DELETE },
    { label: 'Heart', value: MDI_ICONS.HEART },
    { label: 'Star', value: MDI_ICONS.STAR },
    { label: 'Arrow Right', value: MDI_ICONS.ARROW_RIGHT },
    { label: 'Arrow Down', value: MDI_ICONS.ARROW_DOWN },
    { label: 'Menu', value: MDI_ICONS.MENU },
    { label: 'Cog (Settings)', value: MDI_ICONS.COG },
    { label: 'Bell', value: MDI_ICONS.BELL },
    { label: 'Eye', value: MDI_ICONS.EYE },
    { label: 'Lock', value: MDI_ICONS.LOCK },
    { label: 'Calendar', value: MDI_ICONS.CALENDAR },
    { label: 'Download', value: MDI_ICONS.DOWNLOAD },
    { label: 'Upload', value: MDI_ICONS.UPLOAD },
    { label: 'Send', value: MDI_ICONS.SEND },
    { label: 'Share', value: MDI_ICONS.SHARE },
    { label: 'Filter', value: MDI_ICONS.FILTER },
    { label: 'Refresh', value: MDI_ICONS.REFRESH },
]
