import type { ITypeDoc } from '~/interfaces/types-catalog.interface'

export const CHART_TYPE_TYPE_DOC: ITypeDoc = {
    slug: 'chart-type',
    name: 'TChartType',
    kind: 'type',
    category: 'Data Display',
    descriptionKey: 'types.catalog.chart_type.description',
    descriptionFallback: 'Union of all visualisation primitives accepted by OrigamChart — selects the topology and path generator at runtime.',
    definition: `export type TChartType = \`\${CHART_TYPE}\`

// Where CHART_TYPE is:
export enum CHART_TYPE {
    LINE         = 'line',
    AREA         = 'area',
    BAR          = 'bar',
    COLUMN       = 'column',
    PIE          = 'pie',
    DONUT        = 'donut',
    SCATTER      = 'scatter',
    RADAR        = 'radar',
    SPLINE       = 'spline',
    STEPPED_LINE = 'stepped-line',
    GAUGE        = 'gauge',
    PYRAMID      = 'pyramid',
    FUNNEL       = 'funnel',
    HONEYCOMB    = 'honeycomb',
    TREEMAP      = 'treemap',
    SANKEY       = 'sankey',
    WORD_CLOUD   = 'word-cloud',
    HEATMAP      = 'heatmap',
    SUNBURST     = 'sunburst',
    BOX_PLOT     = 'box-plot',
    PICTORIAL    = 'pictorial',
    CANDLESTICK  = 'candlestick',
    STREAMGRAPH  = 'streamgraph',
    VARIWIDE     = 'variwide',
    POLAR_BAR    = 'polar-bar',
    BULLET       = 'bullet',
    PARETO       = 'pareto',
    MAP          = 'map',
    SPARKLINE    = 'sparkline'
}`,
    values: [
        { value: 'line', descriptionKey: 'types.detail.chart_type.line', descriptionFallback: 'Connects data points with line segments. Supports smoothing prop.' },
        { value: 'area', descriptionKey: 'types.detail.chart_type.area', descriptionFallback: 'Filled area beneath the line — good for cumulative or part-to-whole data.' },
        { value: 'bar', descriptionKey: 'types.detail.chart_type.bar', descriptionFallback: 'Horizontal rectangles — one per data point along the Y axis.' },
        { value: 'column', descriptionKey: 'types.detail.chart_type.column', descriptionFallback: 'Vertical rectangles — classic bar chart orientation along the X axis.' },
        { value: 'pie', descriptionKey: 'types.detail.chart_type.pie', descriptionFallback: 'Circular segments proportional to each series value. No inner radius.' },
        { value: 'donut', descriptionKey: 'types.detail.chart_type.donut', descriptionFallback: 'Like pie but with a hollow centre — centre slot can display a summary.' },
        { value: 'scatter', descriptionKey: 'types.detail.chart_type.scatter', descriptionFallback: 'Individual circles at data coordinates — no connecting path.' },
        { value: 'radar', descriptionKey: 'types.detail.chart_type.radar', descriptionFallback: 'Spider / web chart — each axis radiates from the centre.' },
        { value: 'spline', descriptionKey: 'types.detail.chart_type.spline', descriptionFallback: 'Smooth curved line — equivalent to line with smoothing="monotone".' },
        { value: 'stepped-line', descriptionKey: 'types.detail.chart_type.stepped_line', descriptionFallback: 'Staircase polyline with right-angle segments — for step-function data.' },
        { value: 'gauge', descriptionKey: 'types.detail.chart_type.gauge', descriptionFallback: 'Semicircular arc dial showing a single KPI value with min/max range.' },
        { value: 'pyramid', descriptionKey: 'types.detail.chart_type.pyramid', descriptionFallback: 'Stacked trapezoids widening downward — hierarchy or funnel metaphor.' },
        { value: 'funnel', descriptionKey: 'types.detail.chart_type.funnel', descriptionFallback: 'Narrowing trapezoids from top to bottom — conversion pipeline stages.' },
        { value: 'honeycomb', descriptionKey: 'types.detail.chart_type.honeycomb', descriptionFallback: 'Hexagonal tile grid — categorical or heatmap colour mode.' },
        { value: 'treemap', descriptionKey: 'types.detail.chart_type.treemap', descriptionFallback: 'Nested rectangles sized by value — hierarchical data at a glance.' },
        { value: 'sankey', descriptionKey: 'types.detail.chart_type.sankey', descriptionFallback: 'Flow diagram with weighted links between nodes — energy or traffic flows.' },
        { value: 'word-cloud', descriptionKey: 'types.detail.chart_type.word_cloud', descriptionFallback: 'Text tags sized by frequency — qualitative corpus analysis.' },
        { value: 'heatmap', descriptionKey: 'types.detail.chart_type.heatmap', descriptionFallback: 'Matrix of colour-encoded cells — two-dimensional correlation or density.' },
        { value: 'sunburst', descriptionKey: 'types.detail.chart_type.sunburst', descriptionFallback: 'Radial partition chart — hierarchical data as concentric arcs.' },
        { value: 'box-plot', descriptionKey: 'types.detail.chart_type.box_plot', descriptionFallback: 'Box-and-whisker plot — median, quartiles and outlier distribution.' },
        { value: 'pictorial', descriptionKey: 'types.detail.chart_type.pictorial', descriptionFallback: 'Icon / silhouette filled proportionally to a value — infographic-style.' },
        { value: 'candlestick', descriptionKey: 'types.detail.chart_type.candlestick', descriptionFallback: 'OHLC chart — open/high/low/close per period for financial data.' },
        { value: 'streamgraph', descriptionKey: 'types.detail.chart_type.streamgraph', descriptionFallback: 'Stacked area chart centred around a flowing baseline — temporal flow.' },
        { value: 'variwide', descriptionKey: 'types.detail.chart_type.variwide', descriptionFallback: 'Column chart where column width encodes a second dimension of data.' },
        { value: 'polar-bar', descriptionKey: 'types.detail.chart_type.polar_bar', descriptionFallback: 'Bars arranged radially around a polar axis — cyclical comparisons.' },
        { value: 'bullet', descriptionKey: 'types.detail.chart_type.bullet', descriptionFallback: 'Compact horizontal bar with target marker and performance bands.' },
        { value: 'pareto', descriptionKey: 'types.detail.chart_type.pareto', descriptionFallback: 'Column chart with cumulative percentage line — 80/20 analysis.' },
        { value: 'map', descriptionKey: 'types.detail.chart_type.map', descriptionFallback: 'Choropleth map — geographic regions coloured by metric value.' },
        { value: 'sparkline', descriptionKey: 'types.detail.chart_type.sparkline', descriptionFallback: 'Micro-chart — axis-less, label-less trend line for inline KPI context.' },
    ],
    usedBy: [
        { slug: 'chart', name: 'Chart', propName: 'type' },
    ],
    sourceFile: 'packages/ds/src/types/Chart/chart-type.type.ts',
    examples: [
        {
            titleKey: 'types.detail.chart_type.example',
            titleFallback: 'Donut chart with two series',
            code: `<origam-chart
  type="donut"
  :series="[
    { name: 'Vue', data: [65] },
    { name: 'React', data: [25] },
    { name: 'Angular', data: [10] },
  ]"
/>`,
            lang: 'html',
        },
    ],
}
