/**
 * THEME_BUILDER_BRAND_PRESETS — seed values for the /theming builder, one entry
 * per brand theme (light + dark bundled). Each map is the SUBSET of the brand
 * theme cssVars that the builder actually exposes (the keys in
 * THEME_BUILDER_PRESET_LIGHT_VARS from theme-builder-presets.const.ts).
 *
 * GÉNÉRÉ depuis packages/marketing/src/assets/css/themes/*.css
 * par scripts/generate-brand-presets.mjs. Valeurs RÉELLES extraites des CSS
 * de marque — ne PAS éditer à la main. Régénérer via:
 *   node scripts/generate-brand-presets.mjs
 */
import type { IThemeBuilderPreset } from '~/interfaces/theme-builder.interface'

export const THEME_BUILDER_PRESET_CARTOON_LIGHT_VARS: Record<string, string> = {
        "--origam-font-family---heading": "Inter, -apple-system, 'system-ui', sans-serif",
        "--origam-title---font-family": "Inter, -apple-system, 'system-ui', sans-serif",
        "--origam-page---background-image": "radial-gradient(circle at 10% 12%, #ffe5a5 0%, transparent 26%), radial-gradient(circle at 90% 14%, #c5e8ff 0%, transparent 26%), radial-gradient(circle at 78% 88%, #ffd6e8 0%, transparent 28%), radial-gradient(circle at 14% 90%, #c8f5d9 0%, transparent 26%)",
        "--origam-appbar---bg": "#fff9f0",
        "--origam-menu---background": "var(--origam-color__surface---default)",
        "--origam-menu---color": "var(--origam-color__text---primary)",
        "--origam-menu---border-radius": "14px",
        "--origam-menu---box-shadow": "4px 4px 0 #171717, 0 0 0 3px #171717",
        "--origam-menu__content---padding": "6px",
        "--origam-list---background": "transparent",
        "--origam-list---padding-block-start": "0",
        "--origam-list---padding-block-end": "0",
        "--origam-list-item---padding-inline-start": "12px",
        "--origam-list-item---padding-inline-end": "12px",
        "--origam-gradient---hero-glow": "radial-gradient(circle at 10% 10%, #fcd34d 0%, transparent 30%)",
        "--origam-gradient---cta-glow": "radial-gradient(circle at 90% 10%, #fbcfe8 0%, transparent 30%)",
        "--origam-gradient---cta-glow-top": "radial-gradient(circle at 50% 0%, #fcd34d 0%, transparent 30%)",
        "--origam-gradient---hero-title": "linear-gradient(90deg, #7c3aed, #ec4899, #f59e0b)",
        "--origam-gradient---hero-grid": "linear-gradient(rgba(23, 23, 23, 0.06) 1px, transparent 1px), linear-gradient(90deg, rgba(23, 23, 23, 0.06) 1px, transparent 1px)",
        "--origam-gradient---kpi-value": "linear-gradient(#ff8fa3, #ff8fa3)",
        "--origam-chip---border-color": "#171717",
        "--origam-chip---border-style": "solid",
        "--origam-chip---border-width": "3px",
        "--origam-chip---border-width-outlined": "3px",
        "--origam-gradient---btn-primary": "linear-gradient(#ff8fa3, #ff8fa3)",
        "--origam-gradient---btn-secondary": "none",
        "--origam-btn---border-color": "#171717",
        "--origam-btn---border-width-outlined": "3px",
        "--origam-btn---border-width-ghost": "3px",
        "--origam-btn---box-shadow-elevated": "4px 4px 0 #171717",
        "--origam-btn---box-shadow-ghost": "4px 4px 0 #171717",
        "--origam-card---box-shadow": "6px 6px 0 #171717",
        "--origam-code---border-width": "3px",
        "--origam-code---border-color": "#171717",
        "--origam-color__feedback--success---bg": "#16a34a",
        "--origam-color__feedback--success---bgSubtle": "#bbf7d0",
        "--origam-color__feedback--success---fg": "#000000",
        "--origam-color__feedback--success---fgSubtle": "#166534",
        "--origam-color__feedback--success---border": "#171717",
        "--origam-color__feedback--warning---bg": "#fbbf24",
        "--origam-color__feedback--warning---bgSubtle": "#fef3c7",
        "--origam-color__feedback--warning---fg": "#171717",
        "--origam-color__feedback--warning---fgSubtle": "#b45309",
        "--origam-color__feedback--warning---border": "#171717",
        "--origam-color__feedback--danger---bg": "#ef4444",
        "--origam-color__feedback--danger---bgSubtle": "#fecdd3",
        "--origam-color__feedback--danger---fg": "#000000",
        "--origam-color__feedback--danger---fgSubtle": "#b91c1c",
        "--origam-color__feedback--danger---border": "#171717",
        "--origam-color__feedback--info---bg": "#60a5fa",
        "--origam-color__feedback--info---bgSubtle": "#dbeafe",
        "--origam-color__feedback--info---fg": "#171717",
        "--origam-color__feedback--info---fgSubtle": "#1d4ed8",
        "--origam-color__feedback--info---border": "#171717",
        "--origam-card---border-color": "var(--origam-color__border---default)",
        "--origam-card---border-style": "solid",
        "--origam-card---border-top-width": "3px",
        "--origam-card---border-right-width": "3px",
        "--origam-card---border-bottom-width": "3px",
        "--origam-card---border-left-width": "3px",
        "--origam-field---border-width": "3px",
        "--origam-field---border-opacity": "1",
        "--origam-field---border-color": "#171717"
    }

export const THEME_BUILDER_PRESET_CARTOON_DARK_VARS: Record<string, string> = {
        "--origam-font-family---heading": "Inter, -apple-system, 'system-ui', sans-serif",
        "--origam-title---font-family": "Inter, -apple-system, 'system-ui', sans-serif",
        "--origam-page---background-image": "none",
        "--origam-appbar---bg": "#1a1a1a",
        "--origam-menu---background": "var(--origam-color__surface---default)",
        "--origam-menu---color": "var(--origam-color__text---primary)",
        "--origam-menu---border-radius": "14px",
        "--origam-menu---box-shadow": "4px 4px 0 #fffefb, 0 0 0 3px #fffefb",
        "--origam-menu__content---padding": "6px",
        "--origam-list---background": "transparent",
        "--origam-list---padding-block-start": "0",
        "--origam-list---padding-block-end": "0",
        "--origam-list-item---padding-inline-start": "12px",
        "--origam-list-item---padding-inline-end": "12px",
        "--origam-card---border-color": "#fffefb",
        "--origam-card---border-style": "solid",
        "--origam-card---border-top-width": "3px",
        "--origam-card---border-right-width": "3px",
        "--origam-card---border-bottom-width": "3px",
        "--origam-card---border-left-width": "3px",
        "--origam-chip---border-color": "#fffefb",
        "--origam-chip---border-style": "solid",
        "--origam-chip---border-width": "3px",
        "--origam-chip---border-width-outlined": "3px",
        "--origam-gradient---hero-glow": "radial-gradient(circle at 10% 14%, rgba(252, 211, 77, 0.50) 0%, transparent 38%), radial-gradient(circle at 90% 14%, rgba(251, 207, 232, 0.42) 0%, transparent 38%)",
        "--origam-gradient---cta-glow": "radial-gradient(circle at 88% 35%, rgba(251, 207, 232, 0.40) 0%, transparent 45%)",
        "--origam-gradient---cta-glow-top": "radial-gradient(circle at 12% 0%, rgba(252, 211, 77, 0.45) 0%, transparent 45%)",
        "--origam-gradient---hero-title": "linear-gradient(90deg, #7c3aed, #ec4899, #f59e0b)",
        "--origam-gradient---hero-grid": "linear-gradient(rgba(255, 254, 251, 0.08) 1px, transparent 1px), linear-gradient(90deg, rgba(255, 254, 251, 0.08) 1px, transparent 1px)",
        "--origam-gradient---kpi-value": "linear-gradient(#ff8fa3, #ff8fa3)",
        "--origam-gradient---btn-primary": "linear-gradient(#ff8fa3, #ff8fa3)",
        "--origam-gradient---btn-secondary": "none",
        "--origam-btn---border-color": "#fffefb",
        "--origam-btn---border-width-outlined": "3px",
        "--origam-btn---border-width-ghost": "3px",
        "--origam-btn---box-shadow-elevated": "4px 4px 0 #fffefb",
        "--origam-btn---box-shadow-ghost": "4px 4px 0 #fffefb",
        "--origam-card---box-shadow": "6px 6px 0 #171717",
        "--origam-code---border-width": "3px",
        "--origam-code---border-color": "#fffefb",
        "--origam-color__feedback--success---bg": "#4ade80",
        "--origam-color__feedback--success---bgSubtle": "#14532d",
        "--origam-color__feedback--success---fg": "#171717",
        "--origam-color__feedback--success---fgSubtle": "#86efac",
        "--origam-color__feedback--success---border": "#fffefb",
        "--origam-color__feedback--warning---bg": "#fbbf24",
        "--origam-color__feedback--warning---bgSubtle": "#78350f",
        "--origam-color__feedback--warning---fg": "#171717",
        "--origam-color__feedback--warning---fgSubtle": "#fcd34d",
        "--origam-color__feedback--warning---border": "#fffefb",
        "--origam-color__feedback--danger---bg": "#f87171",
        "--origam-color__feedback--danger---bgSubtle": "#7f1d1d",
        "--origam-color__feedback--danger---fg": "#171717",
        "--origam-color__feedback--danger---fgSubtle": "#fca5a5",
        "--origam-color__feedback--danger---border": "#fffefb",
        "--origam-color__feedback--info---bg": "#60a5fa",
        "--origam-color__feedback--info---bgSubtle": "#1e3a8a",
        "--origam-color__feedback--info---fg": "#171717",
        "--origam-color__feedback--info---fgSubtle": "#93c5fd",
        "--origam-color__feedback--info---border": "#fffefb",
        "--origam-code---background-color": "#262626",
        "--origam-field---border-color": "#fffefb"
    }

export const THEME_BUILDER_PRESET_APPLE_LIGHT_VARS: Record<string, string> = {
        "--origam-font-family---heading": "-apple-system, BlinkMacSystemFont, 'SF Pro Display', 'Inter', sans-serif",
        "--origam-title---font-family": "-apple-system, BlinkMacSystemFont, 'SF Pro Display', 'Inter', sans-serif",
        "--origam-appbar---bg": "color-mix(in srgb, #ffffff 80%, transparent)",
        "--origam-appbar---backdrop-filter": "saturate(180%) blur(20px)",
        "--origam-menu---background": "color-mix(in srgb, var(--origam-color__surface---raised) 92%, transparent)",
        "--origam-menu---color": "var(--origam-color__text---primary)",
        "--origam-menu---border-radius": "12px",
        "--origam-menu---box-shadow": "0 4px 16px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.06), 0 0 0 0.5px var(--origam-color__border---default)",
        "--origam-menu__content---padding": "6px",
        "--origam-list---background": "transparent",
        "--origam-list---padding-block-start": "0",
        "--origam-list---padding-block-end": "0",
        "--origam-list-item---padding-inline-start": "12px",
        "--origam-list-item---padding-inline-end": "12px",
        "--origam-gradient---hero-glow": "radial-gradient(ellipse 80% 50% at 50% 0%, rgba(0, 113, 227, 0.06), transparent 60%)",
        "--origam-gradient---cta-glow": "none",
        "--origam-gradient---cta-glow-top": "radial-gradient(ellipse 70% 55% at 50% 0%, rgba(0, 113, 227, 0.06), transparent 65%)",
        "--origam-gradient---hero-title": "linear-gradient(180deg, #1d1d1f 0%, #515154 100%)",
        "--origam-gradient---hero-grid": "linear-gradient(rgba(210, 210, 215, 0.40) 1px, transparent 1px), linear-gradient(90deg, rgba(210, 210, 215, 0.40) 1px, transparent 1px)",
        "--origam-gradient---kpi-value": "linear-gradient(#1d1d1f, #1d1d1f)",
        "--origam-gradient---btn-primary": "none",
        "--origam-gradient---btn-secondary": "none",
        "--origam-btn---border-color": "#d2d2d7",
        "--origam-btn---border-width-outlined": "1px",
        "--origam-btn---border-width-ghost": "1px",
        "--origam-btn---box-shadow-elevated": "0 2px 8px rgba(0, 113, 227, 0.25)",
        "--origam-btn---box-shadow-ghost": "none",
        "--origam-card---box-shadow": "var(--origam-shadow---card-elevated)",
        "--origam-code---border-radius": "12px",
        "--origam-color__feedback--success---bg": "#28cd41",
        "--origam-color__feedback--success---bgSubtle": "#e8f8ec",
        "--origam-color__feedback--success---fg": "#000000",
        "--origam-color__feedback--success---fgSubtle": "#166534",
        "--origam-color__feedback--success---border": "#28cd41",
        "--origam-color__feedback--warning---bg": "#ff9f0a",
        "--origam-color__feedback--warning---bgSubtle": "#fff4e5",
        "--origam-color__feedback--warning---fg": "#000000",
        "--origam-color__feedback--warning---fgSubtle": "#78350f",
        "--origam-color__feedback--warning---border": "#ff9f0a",
        "--origam-color__feedback--danger---bg": "#ff3b30",
        "--origam-color__feedback--danger---bgSubtle": "#ffe9e7",
        "--origam-color__feedback--danger---fg": "#000000",
        "--origam-color__feedback--danger---fgSubtle": "#c2271c",
        "--origam-color__feedback--danger---border": "#ff3b30",
        "--origam-color__feedback--info---bg": "#0071e3",
        "--origam-color__feedback--info---bgSubtle": "#f0f7ff",
        "--origam-color__feedback--info---fg": "#ffffff",
        "--origam-color__feedback--info---fgSubtle": "#0058b0",
        "--origam-color__feedback--info---border": "#0071e3"
    }

export const THEME_BUILDER_PRESET_APPLE_DARK_VARS: Record<string, string> = {
        "--origam-font-family---heading": "-apple-system, BlinkMacSystemFont, 'SF Pro Display', 'Inter', sans-serif",
        "--origam-title---font-family": "-apple-system, BlinkMacSystemFont, 'SF Pro Display', 'Inter', sans-serif",
        "--origam-appbar---bg": "color-mix(in srgb, #000000 80%, transparent)",
        "--origam-appbar---backdrop-filter": "saturate(180%) blur(20px)",
        "--origam-menu---background": "var(--origam-color__surface---raised)",
        "--origam-menu---color": "var(--origam-color__text---primary)",
        "--origam-menu---border-radius": "12px",
        "--origam-menu---box-shadow": "0 4px 24px rgba(0, 0, 0, 0.50), 0 1px 2px rgba(0, 0, 0, 0.40), 0 0 0 0.5px var(--origam-color__border---default)",
        "--origam-menu__content---padding": "6px",
        "--origam-list---background": "transparent",
        "--origam-list---padding-block-start": "0",
        "--origam-list---padding-block-end": "0",
        "--origam-list-item---padding-inline-start": "12px",
        "--origam-list-item---padding-inline-end": "12px",
        "--origam-gradient---hero-glow": "radial-gradient(ellipse 80% 50% at 50% 0%, rgba(10, 132, 255, 0.08), transparent 60%)",
        "--origam-gradient---cta-glow": "none",
        "--origam-gradient---cta-glow-top": "radial-gradient(ellipse 70% 55% at 50% 0%, rgba(10, 132, 255, 0.10), transparent 65%)",
        "--origam-gradient---hero-title": "linear-gradient(180deg, #f5f5f7 0%, #a1a1a6 100%)",
        "--origam-gradient---hero-grid": "linear-gradient(rgba(56, 56, 58, 0.40) 1px, transparent 1px), linear-gradient(90deg, rgba(56, 56, 58, 0.40) 1px, transparent 1px)",
        "--origam-gradient---kpi-value": "linear-gradient(#f5f5f7, #f5f5f7)",
        "--origam-gradient---btn-primary": "none",
        "--origam-gradient---btn-secondary": "none",
        "--origam-btn---border-color": "#38383a",
        "--origam-btn---border-width-outlined": "1px",
        "--origam-btn---border-width-ghost": "1px",
        "--origam-btn---box-shadow-elevated": "0 2px 8px rgba(10, 132, 255, 0.30)",
        "--origam-btn---box-shadow-ghost": "none",
        "--origam-card---box-shadow": "var(--origam-shadow---card-elevated)",
        "--origam-code---border-radius": "12px",
        "--origam-color__feedback--success---bg": "#30d158",
        "--origam-color__feedback--success---bgSubtle": "rgba(48, 209, 88, 0.16)",
        "--origam-color__feedback--success---fg": "#000000",
        "--origam-color__feedback--success---fgSubtle": "#64e47c",
        "--origam-color__feedback--success---border": "#30d158",
        "--origam-color__feedback--warning---bg": "#ff9f0a",
        "--origam-color__feedback--warning---bgSubtle": "rgba(255, 159, 10, 0.16)",
        "--origam-color__feedback--warning---fg": "#000000",
        "--origam-color__feedback--warning---fgSubtle": "#ffb445",
        "--origam-color__feedback--warning---border": "#ff9f0a",
        "--origam-color__feedback--danger---bg": "#ff453a",
        "--origam-color__feedback--danger---bgSubtle": "rgba(255, 69, 58, 0.16)",
        "--origam-color__feedback--danger---fg": "#ffffff",
        "--origam-color__feedback--danger---fgSubtle": "#ff6961",
        "--origam-color__feedback--danger---border": "#ff453a",
        "--origam-color__feedback--info---bg": "#0a84ff",
        "--origam-color__feedback--info---bgSubtle": "rgba(10, 132, 255, 0.16)",
        "--origam-color__feedback--info---fg": "#ffffff",
        "--origam-color__feedback--info---fgSubtle": "#64b5ff",
        "--origam-color__feedback--info---border": "#0a84ff"
    }

export const THEME_BUILDER_PRESET_GEEK_LIGHT_VARS: Record<string, string> = {
        "--origam-font-family---heading": "'JetBrains Mono', 'Fira Code', ui-monospace, monospace",
        "--origam-title---font-family": "'JetBrains Mono', 'Fira Code', ui-monospace, monospace",
        "--origam-appbar---bg": "rgba(251, 245, 255, 0.80)",
        "--origam-menu---background": "var(--origam-color__surface---default)",
        "--origam-menu---color": "var(--origam-color__text---primary)",
        "--origam-menu---border-radius": "4px",
        "--origam-menu---box-shadow": "0 4px 16px -4px rgba(124, 58, 237, 0.14), 0 1px 4px -1px rgba(124, 58, 237, 0.08), 0 0 0 1px var(--origam-color__border---default)",
        "--origam-menu__content---padding": "4px",
        "--origam-list---background": "transparent",
        "--origam-list---padding-block-start": "0",
        "--origam-list---padding-block-end": "0",
        "--origam-list-item---padding-inline-start": "12px",
        "--origam-list-item---padding-inline-end": "12px",
        "--origam-gradient---hero-glow": "radial-gradient(ellipse 60% 40% at 50% 0%, rgba(124, 58, 237, 0.18), transparent 65%)",
        "--origam-gradient---cta-glow": "radial-gradient(ellipse 80% 60% at 80% 30%, rgba(139, 92, 246, 0.12), transparent 70%)",
        "--origam-gradient---cta-glow-top": "radial-gradient(ellipse 70% 55% at 50% 0%, rgba(162, 28, 175, 0.14), transparent 65%)",
        "--origam-gradient---hero-title": "linear-gradient(var(--origam-color__text---ink), var(--origam-color__text---ink))",
        "--origam-gradient---hero-grid": "linear-gradient(var(--origam-color__border---default) 1px, transparent 1px), linear-gradient(90deg, var(--origam-color__border---default) 1px, transparent 1px)",
        "--origam-gradient---kpi-value": "linear-gradient(110deg, #0891b2 0%, #a21caf 55%, #db2777 100%)",
        "--origam-gradient---btn-primary": "linear-gradient(110deg, #0891b2, #a21caf 60%, #db2777)",
        "--origam-gradient---btn-secondary": "none",
        "--origam-btn---border-color": "rgba(217, 70, 239, 0.55)",
        "--origam-btn---border-width-outlined": "1px",
        "--origam-btn---border-width-ghost": "1px",
        "--origam-btn---box-shadow-elevated": "0 4px 14px -4px rgba(124, 58, 237, 0.30), 0 1px 3px -1px rgba(124, 58, 237, 0.15)",
        "--origam-btn---box-shadow-ghost": "rgba(217, 70, 239, 0.35) 0px 0px 10px -4px",
        "--origam-card---box-shadow": "0 1px 3px rgba(124, 58, 237, 0.06), 0 8px 24px -16px rgba(124, 58, 237, 0.20)",
        "--origam-code---border-color": "rgba(168, 85, 247, 0.28)",
        "--origam-code---border-width": "1px",
        "--origam-color__feedback--success---bg": "#16a34a",
        "--origam-color__feedback--success---bgSubtle": "rgba(22, 163, 74, 0.1)",
        "--origam-color__feedback--success---fg": "#000000",
        "--origam-color__feedback--success---fgSubtle": "#15803d",
        "--origam-color__feedback--success---border": "#16a34a",
        "--origam-color__feedback--warning---bg": "#d97706",
        "--origam-color__feedback--warning---bgSubtle": "rgba(217, 119, 6, 0.1)",
        "--origam-color__feedback--warning---fg": "#000000",
        "--origam-color__feedback--warning---fgSubtle": "#b45309",
        "--origam-color__feedback--warning---border": "#d97706",
        "--origam-color__feedback--danger---bg": "#dc2626",
        "--origam-color__feedback--danger---bgSubtle": "rgba(220, 38, 38, 0.1)",
        "--origam-color__feedback--danger---fg": "#ffffff",
        "--origam-color__feedback--danger---fgSubtle": "#b91c1c",
        "--origam-color__feedback--danger---border": "#dc2626",
        "--origam-color__feedback--info---bg": "#2563eb",
        "--origam-color__feedback--info---bgSubtle": "rgba(37, 99, 235, 0.1)",
        "--origam-color__feedback--info---fg": "#ffffff",
        "--origam-color__feedback--info---fgSubtle": "#1d4ed8",
        "--origam-color__feedback--info---border": "#2563eb"
    }

export const THEME_BUILDER_PRESET_GEEK_DARK_VARS: Record<string, string> = {
        "--origam-font-family---heading": "'JetBrains Mono', 'Fira Code', ui-monospace, monospace",
        "--origam-title---font-family": "'JetBrains Mono', 'Fira Code', ui-monospace, monospace",
        "--origam-appbar---bg": "rgba(10, 6, 18, 0.85)",
        "--origam-menu---background": "var(--origam-color__surface---default)",
        "--origam-menu---color": "var(--origam-color__text---primary)",
        "--origam-menu---border-radius": "8px",
        "--origam-menu---box-shadow": "0 4px 24px -4px rgba(0, 0, 0, 0.70), 0 1px 4px -1px rgba(0, 0, 0, 0.40), 0 0 0 1px var(--origam-color__border---default), 0 0 20px -8px rgba(0, 240, 255, 0.20)",
        "--origam-menu__content---padding": "4px",
        "--origam-list---background": "transparent",
        "--origam-list---padding-block-start": "0",
        "--origam-list---padding-block-end": "0",
        "--origam-list-item---padding-inline-start": "12px",
        "--origam-list-item---padding-inline-end": "12px",
        "--origam-gradient---hero-glow": "radial-gradient(ellipse 65% 45% at 50% 0%, rgba(0, 240, 255, 0.18), transparent 65%)",
        "--origam-gradient---cta-glow": "radial-gradient(ellipse 80% 60% at 80% 30%, rgba(199, 125, 255, 0.15), transparent 70%)",
        "--origam-gradient---cta-glow-top": "radial-gradient(ellipse 70% 55% at 50% 0%, rgba(0, 240, 255, 0.14), transparent 65%)",
        "--origam-gradient---hero-title": "linear-gradient(var(--origam-color__text---ink), var(--origam-color__text---ink))",
        "--origam-gradient---hero-grid": "linear-gradient(var(--origam-color__border---default) 1px, transparent 1px), linear-gradient(90deg, var(--origam-color__border---default) 1px, transparent 1px)",
        "--origam-gradient---kpi-value": "linear-gradient(110deg, #00f0ff 0%, #c77dff 50%, #ff3cac 100%)",
        "--origam-gradient---btn-primary": "linear-gradient(110deg, #00f0ff, #c77dff 60%, #ff3cac)",
        "--origam-gradient---btn-secondary": "none",
        "--origam-btn---border-color": "rgba(0, 240, 255, 0.40)",
        "--origam-btn---border-width-outlined": "1px",
        "--origam-btn---border-width-ghost": "1px",
        "--origam-btn---box-shadow-elevated": "0 8px 24px -8px rgba(0, 240, 255, 0.50), 0 0 32px -8px rgba(199, 125, 255, 0.35)",
        "--origam-btn---box-shadow-ghost": "rgba(0, 240, 255, 0.25) 0px 0px 12px -4px",
        "--origam-card---box-shadow": "inset 0 1px 0 rgba(199, 125, 255, 0.08), 0 8px 28px -12px rgba(0, 0, 0, 0.80), 0 0 0 1px rgba(0, 240, 255, 0.04)",
        "--origam-code---border-color": "rgba(124, 77, 255, 0.28)",
        "--origam-code---border-width": "1px",
        "--origam-color__feedback--success---bg": "#4ade80",
        "--origam-color__feedback--success---bgSubtle": "rgba(74, 222, 128, 0.1)",
        "--origam-color__feedback--success---fg": "#050a05",
        "--origam-color__feedback--success---fgSubtle": "#6ee7b7",
        "--origam-color__feedback--success---border": "#4ade80",
        "--origam-color__feedback--warning---bg": "#fbbf24",
        "--origam-color__feedback--warning---bgSubtle": "rgba(251, 191, 36, 0.1)",
        "--origam-color__feedback--warning---fg": "#050a05",
        "--origam-color__feedback--warning---fgSubtle": "#fbbf24",
        "--origam-color__feedback--warning---border": "#fbbf24",
        "--origam-color__feedback--danger---bg": "#fca5a5",
        "--origam-color__feedback--danger---bgSubtle": "rgba(252, 165, 165, 0.1)",
        "--origam-color__feedback--danger---fg": "#050a05",
        "--origam-color__feedback--danger---fgSubtle": "#fca5a5",
        "--origam-color__feedback--danger---border": "#fca5a5",
        "--origam-color__feedback--info---bg": "#93c5fd",
        "--origam-color__feedback--info---bgSubtle": "rgba(147, 197, 253, 0.1)",
        "--origam-color__feedback--info---fg": "#050a05",
        "--origam-color__feedback--info---fgSubtle": "#93c5fd",
        "--origam-color__feedback--info---border": "#93c5fd"
    }

export const THEME_BUILDER_PRESET_GLASS_LIGHT_VARS: Record<string, string> = {
        "--origam-glass---page-bg-color": "#e9ecff",
        "--origam-page---background-image": "radial-gradient(40% 50% at 12% 14%, rgba(167, 139, 250, 0.65), transparent 70%), radial-gradient(38% 46% at 90% 6%, rgba(94, 234, 212, 0.60), transparent 70%), radial-gradient(44% 52% at 78% 82%, rgba(244, 114, 182, 0.52), transparent 72%), radial-gradient(40% 48% at 18% 94%, rgba(125, 211, 252, 0.56), transparent 70%)",
        "--origam-card---backdrop-filter": "blur(3px) saturate(1.8) brightness(1.08)",
        "--origam-sheet---backdrop-filter": "blur(3px) saturate(1.8) brightness(1.08)",
        "--origam-appbar---backdrop-filter": "saturate(2) brightness(1.1) blur(26px)",
        "--origam-menu---backdrop-filter": "blur(20px) saturate(1.8) brightness(1.05)",
        "--origam-appbar---bg": "rgba(255, 255, 255, 0.30)",
        "--origam-menu---background": "rgba(255, 255, 255, 0.80)",
        "--origam-menu---color": "var(--origam-color__text---primary)",
        "--origam-menu---border-radius": "16px",
        "--origam-menu---box-shadow": "0 8px 32px -8px rgba(124, 58, 237, 0.18), 0 1px 4px -1px rgba(124, 58, 237, 0.10), 0 0 0 1px var(--origam-color__border---default), inset 0 1px 0 rgba(255, 255, 255, 0.60)",
        "--origam-menu__content---padding": "6px",
        "--origam-list---background": "transparent",
        "--origam-list---padding-block-start": "0",
        "--origam-list---padding-block-end": "0",
        "--origam-list-item---padding-inline-start": "12px",
        "--origam-list-item---padding-inline-end": "12px",
        "--origam-gradient---hero-glow": "radial-gradient(ellipse 70% 60% at 30% 20%, rgba(167, 139, 250, 0.30), transparent 60%)",
        "--origam-gradient---cta-glow": "radial-gradient(ellipse 60% 60% at 80% 70%, rgba(45, 212, 191, 0.18), transparent 60%)",
        "--origam-gradient---cta-glow-top": "radial-gradient(ellipse 70% 55% at 50% 0%, rgba(124, 58, 237, 0.14), transparent 65%)",
        "--origam-gradient---hero-title": "linear-gradient(#1a1538, #1a1538)",
        "--origam-gradient---hero-grid": "linear-gradient(rgba(124, 58, 237, 0.08) 1px, transparent 1px), linear-gradient(90deg, rgba(124, 58, 237, 0.08) 1px, transparent 1px)",
        "--origam-gradient---kpi-value": "linear-gradient(135deg, #7c3aed, #a78bfa)",
        "--origam-gradient---btn-primary": "none",
        "--origam-gradient---btn-secondary": "none",
        "--origam-btn---border-color": "rgba(124, 58, 237, 0.35)",
        "--origam-btn---border-width-outlined": "1px",
        "--origam-btn---border-width-ghost": "1px",
        "--origam-btn---box-shadow-elevated": "inset 0 1px 1px rgba(255, 255, 255, 0.90), inset 1px 0 1px rgba(255, 255, 255, 0.50), inset 0 -1px 1px rgba(124, 58, 237, 0.12), 0 10px 30px -12px rgba(60, 30, 120, 0.40)",
        "--origam-btn---box-shadow-ghost": "none",
        "--origam-btn---backdrop-filter-ghost": "blur(12px) saturate(1.8) brightness(1.05)",
        "--origam-card---box-shadow": "var(--origam-shadow---card-elevated)",
        "--origam-code---border-radius": "16px",
        "--origam-color__feedback--success---bg": "#16a34a",
        "--origam-color__feedback--success---bgSubtle": "rgba(22, 163, 74, 0.1)",
        "--origam-color__feedback--success---fg": "#000000",
        "--origam-color__feedback--success---fgSubtle": "#15803d",
        "--origam-color__feedback--success---border": "#16a34a",
        "--origam-color__feedback--warning---bg": "#d97706",
        "--origam-color__feedback--warning---bgSubtle": "rgba(217, 119, 6, 0.1)",
        "--origam-color__feedback--warning---fg": "#000000",
        "--origam-color__feedback--warning---fgSubtle": "#b45309",
        "--origam-color__feedback--warning---border": "#d97706",
        "--origam-color__feedback--danger---bg": "#dc2626",
        "--origam-color__feedback--danger---bgSubtle": "rgba(220, 38, 38, 0.1)",
        "--origam-color__feedback--danger---fg": "#ffffff",
        "--origam-color__feedback--danger---fgSubtle": "#b91c1c",
        "--origam-color__feedback--danger---border": "#dc2626",
        "--origam-color__feedback--info---bg": "#2563eb",
        "--origam-color__feedback--info---bgSubtle": "rgba(37, 99, 235, 0.1)",
        "--origam-color__feedback--info---fg": "#ffffff",
        "--origam-color__feedback--info---fgSubtle": "#1d4ed8",
        "--origam-color__feedback--info---border": "#2563eb",
        "--origam-toolbar---background": "var(--origam-appbar---bg)",
        "--origam-code---background-color": "rgba(255, 255, 255, 0.60)",
        "--origam-code__compact---background-color": "rgba(255, 255, 255, 0.60)",
        "--origam-code---border-color": "rgba(124, 58, 237, 0.22)"
    }

export const THEME_BUILDER_PRESET_GLASS_DARK_VARS: Record<string, string> = {
        "--origam-glass---page-bg-color": "#07060f",
        "--origam-page---background-image": "radial-gradient(40% 50% at 12% 14%, rgba(167, 139, 250, 0.75), transparent 70%), radial-gradient(38% 46% at 90% 6%, rgba(45, 212, 191, 0.65), transparent 70%), radial-gradient(44% 52% at 78% 82%, rgba(236, 72, 153, 0.62), transparent 72%), radial-gradient(40% 48% at 18% 94%, rgba(56, 189, 248, 0.58), transparent 70%), radial-gradient(50% 60% at 50% 50%, rgba(124, 58, 237, 0.30), transparent 80%)",
        "--origam-card---backdrop-filter": "blur(3px) saturate(1.8) brightness(1.08)",
        "--origam-sheet---backdrop-filter": "blur(3px) saturate(1.8) brightness(1.08)",
        "--origam-appbar---backdrop-filter": "saturate(2) brightness(1.1) blur(26px)",
        "--origam-menu---backdrop-filter": "blur(20px) saturate(1.6) brightness(1.02)",
        "--origam-appbar---bg": "rgba(255, 255, 255, 0.06)",
        "--origam-menu---background": "rgba(20, 18, 40, 0.85)",
        "--origam-menu---color": "var(--origam-color__text---primary)",
        "--origam-menu---border-radius": "22px",
        "--origam-menu---box-shadow": "0 8px 32px -8px rgba(0, 0, 0, 0.60), 0 0 0 1px rgba(255, 255, 255, 0.12), inset 0 1px 0 rgba(255, 255, 255, 0.10)",
        "--origam-menu__content---padding": "6px",
        "--origam-list---background": "transparent",
        "--origam-list---padding-block-start": "0",
        "--origam-list---padding-block-end": "0",
        "--origam-list-item---padding-inline-start": "12px",
        "--origam-list-item---padding-inline-end": "12px",
        "--origam-gradient---hero-glow": "radial-gradient(ellipse 70% 60% at 30% 20%, rgba(167, 139, 250, 0.30), transparent 60%)",
        "--origam-gradient---cta-glow": "radial-gradient(ellipse 60% 60% at 80% 70%, rgba(45, 212, 191, 0.18), transparent 60%)",
        "--origam-gradient---cta-glow-top": "radial-gradient(ellipse 70% 55% at 50% 0%, rgba(167, 139, 250, 0.18), transparent 65%)",
        "--origam-gradient---hero-title": "linear-gradient(180deg, #ffffff 0%, #ddd6fe 50%, #a78bfa 100%)",
        "--origam-gradient---hero-grid": "linear-gradient(rgba(167, 139, 250, 0.08) 1px, transparent 1px), linear-gradient(90deg, rgba(167, 139, 250, 0.08) 1px, transparent 1px)",
        "--origam-gradient---kpi-value": "linear-gradient(135deg, #a78bfa, #ddd6fe)",
        "--origam-gradient---btn-primary": "none",
        "--origam-gradient---btn-secondary": "none",
        "--origam-btn---border-color": "rgba(255, 255, 255, 0.20)",
        "--origam-btn---border-width-outlined": "1px",
        "--origam-btn---border-width-ghost": "1px",
        "--origam-btn---box-shadow-elevated": "inset 0 1px 1px rgba(255, 255, 255, 0.60), inset 1.5px 0 1px rgba(255, 255, 255, 0.28), inset 0 -1px 1px rgba(0, 0, 0, 0.20), 0 8px 24px -6px rgba(167, 139, 250, 0.60)",
        "--origam-btn---box-shadow-ghost": "none",
        "--origam-btn---backdrop-filter-ghost": "blur(12px) saturate(1.6) brightness(1.02)",
        "--origam-card---box-shadow": "var(--origam-shadow---card-elevated)",
        "--origam-code---border-radius": "16px",
        "--origam-color__feedback--success---bg": "#6ee7b7",
        "--origam-color__feedback--success---bgSubtle": "rgba(110, 231, 183, 0.14)",
        "--origam-color__feedback--success---fg": "#0f0e1a",
        "--origam-color__feedback--success---fgSubtle": "#6ee7b7",
        "--origam-color__feedback--success---border": "#6ee7b7",
        "--origam-color__feedback--warning---bg": "#fcd34d",
        "--origam-color__feedback--warning---bgSubtle": "rgba(252, 211, 77, 0.14)",
        "--origam-color__feedback--warning---fg": "#0f0e1a",
        "--origam-color__feedback--warning---fgSubtle": "#fcd34d",
        "--origam-color__feedback--warning---border": "#fcd34d",
        "--origam-color__feedback--danger---bg": "#fca5a5",
        "--origam-color__feedback--danger---bgSubtle": "rgba(252, 165, 165, 0.14)",
        "--origam-color__feedback--danger---fg": "#0f0e1a",
        "--origam-color__feedback--danger---fgSubtle": "#fca5a5",
        "--origam-color__feedback--danger---border": "#fca5a5",
        "--origam-color__feedback--info---bg": "#93c5fd",
        "--origam-color__feedback--info---bgSubtle": "rgba(147, 197, 253, 0.14)",
        "--origam-color__feedback--info---fg": "#0f0e1a",
        "--origam-color__feedback--info---fgSubtle": "#93c5fd",
        "--origam-color__feedback--info---border": "#93c5fd",
        "--origam-code---background-color": "rgba(255, 255, 255, 0.08)",
        "--origam-code__compact---background-color": "rgba(255, 255, 255, 0.08)",
        "--origam-code---border-color": "rgba(167, 139, 250, 0.28)"
    }

export const THEME_BUILDER_PRESET_EDITORIAL_LIGHT_VARS: Record<string, string> = {
        "--origam-font-family---heading": "'Fraunces', 'Playfair Display', Georgia, serif",
        "--origam-title---font-family": "'Fraunces', 'Playfair Display', Georgia, serif",
        "--origam-font-weight---extrabold": "400",
        "--origam-letter-spacing---hero": "-0.04em",
        "--origam-line-height---hero": "0.9",
        "--origam-letter-spacing---tight": "-0.03em",
        "--origam-appbar---bg": "color-mix(in srgb, #fbf7ee 72%, transparent)",
        "--origam-appbar---backdrop-filter": "saturate(140%) blur(16px)",
        "--origam-menu---background": "var(--origam-color__surface---default)",
        "--origam-menu---color": "var(--origam-color__text---primary)",
        "--origam-menu---border-radius": "0px",
        "--origam-menu---box-shadow": "0 4px 16px -4px rgba(0, 0, 0, 0.12), 0 0 0 1px var(--origam-color__border---default)",
        "--origam-menu__content---padding": "4px",
        "--origam-list---background": "transparent",
        "--origam-list---padding-block-start": "0",
        "--origam-list---padding-block-end": "0",
        "--origam-list-item---padding-inline-start": "12px",
        "--origam-list-item---padding-inline-end": "12px",
        "--m-shadow-card": "none (print aesthetic, no depth) --m-shadow-btn: none *//* ── Gradients — marketing display ──────────────────────────────────── Hero glow: --m-bg-decor-1 = radial lavender ellipse at 50% 0% (section-scoped) Measured: radial-gradient(60% 50% at 50% 0%, rgba(167,139,250,.16), transparent 60%) CTA: no glow (--m-bg-decor-2: none) — editorial is minimal Hero title: none (solid ink text, no gradient — maquette bg-clip=border-box, no clip) Hero grid: faint ink grid lines 1px at rgba(26,23,20,0.06) KPI: solid primary (Fraunces gradient stops identical = one colour) Note: kpi value uses color directly (Fraunces, color=primary), not gradient clip. We use a degenerate solid gradient to preserve the -webkit-text-fill trick. */ --origam-gradient---hero-glow: radial-gradient(ellipse 60% 50% at 50% 0%, rgba(167, 139, 250, 0.16), transparent 60%)",
        "--origam-gradient---cta-glow": "none",
        "--origam-gradient---cta-glow-top": "none",
        "--origam-gradient---hero-title": "linear-gradient(#1a1714, #1a1714)",
        "--origam-gradient---hero-grid": "linear-gradient(rgba(26, 23, 20, 0.06) 1px, transparent 1px), linear-gradient(90deg, rgba(26, 23, 20, 0.06) 1px, transparent 1px)",
        "--origam-gradient---kpi-value": "linear-gradient(#5b21b6, #5b21b6)",
        "--origam-gradient---btn-primary": "linear-gradient(#5b21b6, #5b21b6)",
        "--origam-gradient---btn-secondary": "none",
        "--origam-btn---border-color": "rgba(26, 23, 20, 0.40)",
        "--origam-btn---border-width-outlined": "1px",
        "--origam-btn---border-width-ghost": "1px",
        "--origam-btn---box-shadow-elevated": "none",
        "--origam-btn---box-shadow-ghost": "none",
        "--origam-btn---border-radius": "0px",
        "--origam-card---background": "var(--origam-color__surface---raised)",
        "--origam-card---border-color": "var(--origam-color__border---default)",
        "--origam-card---border-style": "solid",
        "--origam-card---border-top-width": "1px",
        "--origam-card---border-right-width": "1px",
        "--origam-card---border-bottom-width": "1px",
        "--origam-card---border-left-width": "1px",
        "--origam-card---box-shadow": "none",
        "--origam-chip---border-radius": "0px",
        "--origam-chip---background-color": "var(--origam-color__surface---raised)",
        "--origam-chip---border-color": "var(--origam-color__border---default)",
        "--origam-chip---border-width": "1px",
        "--origam-chip---border-style": "solid",
        "--origam-code---border-radius": "0px",
        "--origam-code---border-color": "var(--origam-color__border---default)",
        "--origam-code---border-width": "1px",
        "--origam-code---background-color": "var(--origam-color__surface---sunken, #f3ecdd)",
        "--origam-field---border-radius": "0px",
        "--origam-field---border-color": "rgba(26, 23, 20, 0.40)",
        "--origam-field---border-opacity": "1",
        "--origam-alert---border-radius": "0px",
        "--origam-color__feedback--success---bg": "#15803d",
        "--origam-color__feedback--success---bgSubtle": "rgba(21, 128, 61, 0.08)",
        "--origam-color__feedback--success---fg": "#ffffff",
        "--origam-color__feedback--success---fgSubtle": "#166534",
        "--origam-color__feedback--success---border": "#15803d",
        "--origam-color__feedback--warning---bg": "#b45309",
        "--origam-color__feedback--warning---bgSubtle": "rgba(180, 83, 9, 0.08)",
        "--origam-color__feedback--warning---fg": "#ffffff",
        "--origam-color__feedback--warning---fgSubtle": "#92400e",
        "--origam-color__feedback--warning---border": "#b45309",
        "--origam-color__feedback--danger---bg": "#b91c1c",
        "--origam-color__feedback--danger---bgSubtle": "rgba(185, 28, 28, 0.08)",
        "--origam-color__feedback--danger---fg": "#ffffff",
        "--origam-color__feedback--danger---fgSubtle": "#991b1b",
        "--origam-color__feedback--danger---border": "#b91c1c",
        "--origam-color__feedback--info---bg": "#1d4ed8",
        "--origam-color__feedback--info---bgSubtle": "rgba(29, 78, 216, 0.08)",
        "--origam-color__feedback--info---fg": "#ffffff",
        "--origam-color__feedback--info---fgSubtle": "#1e40af",
        "--origam-color__feedback--info---border": "#1d4ed8",
        "--origam-text-mask---font-family": "'Fraunces', 'Playfair Display', Georgia, serif"
    }

export const THEME_BUILDER_PRESET_EDITORIAL_DARK_VARS: Record<string, string> = {
        "--origam-font-family---heading": "'Fraunces', 'Playfair Display', Georgia, serif",
        "--origam-title---font-family": "'Fraunces', 'Playfair Display', Georgia, serif",
        "--origam-font-weight---extrabold": "400",
        "--origam-letter-spacing---hero": "-0.04em",
        "--origam-line-height---hero": "0.9",
        "--origam-letter-spacing---tight": "-0.03em",
        "--m-accent-border": "#A78BFA) Measured: m-pill border=rgb(167,139,250), m-stat__num color=rgb(167,139,250) On-primary text = #0A0A0A (dark ink on light lavender) *//* ── Actions / secondary ─────────────────────────────────────────────── Ghost in dark: transparent bg, white border *//* ── Actions / ghost ─────────────────────────────────────────────────── Ghost: same lavender accent *//* ── Borders ─────────────────────────────────────────────────────────── --m-border = rgba(255,255,255,.10) → 1px white translucent (default) --m-border-soft = rgba(255,255,255,.05) → subtle --m-border-strong = rgba(255,255,255,.20) → strong --m-accent-border = #A78BFA → focus / accent ring Measured: nav border-bottom=rgba(255,255,255,0.1), card border=rgba(255,255,255,0.1) *//* Editorial dark: ghost border matches default (nav border = rgba(255,255,255,.10)) *//* ── Feedback ────────────────────────────────────────────────────────── Dark feedback: bright accessible colours on dark bg *//* ── Appbar ──────────────────────────────────────────────────────────── Measured: nav bg=color(srgb 0.0392 0.0392 0.0392 / 0.72) ≈ #0A0A0A @ 72% border-block-end: 1px solid rgba(255,255,255,0.10) backdrop-filter: saturate(1.4) blur(16px) */ --origam-appbar---bg: color-mix(in srgb, #0a0a0a 72%, transparent)",
        "--origam-appbar---backdrop-filter": "saturate(140%) blur(16px)",
        "--origam-menu---background": "var(--origam-color__surface---default)",
        "--origam-menu---color": "var(--origam-color__text---primary)",
        "--origam-menu---border-radius": "0px",
        "--origam-menu---box-shadow": "0 4px 24px -4px rgba(0, 0, 0, 0.50), 0 0 0 1px var(--origam-color__border---default)",
        "--origam-menu__content---padding": "4px",
        "--origam-list---background": "transparent",
        "--origam-list---padding-block-start": "0",
        "--origam-list---padding-block-end": "0",
        "--origam-list-item---padding-inline-start": "12px",
        "--origam-list-item---padding-inline-end": "12px",
        "--origam-gradient---hero-glow": "radial-gradient(ellipse 60% 50% at 50% 0%, rgba(167, 139, 250, 0.16), transparent 60%)",
        "--origam-gradient---cta-glow": "none",
        "--origam-gradient---cta-glow-top": "none",
        "--origam-gradient---hero-title": "linear-gradient(#ffffff, #ffffff)",
        "--origam-gradient---hero-grid": "linear-gradient(rgba(255, 255, 255, 0.06) 1px, transparent 1px), linear-gradient(90deg, rgba(255, 255, 255, 0.06) 1px, transparent 1px)",
        "--origam-gradient---kpi-value": "linear-gradient(#a78bfa, #a78bfa)",
        "--origam-gradient---btn-primary": "linear-gradient(#a78bfa, #a78bfa)",
        "--origam-gradient---btn-secondary": "none",
        "--origam-btn---border-color": "rgba(255, 255, 255, 0.20)",
        "--origam-btn---border-width-outlined": "1px",
        "--origam-btn---border-width-ghost": "1px",
        "--origam-btn---box-shadow-elevated": "none",
        "--origam-btn---box-shadow-ghost": "none",
        "--origam-btn---border-radius": "0px",
        "--origam-card---background": "var(--origam-color__surface---raised)",
        "--origam-card---border-color": "var(--origam-color__border---default)",
        "--origam-card---border-style": "solid",
        "--origam-card---border-top-width": "1px",
        "--origam-card---border-right-width": "1px",
        "--origam-card---border-bottom-width": "1px",
        "--origam-card---border-left-width": "1px",
        "--origam-card---box-shadow": "none",
        "--origam-chip---border-radius": "0px",
        "--origam-chip---background-color": "var(--origam-color__surface---raised)",
        "--origam-chip---border-color": "var(--origam-color__border---default)",
        "--origam-chip---border-width": "1px",
        "--origam-chip---border-style": "solid",
        "--origam-code---border-radius": "0px",
        "--origam-code---border-color": "var(--origam-color__border---default)",
        "--origam-code---border-width": "1px",
        "--origam-code---background-color": "var(--origam-color__surface---sunken, #131313)",
        "--origam-field---border-radius": "0px",
        "--origam-field---border-color": "rgba(255, 255, 255, 0.30)",
        "--origam-field---border-opacity": "1",
        "--origam-alert---border-radius": "0px",
        "--origam-color__feedback--success---bg": "#6ee7b7",
        "--origam-color__feedback--success---bgSubtle": "rgba(110, 231, 183, 0.1)",
        "--origam-color__feedback--success---fg": "#0a0a0a",
        "--origam-color__feedback--success---fgSubtle": "#6ee7b7",
        "--origam-color__feedback--success---border": "#6ee7b7",
        "--origam-color__feedback--warning---bg": "#fcd34d",
        "--origam-color__feedback--warning---bgSubtle": "rgba(252, 211, 77, 0.1)",
        "--origam-color__feedback--warning---fg": "#0a0a0a",
        "--origam-color__feedback--warning---fgSubtle": "#fcd34d",
        "--origam-color__feedback--warning---border": "#fcd34d",
        "--origam-color__feedback--danger---bg": "#fca5a5",
        "--origam-color__feedback--danger---bgSubtle": "rgba(252, 165, 165, 0.1)",
        "--origam-color__feedback--danger---fg": "#0a0a0a",
        "--origam-color__feedback--danger---fgSubtle": "#fca5a5",
        "--origam-color__feedback--danger---border": "#fca5a5",
        "--origam-color__feedback--info---bg": "#93c5fd",
        "--origam-color__feedback--info---bgSubtle": "rgba(147, 197, 253, 0.1)",
        "--origam-color__feedback--info---fg": "#0a0a0a",
        "--origam-color__feedback--info---fgSubtle": "#93c5fd",
        "--origam-color__feedback--info---border": "#93c5fd",
        "--origam-text-mask---font-family": "'Fraunces', 'Playfair Display', Georgia, serif"
    }

export const THEME_BUILDER_PRESET_MATERIAL_LIGHT_VARS: Record<string, string> = {
        "--origam-font-family---heading": "'Roboto', 'Inter', -apple-system, sans-serif",
        "--origam-title---font-family": "'Roboto', 'Inter', -apple-system, sans-serif",
        "--origam-font-weight---extrabold": "600",
        "--origam-letter-spacing---hero": "-0.025em",
        "--origam-appbar---bg": "color-mix(in srgb, #fef7ff 72%, transparent)",
        "--origam-appbar---backdrop-filter": "saturate(140%) blur(16px)",
        "--origam-menu---background": "var(--origam-color__surface---raised)",
        "--origam-menu---color": "var(--origam-color__text---primary)",
        "--origam-menu---border-radius": "16px",
        "--origam-menu---box-shadow": "0 1px 2px rgba(0, 0, 0, 0.3), 0 2px 6px 2px rgba(208, 188, 255, 0.15), 0 0 0 1px var(--origam-color__border---default)",
        "--origam-menu__content---padding": "6px",
        "--origam-list---background": "transparent",
        "--origam-list---padding-block-start": "0",
        "--origam-list---padding-block-end": "0",
        "--origam-list-item---padding-inline-start": "12px",
        "--origam-list-item---padding-inline-end": "12px",
        "--origam-gradient---hero-glow": "radial-gradient(ellipse 70% 50% at 50% 0%, rgba(208, 188, 255, 0.16), transparent 60%)",
        "--origam-gradient---cta-glow": "none",
        "--origam-gradient---cta-glow-top": "radial-gradient(ellipse 70% 55% at 50% 0%, rgba(208, 188, 255, 0.14), transparent 65%)",
        "--origam-gradient---hero-title": "linear-gradient(#1c1b1f, #1c1b1f)",
        "--origam-gradient---hero-grid": "linear-gradient(rgba(28, 27, 31, 0.06) 1px, transparent 1px), linear-gradient(90deg, rgba(28, 27, 31, 0.06) 1px, transparent 1px)",
        "--origam-gradient---kpi-value": "linear-gradient(135deg, #6750a4, #d0bcff)",
        "--origam-gradient---btn-primary": "none",
        "--origam-gradient---btn-secondary": "linear-gradient(#eaddff, #eaddff)",
        "--origam-card---background": "var(--origam-color__surface---raised)",
        "--origam-card---border-radius": "28px",
        "--origam-card---border-width": "1px",
        "--origam-card---border-color": "var(--origam-color__border---default)",
        "--origam-chip---border-radius": "999px",
        "--origam-chip---background": "var(--origam-color__surface---raised)",
        "--origam-chip---background-color": "var(--origam-color__surface---raised)",
        "--origam-chip---border-color": "var(--origam-color__border---default)",
        "--origam-btn---border-radius": "999px",
        "--origam-btn---border-radius-rounded": "999px",
        "--origam-btn---border-color": "var(--origam-color__border---default)",
        "--origam-btn---border-width-outlined": "1px",
        "--origam-btn---border-width-ghost": "1px",
        "--origam-btn---box-shadow-elevated": "0 1px 2px rgba(0, 0, 0, 0.3), 0 1px 3px 1px rgba(0, 0, 0, 0.15)",
        "--origam-btn---box-shadow-ghost": "none",
        "--origam-code---border-radius": "12px",
        "--origam-code---border-width": "0",
        "--origam-alert---border-radius": "var(--origam-radius---lg, 12px)",
        "--origam-alert---box-shadow-elevated": "0 1px 2px rgba(0, 0, 0, 0.3), 0 1px 3px 1px rgba(0, 0, 0, 0.15)",
        "--origam-table---border-radius": "28px",
        "--origam-color__feedback--success---bg": "#388e3c",
        "--origam-color__feedback--success---bgSubtle": "#e8f5e9",
        "--origam-color__feedback--success---fg": "#000000",
        "--origam-color__feedback--success---fgSubtle": "#1b5e20",
        "--origam-color__feedback--success---border": "#388e3c",
        "--origam-color__feedback--warning---bg": "#f57c00",
        "--origam-color__feedback--warning---bgSubtle": "#fff3e0",
        "--origam-color__feedback--warning---fg": "#000000",
        "--origam-color__feedback--warning---fgSubtle": "#9a3412",
        "--origam-color__feedback--warning---border": "#f57c00",
        "--origam-color__feedback--danger---bg": "#b3261e",
        "--origam-color__feedback--danger---bgSubtle": "#f9dedc",
        "--origam-color__feedback--danger---fg": "#ffffff",
        "--origam-color__feedback--danger---fgSubtle": "#601410",
        "--origam-color__feedback--danger---border": "#b3261e",
        "--origam-color__feedback--info---bg": "#0288d1",
        "--origam-color__feedback--info---bgSubtle": "#e1f5fe",
        "--origam-color__feedback--info---fg": "#000000",
        "--origam-color__feedback--info---fgSubtle": "#01579b",
        "--origam-color__feedback--info---border": "#0288d1"
    }

export const THEME_BUILDER_PRESET_MATERIAL_DARK_VARS: Record<string, string> = {
        "--origam-font-family---heading": "'Roboto', 'Inter', -apple-system, sans-serif",
        "--origam-title---font-family": "'Roboto', 'Inter', -apple-system, sans-serif",
        "--origam-font-weight---extrabold": "600",
        "--origam-letter-spacing---hero": "-0.025em",
        "--origam-appbar---bg": "color-mix(in srgb, #1c1b1f 72%, transparent)",
        "--origam-appbar---backdrop-filter": "saturate(140%) blur(16px)",
        "--origam-menu---background": "var(--origam-color__surface---raised)",
        "--origam-menu---color": "var(--origam-color__text---primary)",
        "--origam-menu---border-radius": "16px",
        "--origam-menu---box-shadow": "0 4px 24px -4px rgba(0, 0, 0, 0.50), 0 1px 2px rgba(0, 0, 0, 0.30), 0 0 0 1px var(--origam-color__border---default)",
        "--origam-menu__content---padding": "6px",
        "--origam-list---background": "transparent",
        "--origam-list---padding-block-start": "0",
        "--origam-list---padding-block-end": "0",
        "--origam-list-item---padding-inline-start": "12px",
        "--origam-list-item---padding-inline-end": "12px",
        "--origam-gradient---hero-glow": "radial-gradient(ellipse 70% 50% at 50% 0%, rgba(208, 188, 255, 0.18), transparent 60%)",
        "--origam-gradient---cta-glow": "none",
        "--origam-gradient---cta-glow-top": "radial-gradient(ellipse 70% 55% at 50% 0%, rgba(208, 188, 255, 0.16), transparent 65%)",
        "--origam-gradient---hero-title": "linear-gradient(180deg, #ffffff 0%, #eaddff 60%, #d0bcff 100%)",
        "--origam-gradient---hero-grid": "linear-gradient(rgba(202, 196, 208, 0.06) 1px, transparent 1px), linear-gradient(90deg, rgba(202, 196, 208, 0.06) 1px, transparent 1px)",
        "--origam-gradient---kpi-value": "linear-gradient(135deg, #d0bcff, #eaddff)",
        "--origam-gradient---btn-primary": "none",
        "--origam-gradient---btn-secondary": "linear-gradient(#4a4458, #4a4458)",
        "--origam-card---background": "var(--origam-color__surface---raised)",
        "--origam-card---border-radius": "28px",
        "--origam-card---border-width": "1px",
        "--origam-card---border-color": "var(--origam-color__border---default)",
        "--origam-chip---border-radius": "999px",
        "--origam-chip---background": "var(--origam-color__surface---raised)",
        "--origam-chip---background-color": "var(--origam-color__surface---raised)",
        "--origam-chip---border-color": "var(--origam-color__border---default)",
        "--origam-btn---border-radius": "999px",
        "--origam-btn---border-radius-rounded": "999px",
        "--origam-btn---border-color": "var(--origam-color__border---default)",
        "--origam-btn---border-width-outlined": "1px",
        "--origam-btn---border-width-ghost": "1px",
        "--origam-btn---box-shadow-elevated": "0 1px 2px rgba(0, 0, 0, 0.3), 0 1px 3px 1px rgba(0, 0, 0, 0.15)",
        "--origam-btn---box-shadow-ghost": "none",
        "--origam-code---border-radius": "12px",
        "--origam-code---border-width": "0",
        "--origam-alert---border-radius": "var(--origam-radius---lg, 12px)",
        "--origam-alert---box-shadow-elevated": "0 1px 2px rgba(0, 0, 0, 0.3), 0 1px 3px 1px rgba(0, 0, 0, 0.15)",
        "--origam-table---border-radius": "28px",
        "--origam-color__feedback--success---bg": "#9ccc65",
        "--origam-color__feedback--success---bgSubtle": "#33401c",
        "--origam-color__feedback--success---fg": "#1c1b1f",
        "--origam-color__feedback--success---fgSubtle": "#c5e1a5",
        "--origam-color__feedback--success---border": "#9ccc65",
        "--origam-color__feedback--warning---bg": "#ffd54f",
        "--origam-color__feedback--warning---bgSubtle": "#3d2f00",
        "--origam-color__feedback--warning---fg": "#1c1b1f",
        "--origam-color__feedback--warning---fgSubtle": "#ffe082",
        "--origam-color__feedback--warning---border": "#ffd54f",
        "--origam-color__feedback--danger---bg": "#f2b8b5",
        "--origam-color__feedback--danger---bgSubtle": "#601410",
        "--origam-color__feedback--danger---fg": "#601410",
        "--origam-color__feedback--danger---fgSubtle": "#f9dedc",
        "--origam-color__feedback--danger---border": "#f2b8b5",
        "--origam-color__feedback--info---bg": "#80cefe",
        "--origam-color__feedback--info---bgSubtle": "#003c5c",
        "--origam-color__feedback--info---fg": "#1c1b1f",
        "--origam-color__feedback--info---fgSubtle": "#b3e5fc",
        "--origam-color__feedback--info---border": "#80cefe"
    }

export const THEME_BUILDER_PRESET_ECOM_LIGHT_VARS: Record<string, string> = {
        "--origam-font-family---heading": "'Inter', -apple-system, BlinkMacSystemFont, sans-serif",
        "--origam-title---font-family": "'Inter', -apple-system, BlinkMacSystemFont, sans-serif",
        "--origam-appbar---bg": "color-mix(in srgb, #fff7f0 72%, transparent)",
        "--origam-appbar---backdrop-filter": "saturate(140%) blur(16px)",
        "--origam-menu---background": "var(--origam-color__surface---raised)",
        "--origam-menu---color": "var(--origam-color__text---primary)",
        "--origam-menu---border-radius": "6px",
        "--origam-menu---box-shadow": "0 1px 3px rgba(225, 29, 72, 0.08), 0 1px 2px rgba(0, 0, 0, 0.06), 0 0 0 1px var(--origam-color__border---default)",
        "--origam-menu__content---padding": "4px",
        "--origam-list---background": "transparent",
        "--origam-list---padding-block-start": "0",
        "--origam-list---padding-block-end": "0",
        "--origam-list-item---padding-inline-start": "12px",
        "--origam-list-item---padding-inline-end": "12px",
        "--m-shadow-card": "warm red card shadow --m-shadow-btn: red 2-layer glow for primary button --m-shadow-elev: elevated card shadow *//* ── Gradients — marketing display ─────────────────────────────────── Hero glow: --m-bg-decor-1 = warm amber wash from top (section-scoped) CTA glow: --m-bg-decor-2 = orange radial at right Hero title: --m-glow-text = red→orange→amber tricolor gradient Hero grid: warm red tinted 1px grid lines KPI values: same tricolor gradient as title */ --origam-gradient---hero-glow: linear-gradient(180deg, #ffedd5 0%, transparent 40%)",
        "--origam-gradient---cta-glow": "none",
        "--origam-gradient---cta-glow-top": "radial-gradient(ellipse 50% 50% at 90% 20%, rgba(251, 146, 60, 0.20), transparent 60%)",
        "--origam-gradient---hero-title": "linear-gradient(90deg, #e11d48 0%, #ea580c 50%, #f59e0b 100%)",
        "--origam-gradient---hero-grid": "linear-gradient(rgba(225, 29, 72, 0.06) 1px, transparent 1px), linear-gradient(90deg, rgba(225, 29, 72, 0.06) 1px, transparent 1px)",
        "--origam-gradient---kpi-value": "linear-gradient(90deg, #e11d48 0%, #ea580c 50%, #f59e0b 100%)",
        "--origam-gradient---btn-primary": "linear-gradient(#e11d48, #e11d48)",
        "--origam-gradient---btn-secondary": "none",
        "--origam-btn---border-color": "#fed7aa",
        "--origam-btn---border-width-outlined": "1px",
        "--origam-btn---border-width-ghost": "1px",
        "--origam-btn---box-shadow-elevated": "0 2px 0 rgba(225, 29, 72, 0.20), 0 4px 12px -2px rgba(225, 29, 72, 0.35)",
        "--origam-btn---box-shadow-ghost": "none",
        "--origam-btn---border-radius": "var(--origam-radius---btn, 6px)",
        "--origam-card---background": "#ffffff",
        "--origam-card---border-color": "#fed7aa",
        "--origam-card---border-style": "solid",
        "--origam-card---border-top-width": "1px",
        "--origam-card---border-right-width": "1px",
        "--origam-card---border-bottom-width": "1px",
        "--origam-card---border-left-width": "1px",
        "--origam-card---border-start-start-radius": "10px",
        "--origam-card---border-start-end-radius": "10px",
        "--origam-card---border-end-end-radius": "10px",
        "--origam-card---border-end-start-radius": "10px",
        "--origam-card---box-shadow": "0 1px 3px rgba(225, 29, 72, 0.08), 0 1px 2px rgba(0, 0, 0, 0.06)",
        "--origam-chip---border-radius": "6px",
        "--origam-chip---border-color": "#fed7aa",
        "--origam-chip---border-width": "1px",
        "--origam-chip---border-style": "solid",
        "--origam-chip---background-color": "var(--origam-color__surface---sunken, #ffedd5)",
        "--origam-code---border-radius": "6px",
        "--origam-code---border-color": "#fed7aa",
        "--origam-code---border-width": "1px",
        "--origam-code---background-color": "#ffedd5",
        "--origam-field---border-radius": "6px",
        "--origam-field---border-color": "#fb923c",
        "--origam-field---border-opacity": "0.50",
        "--origam-alert---border-radius": "6px",
        "--origam-color__feedback--success---bg": "#16a34a",
        "--origam-color__feedback--success---bgSubtle": "#f0fdf4",
        "--origam-color__feedback--success---fg": "#000000",
        "--origam-color__feedback--success---fgSubtle": "#15803d",
        "--origam-color__feedback--success---border": "#16a34a",
        "--origam-color__feedback--warning---bg": "#b45309",
        "--origam-color__feedback--warning---bgSubtle": "#fffbeb",
        "--origam-color__feedback--warning---fg": "#ffffff",
        "--origam-color__feedback--warning---fgSubtle": "#92400e",
        "--origam-color__feedback--warning---border": "#b45309",
        "--origam-color__feedback--danger---bg": "#dc2626",
        "--origam-color__feedback--danger---bgSubtle": "#fff1f2",
        "--origam-color__feedback--danger---fg": "#ffffff",
        "--origam-color__feedback--danger---fgSubtle": "#b91c1c",
        "--origam-color__feedback--danger---border": "#dc2626",
        "--origam-color__feedback--info---bg": "#1677ff",
        "--origam-color__feedback--info---bgSubtle": "#eff6ff",
        "--origam-color__feedback--info---fg": "#000000",
        "--origam-color__feedback--info---fgSubtle": "#1d4ed8",
        "--origam-color__feedback--info---border": "#1677ff"
    }

export const THEME_BUILDER_PRESET_ECOM_DARK_VARS: Record<string, string> = {
        "--origam-font-family---heading": "'Inter', -apple-system, BlinkMacSystemFont, sans-serif",
        "--origam-title---font-family": "'Inter', -apple-system, BlinkMacSystemFont, sans-serif",
        "--origam-appbar---bg": "color-mix(in srgb, #1a0f0a 72%, transparent)",
        "--origam-appbar---backdrop-filter": "saturate(140%) blur(16px)",
        "--origam-menu---background": "var(--origam-color__surface---raised)",
        "--origam-menu---color": "var(--origam-color__text---primary)",
        "--origam-menu---border-radius": "6px",
        "--origam-menu---box-shadow": "0 4px 24px -4px rgba(0, 0, 0, 0.60), 0 0 0 1px var(--origam-color__border---default)",
        "--origam-menu__content---padding": "4px",
        "--origam-list---background": "transparent",
        "--origam-list---padding-block-start": "0",
        "--origam-list---padding-block-end": "0",
        "--origam-list-item---padding-inline-start": "12px",
        "--origam-list-item---padding-inline-end": "12px",
        "--origam-gradient---hero-glow": "linear-gradient(180deg, rgba(255, 237, 213, 0.08) 0%, transparent 40%)",
        "--origam-gradient---cta-glow": "none",
        "--origam-gradient---cta-glow-top": "radial-gradient(ellipse 50% 50% at 90% 20%, rgba(251, 146, 60, 0.15), transparent 60%)",
        "--origam-gradient---hero-title": "linear-gradient(90deg, #e11d48 0%, #ea580c 50%, #f59e0b 100%)",
        "--origam-gradient---hero-grid": "linear-gradient(rgba(244, 63, 94, 0.06) 1px, transparent 1px), linear-gradient(90deg, rgba(244, 63, 94, 0.06) 1px, transparent 1px)",
        "--origam-gradient---kpi-value": "linear-gradient(90deg, #f43f5e 0%, #fb923c 50%, #f59e0b 100%)",
        "--origam-gradient---btn-primary": "linear-gradient(#f43f5e, #f43f5e)",
        "--origam-gradient---btn-secondary": "none",
        "--origam-btn---border-color": "rgba(251, 146, 60, 0.30)",
        "--origam-btn---border-width-outlined": "1px",
        "--origam-btn---border-width-ghost": "1px",
        "--origam-btn---box-shadow-elevated": "0 2px 0 rgba(244, 63, 94, 0.25), 0 4px 12px -2px rgba(244, 63, 94, 0.40)",
        "--origam-btn---box-shadow-ghost": "none",
        "--origam-btn---border-radius": "var(--origam-radius---btn, 6px)",
        "--origam-card---background": "#2e1b14",
        "--origam-card---border-color": "rgba(251, 146, 60, 0.20)",
        "--origam-card---border-style": "solid",
        "--origam-card---border-top-width": "1px",
        "--origam-card---border-right-width": "1px",
        "--origam-card---border-bottom-width": "1px",
        "--origam-card---border-left-width": "1px",
        "--origam-card---border-start-start-radius": "10px",
        "--origam-card---border-start-end-radius": "10px",
        "--origam-card---border-end-end-radius": "10px",
        "--origam-card---border-end-start-radius": "10px",
        "--origam-card---box-shadow": "0 1px 3px rgba(225, 29, 72, 0.12), 0 1px 2px rgba(0, 0, 0, 0.30)",
        "--origam-chip---border-radius": "6px",
        "--origam-chip---border-color": "rgba(251, 146, 60, 0.30)",
        "--origam-chip---border-width": "1px",
        "--origam-chip---border-style": "solid",
        "--origam-chip---background-color": "var(--origam-color__surface---sunken, #231510)",
        "--origam-code---border-radius": "6px",
        "--origam-code---border-color": "rgba(251, 146, 60, 0.20)",
        "--origam-code---border-width": "1px",
        "--origam-code---background-color": "#231510",
        "--origam-field---border-radius": "6px",
        "--origam-field---border-color": "#fb923c",
        "--origam-field---border-opacity": "0.40",
        "--origam-alert---border-radius": "6px",
        "--origam-color__feedback--success---bg": "#4ade80",
        "--origam-color__feedback--success---bgSubtle": "rgba(74, 222, 128, 0.14)",
        "--origam-color__feedback--success---fg": "#1a0f0a",
        "--origam-color__feedback--success---fgSubtle": "#86efac",
        "--origam-color__feedback--success---border": "#4ade80",
        "--origam-color__feedback--warning---bg": "#fbbf24",
        "--origam-color__feedback--warning---bgSubtle": "rgba(251, 191, 36, 0.14)",
        "--origam-color__feedback--warning---fg": "#1a0f0a",
        "--origam-color__feedback--warning---fgSubtle": "#fcd34d",
        "--origam-color__feedback--warning---border": "#fbbf24",
        "--origam-color__feedback--danger---bg": "#ef4444",
        "--origam-color__feedback--danger---bgSubtle": "rgba(239, 68, 68, 0.14)",
        "--origam-color__feedback--danger---fg": "#1a0f0a",
        "--origam-color__feedback--danger---fgSubtle": "#fca5a5",
        "--origam-color__feedback--danger---border": "#ef4444",
        "--origam-color__feedback--info---bg": "#60a5fa",
        "--origam-color__feedback--info---bgSubtle": "rgba(96, 165, 250, 0.14)",
        "--origam-color__feedback--info---fg": "#1a0f0a",
        "--origam-color__feedback--info---fgSubtle": "#93c5fd",
        "--origam-color__feedback--info---border": "#60a5fa"
    }

export const THEME_BUILDER_PRESET_SOBRE_LIGHT_VARS: Record<string, string> = {
        "--origam-alert---border-radius": "10px",
        "--origam-alert---box-shadow-elevated": "0 1px 3px rgba(0, 0, 0, 0.04), 0 8px 24px -16px rgba(0, 0, 0, 0.18)",
        "--origam-btn---border-color": "var(--origam-color__border---strong)",
        "--origam-btn---border-width-ghost": "1px",
        "--origam-btn---border-width-outlined": "1px",
        "--origam-card---background": "var(--origam-color__surface---raised)",
        "--origam-card---border-color": "var(--origam-color__border---default)",
        "--origam-card---border-radius-rounded": "12px",
        "--origam-chip---background-color": "var(--origam-color__surface---raised)",
        "--origam-chip---border-color": "var(--origam-color__border---default)",
        "--origam-color__feedback--success---bg": "#16a34a",
        "--origam-color__feedback--success---bgSubtle": "rgba(22, 163, 74, 0.08)",
        "--origam-color__feedback--success---fg": "#000000",
        "--origam-color__feedback--success---fgSubtle": "#15803d",
        "--origam-color__feedback--success---border": "#16a34a",
        "--origam-color__feedback--warning---bg": "#d97706",
        "--origam-color__feedback--warning---bgSubtle": "rgba(217, 119, 6, 0.08)",
        "--origam-color__feedback--warning---fg": "#000000",
        "--origam-color__feedback--warning---fgSubtle": "#b45309",
        "--origam-color__feedback--warning---border": "#d97706",
        "--origam-color__feedback--danger---bg": "#dc2626",
        "--origam-color__feedback--danger---bgSubtle": "rgba(220, 38, 38, 0.08)",
        "--origam-color__feedback--danger---fg": "#ffffff",
        "--origam-color__feedback--danger---fgSubtle": "#b91c1c",
        "--origam-color__feedback--danger---border": "#dc2626",
        "--origam-color__feedback--info---bg": "#2563eb",
        "--origam-color__feedback--info---bgSubtle": "rgba(37, 99, 235, 0.08)",
        "--origam-color__feedback--info---fg": "#ffffff",
        "--origam-color__feedback--info---fgSubtle": "#1d4ed8",
        "--origam-color__feedback--info---border": "#2563eb"
    }

export const THEME_BUILDER_PRESET_SOBRE_DARK_VARS: Record<string, string> = {
        "--origam-alert---border-radius": "10px",
        "--origam-alert---box-shadow-elevated": "inset 0 1px 0 rgba(255, 255, 255, 0.03), 0 8px 24px -16px rgba(0, 0, 0, 0.6)",
        "--origam-btn---border-color": "var(--origam-color__border---strong)",
        "--origam-btn---border-width-ghost": "1px",
        "--origam-btn---border-width-outlined": "1px",
        "--origam-card---background": "var(--origam-color__surface---raised)",
        "--origam-card---border-color": "var(--origam-color__border---default)",
        "--origam-card---border-radius-rounded": "12px",
        "--origam-chip---background-color": "var(--origam-color__surface---raised)",
        "--origam-chip---border-color": "var(--origam-color__border---default)",
        "--origam-color__feedback--success---bg": "#6ee7b7",
        "--origam-color__feedback--success---bgSubtle": "rgba(110, 231, 183, 0.12)",
        "--origam-color__feedback--success---fg": "#0a0a0a",
        "--origam-color__feedback--success---fgSubtle": "#6ee7b7",
        "--origam-color__feedback--success---border": "#6ee7b7",
        "--origam-color__feedback--warning---bg": "#fbbf24",
        "--origam-color__feedback--warning---bgSubtle": "rgba(251, 191, 36, 0.12)",
        "--origam-color__feedback--warning---fg": "#0a0a0a",
        "--origam-color__feedback--warning---fgSubtle": "#fbbf24",
        "--origam-color__feedback--warning---border": "#fbbf24",
        "--origam-color__feedback--danger---bg": "#f87171",
        "--origam-color__feedback--danger---bgSubtle": "rgba(248, 113, 113, 0.12)",
        "--origam-color__feedback--danger---fg": "#ffffff",
        "--origam-color__feedback--danger---fgSubtle": "#f87171",
        "--origam-color__feedback--danger---border": "#f87171",
        "--origam-color__feedback--info---bg": "#60a5fa",
        "--origam-color__feedback--info---bgSubtle": "rgba(96, 165, 250, 0.12)",
        "--origam-color__feedback--info---fg": "#0a0a0a",
        "--origam-color__feedback--info---fgSubtle": "#60a5fa",
        "--origam-color__feedback--info---border": "#60a5fa"
    }

export const THEME_BUILDER_BRAND_PRESETS: IThemeBuilderPreset[] = [
    {
        key: 'cartoon',
        labelKey: 'theming.preset.cartoon',
        labelFallback: 'Cartoon',
        light: THEME_BUILDER_PRESET_CARTOON_LIGHT_VARS,
        dark: THEME_BUILDER_PRESET_CARTOON_DARK_VARS
    },
    {
        key: 'apple',
        labelKey: 'theming.preset.apple',
        labelFallback: 'Apple',
        light: THEME_BUILDER_PRESET_APPLE_LIGHT_VARS,
        dark: THEME_BUILDER_PRESET_APPLE_DARK_VARS
    },
    {
        key: 'geek',
        labelKey: 'theming.preset.geek',
        labelFallback: 'Geek',
        light: THEME_BUILDER_PRESET_GEEK_LIGHT_VARS,
        dark: THEME_BUILDER_PRESET_GEEK_DARK_VARS
    },
    {
        key: 'glass',
        labelKey: 'theming.preset.glass',
        labelFallback: 'Glass',
        light: THEME_BUILDER_PRESET_GLASS_LIGHT_VARS,
        dark: THEME_BUILDER_PRESET_GLASS_DARK_VARS
    },
    {
        key: 'editorial',
        labelKey: 'theming.preset.editorial',
        labelFallback: 'Editorial',
        light: THEME_BUILDER_PRESET_EDITORIAL_LIGHT_VARS,
        dark: THEME_BUILDER_PRESET_EDITORIAL_DARK_VARS
    },
    {
        key: 'material',
        labelKey: 'theming.preset.material',
        labelFallback: 'Material',
        light: THEME_BUILDER_PRESET_MATERIAL_LIGHT_VARS,
        dark: THEME_BUILDER_PRESET_MATERIAL_DARK_VARS
    },
    {
        key: 'ecom',
        labelKey: 'theming.preset.ecom',
        labelFallback: 'E-commerce',
        light: THEME_BUILDER_PRESET_ECOM_LIGHT_VARS,
        dark: THEME_BUILDER_PRESET_ECOM_DARK_VARS
    },
    {
        key: 'sobre',
        labelKey: 'theming.preset.sobre',
        labelFallback: 'Sobre',
        light: THEME_BUILDER_PRESET_SOBRE_LIGHT_VARS,
        dark: THEME_BUILDER_PRESET_SOBRE_DARK_VARS
    }
]
