/**
 * THEME_BUILDER_PRESETS — seed values for the /theming builder, one entry per
 * DS preset (origam light, origam dark) plus the 8 brand themes (cartoon,
 * apple, geek, glass, editorial, material, ecom, sobre) × 2 modes = 18 total.
 *
 * Origam presets: GÉNÉRÉ depuis packages/ds/src/themes/origam.theme.ts.
 * Brand presets: GÉNÉRÉS depuis packages/marketing/src/assets/css/themes/*.css
 * via scripts/generate-brand-presets.mjs — ne PAS éditer à la main.
 */
import type { IOrigamTheme } from 'origam/interfaces'
import { resolveThemeVars } from 'origam/utils'

import type { IThemeBuilderPreset } from '~/interfaces/theme-builder.interface'
import { THEME_BUILDER_BRAND_PRESETS } from '~/consts/theme-builder-brand-presets.const'
import { cartoonThemes } from '~/themes/cartoon.theme'
import { appleThemes } from '~/themes/apple.theme'
import { geekThemes } from '~/themes/geek.theme'
import { glassThemes } from '~/themes/glass.theme'
import { editorialThemes } from '~/themes/editorial.theme'
import { materialThemes } from '~/themes/material.theme'
import { ecomThemes } from '~/themes/ecom.theme'

/**
 * PROPS-FIRST (logique DS) : un preset est sourcé depuis l'objet `IOrigamTheme`
 * canonique (`src/themes/*.theme.ts`). On résout `vars → --origam-*` via le DS
 * (`resolveThemeVars`) et on prend `theme.components` (props par composant). Ça
 * remplace la génération CSS fragile, thème par thème.
 */
function presetFromThemes (key: string, labelFallback: string, themes: IOrigamTheme[]): IThemeBuilderPreset {
    const light = themes.find(t => t.mode !== 'dark') ?? themes[0]
    const dark = themes.find(t => t.mode === 'dark') ?? light
    const lightVars = resolveThemeVars(light) as Record<string, string>
    return {
        key,
        labelKey: `theming.preset.${key}`,
        labelFallback,
        light: lightVars,
        dark: { ...lightVars, ...(resolveThemeVars(dark) as Record<string, string>) },
        components: { ...(light.components ?? {}), ...(dark.components ?? {}) }
    }
}

export const THEME_BUILDER_PRESET_LIGHT_VARS: Record<string, string> = {
        "--origam-alert---accent-width": "24px",
        "--origam-alert---background-color": "#e6e6e6",
        "--origam-alert---border-bottom-width": "0px",
        "--origam-alert---border-color": "rgba(0, 0, 0, 0)",
        "--origam-alert---border-left-width": "0px",
        "--origam-alert---border-radius": "0px",
        "--origam-alert---border-radius-rounded": "4px",
        "--origam-alert---border-right-width": "0px",
        "--origam-alert---border-style": "solid",
        "--origam-alert---border-top-width": "0px",
        "--origam-alert---box-shadow-elevated": "0px 6px 24px 0px rgba(0,0,0,0.05), 0px 0px 0px 1px rgba(0,0,0,0.08)",
        "--origam-alert---color": "#171717",
        "--origam-alert---density": "0px",
        "--origam-alert---margin-block-end": "0px",
        "--origam-alert---margin-block-start": "0px",
        "--origam-alert---margin-inline-end": "0px",
        "--origam-alert---margin-inline-start": "0px",
        "--origam-alert---padding-block-end": "16px",
        "--origam-alert---padding-block-start": "16px",
        "--origam-alert---padding-inline-end": "16px",
        "--origam-alert---padding-inline-start": "16px",
        "--origam-alert---position": "static",
        "--origam-avatar---background-color": "#f5f5f5",
        "--origam-avatar---border-color": "currentColor",
        "--origam-avatar---border-radius": "9999px",
        "--origam-avatar---border-radius-rounded": "4px",
        "--origam-avatar---border-radius-square": "0px",
        "--origam-avatar---border-style": "solid",
        "--origam-avatar---border-width": "0px",
        "--origam-avatar---box-shadow": "0px 0px 0px 0px rgba(0,0,0,0)",
        "--origam-avatar---box-shadow-elevated": "0px 6px 24px 0px rgba(0,0,0,0.05), 0px 0px 0px 1px rgba(0,0,0,0.08)",
        "--origam-avatar---color": "#525252",
        "--origam-avatar---density": "0px",
        "--origam-avatar---font-size": "1.5rem",
        "--origam-avatar---font-weight": "400",
        "--origam-avatar---letter-spacing": "0em",
        "--origam-avatar---line-height": "1",
        "--origam-avatar---margin-block-end": "0px",
        "--origam-avatar---margin-block-start": "0px",
        "--origam-avatar---margin-inline-end": "0px",
        "--origam-avatar---margin-inline-start": "0px",
        "--origam-avatar---overflow": "hidden",
        "--origam-avatar---padding-block-end": "0px",
        "--origam-avatar---padding-block-start": "0px",
        "--origam-avatar---padding-inline-end": "0px",
        "--origam-avatar---padding-inline-start": "0px",
        "--origam-badge__badge---background-color": "#7c3aed",
        "--origam-badge__badge---border-bottom-width": "0px",
        "--origam-badge__badge---border-color": "currentColor",
        "--origam-badge__badge---border-left-width": "0px",
        "--origam-badge__badge---border-radius": "9999px",
        "--origam-badge__badge---border-right-width": "0px",
        "--origam-badge__badge---border-style": "solid",
        "--origam-badge__badge---border-top-width": "0px",
        "--origam-badge__badge---border-width": "0px",
        "--origam-badge__badge---box-shadow": "0px 0px 0px 0px rgba(0,0,0,0)",
        "--origam-badge__badge---box-shadow-elevated": "0px 6px 24px 0px rgba(0,0,0,0.05), 0px 0px 0px 1px rgba(0,0,0,0.08)",
        "--origam-badge__badge---color": "#ffffff",
        "--origam-badge__badge---font-size": "0.75rem",
        "--origam-badge__badge---font-weight": "500",
        "--origam-badge__badge---height": "1.25rem",
        "--origam-badge__badge---margin-block-end": "0px",
        "--origam-badge__badge---margin-block-start": "0px",
        "--origam-badge__badge---margin-inline-end": "0px",
        "--origam-badge__badge---margin-inline-start": "0px",
        "--origam-badge__badge---min-width": "20px",
        "--origam-badge__badge---padding-block-end": "0px",
        "--origam-badge__badge---padding-block-start": "0px",
        "--origam-badge__badge---padding-inline-end": "4px",
        "--origam-badge__badge---padding-inline-start": "4px",
        "--origam-btn---background-color": "#e6e6e6",
        "--origam-btn---background-color-disabled": "#e6e6e6",
        "--origam-btn---background-color-hover": "#d4d4d4",
        "--origam-btn---background-color-tonal": "#f5f5f5",
        "--origam-btn---border-color": "currentColor",
        "--origam-btn---border-radius": "4px",
        "--origam-btn---border-radius-icon": "9999px",
        "--origam-btn---border-radius-rounded": "24px",
        "--origam-btn---border-style": "solid",
        "--origam-btn---border-width": "0px",
        "--origam-btn---border-width-ghost": "1px",
        "--origam-btn---border-width-outlined": "1px",
        "--origam-btn---color": "#262626",
        "--origam-btn---color-disabled": "#a3a3a3",
        "--origam-btn---height": "36px",
        "--origam-btn---height-lg": "44px",
        "--origam-btn---height-md": "36px",
        "--origam-btn---height-sm": "28px",
        "--origam-btn---height-xl": "52px",
        "--origam-btn---height-xs": "20px",
        "--origam-btn---line-height": "1",
        "--origam-btn---max-height": "100%",
        "--origam-btn---max-width": "100%",
        "--origam-btn---min-width": "64px",
        "--origam-card---background": "#ffffff",
        "--origam-card---border-bottom-width": "0px",
        "--origam-card---border-color": "#d4d4d4",
        "--origam-card---border-end-end-radius": "0px",
        "--origam-card---border-end-start-radius": "0px",
        "--origam-card---border-left-width": "0px",
        "--origam-card---border-radius-rounded": "8px",
        "--origam-card---border-right-width": "0px",
        "--origam-card---border-start-end-radius": "0px",
        "--origam-card---border-start-start-radius": "0px",
        "--origam-card---border-style": "solid",
        "--origam-card---border-top-width": "0px",
        "--origam-card---color": "#171717",
        "--origam-card---margin-block-end": "0px",
        "--origam-card---margin-block-start": "0px",
        "--origam-card---margin-inline-end": "0px",
        "--origam-card---margin-inline-start": "0px",
        "--origam-card---opacity": "1",
        "--origam-card---opacity-disabled": "0.6",
        "--origam-card---overlay-opacity-disabled": "0",
        "--origam-card---overlay-opacity-hover": "0.12",
        "--origam-card---padding-block-end": "0px",
        "--origam-card---padding-block-start": "0px",
        "--origam-card---padding-inline-end": "0px",
        "--origam-checkbox---flex": "0 1 auto",
        "--origam-checkbox---min-height": "56px",
        "--origam-checkbox---transition-duration": "200ms",
        "--origam-checkbox---transition-easing": "cubic-bezier(0.4, 0, 0.2, 1)",
        "--origam-chip---background-color": "#f5f5f5",
        "--origam-chip---border-color": "currentColor",
        "--origam-chip---border-radius": "9999px",
        "--origam-chip---border-radius-label": "4px",
        "--origam-chip---border-style": "solid",
        "--origam-chip---border-width": "0px",
        "--origam-chip---color": "#171717",
        "--origam-chip---density": "0px",
        "--origam-chip---font-size": "0.875rem",
        "--origam-chip---font-size-lg": "1rem",
        "--origam-chip---font-size-md": "0.875rem",
        "--origam-chip---font-size-sm": "0.75rem",
        "--origam-chip---font-size-xl": "1.125rem",
        "--origam-chip---font-size-xs": "0.625rem",
        "--origam-chip---opacity-disabled": "0.32",
        "--origam-chip---overlay-opacity": "0",
        "--origam-chip---overlay-opacity-active": "0.12",
        "--origam-chip---overlay-opacity-focus": "0.12",
        "--origam-chip---overlay-opacity-hover": "0.24",
        "--origam-chip---padding-lg": "14px",
        "--origam-chip---padding-md": "12px",
        "--origam-chip---padding-sm": "10px",
        "--origam-chip---padding-xl": "17px",
        "--origam-chip---padding-xs": "8px",
        "--origam-color__feedback--danger---bg": "#ef4444",
        "--origam-color__feedback--danger---bgSubtle": "#fff1f2",
        "--origam-color__feedback--danger---border": "#cf6679",
        "--origam-color__feedback--danger---fg": "#ffffff",
        "--origam-color__feedback--danger---fgSubtle": "#b91c1c",
        "--origam-color__feedback--info---bg": "#2196f3",
        "--origam-color__feedback--info---bgSubtle": "#eff6ff",
        "--origam-color__feedback--info---border": "#2196f3",
        "--origam-color__feedback--info---fg": "#ffffff",
        "--origam-color__feedback--info---fgSubtle": "#1e40af",
        "--origam-color__feedback--success---bg": "#4caf50",
        "--origam-color__feedback--success---bgSubtle": "#f0fdf4",
        "--origam-color__feedback--success---border": "#4caf50",
        "--origam-color__feedback--success---fg": "#ffffff",
        "--origam-color__feedback--success---fgSubtle": "#16a34a",
        "--origam-color__feedback--warning---bg": "#fb8c00",
        "--origam-color__feedback--warning---bgSubtle": "#fffbeb",
        "--origam-color__feedback--warning---border": "#fb8c00",
        "--origam-color__feedback--warning---fg": "#ffffff",
        "--origam-color__feedback--warning---fgSubtle": "#b45309",
        "--origam-divider---border-style": "solid",
        "--origam-divider---color": "#d4d4d4",
        "--origam-divider---margin-block": "0px",
        "--origam-divider---opacity": "1",
        "--origam-divider---padding-block-end": "0px",
        "--origam-divider---padding-block-start": "0px",
        "--origam-divider---padding-inline-end": "0px",
        "--origam-divider---padding-inline-start": "0px",
        "--origam-divider---thickness": "1px",
        "--origam-field---append-inner-icon-opacity": "0.7",
        "--origam-field---append-inner-icon-opacity-focused": "1",
        "--origam-field---background-color": "rgba(0, 0, 0, 0)",
        "--origam-field---border-color": "#a3a3a3",
        "--origam-field---border-opacity": "0.38",
        "--origam-field---border-radius": "4px",
        "--origam-field---border-width": "1px",
        "--origam-field---color": "#171717",
        "--origam-field---font-size": "16px",
        "--origam-field---letter-spacing": "0.0094em",
        "--origam-field---opacity-disabled": "0.5",
        "--origam-field---padding-bottom": "6px",
        "--origam-field---padding-end": "16px",
        "--origam-field---padding-start": "16px",
        "--origam-field---padding-top": "8px",
        "--origam-field---prepend-inner-icon-opacity": "0.7",
        "--origam-field---prepend-inner-icon-opacity-focused": "1",
        "--origam-field---transition-duration": "150ms",
        "--origam-field---transition-easing": "cubic-bezier(0.4, 0, 0.2, 1)",
        "--origam-field---variant-outlined-background-color": "rgba(0, 0, 0, 0)",
        "--origam-field---variant-solo-box-shadow": "0px 1px 3px 0px rgba(0,0,0,0.1), 0px 1px 2px -1px rgba(0,0,0,0.1)",
        "--origam-icon---color": "currentColor",
        "--origam-icon---color-danger": "#ef4444",
        "--origam-icon---color-disabled": "#a3a3a3",
        "--origam-icon---color-info": "#2196f3",
        "--origam-icon---color-primary": "#7c3aed",
        "--origam-icon---color-success": "#4caf50",
        "--origam-icon---color-warning": "#fb8c00",
        "--origam-icon---font-size-2xl": "1.25rem",
        "--origam-icon---font-size-3xl": "1.5rem",
        "--origam-icon---font-size-4xl": "1.875rem",
        "--origam-icon---font-size-lg": "1rem",
        "--origam-icon---font-size-md": "0.875rem",
        "--origam-icon---font-size-sm": "0.75rem",
        "--origam-icon---font-size-xl": "1.125rem",
        "--origam-icon---font-size-xs": "0.625rem",
        "--origam-icon---transition-duration": "100ms",
        "--origam-icon---transition-timing-function": "cubic-bezier(0.4, 0, 0.2, 1)",
        "--origam-progress-linear---background": "rgba(0, 0, 0, 0)",
        "--origam-progress-linear---background-track-background": "currentColor",
        "--origam-progress-linear---background-track-opacity": "0.5",
        "--origam-progress-linear---background-track-position": "absolute",
        "--origam-progress-linear---indeterminate-duration": "2200ms",
        "--origam-progress-linear---overflow": "hidden",
        "--origam-progress-linear---position": "relative",
        "--origam-progress-linear---rounded-border-radius": "9999px",
        "--origam-progress-linear---transition-duration": "200ms",
        "--origam-progress-linear---transition-easing": "cubic-bezier(0.4, 0, 0.2, 1)",
        "--origam-progress-linear---width": "100%",
        "--origam-select---min-width": "150px",
        "--origam-select---no-data-color": "#525252",
        "--origam-select---no-data-font-size": "0.75rem",
        "--origam-select---no-data-padding": "16px",
        "--origam-select---no-data-text-align": "center",
        "--origam-switch---opacity-disabled": "0.32",
        "--origam-switch---transition-duration": "200ms",
        "--origam-switch---transition-timing-function": "cubic-bezier(0.4, 0, 0.2, 1)",
        "--origam-title---color": "#171717",
        "--origam-title---font-family": "Inter, \\'Helvetica Neue\\', Arial, sans-serif",
        "--origam-title---font-size-2xl": "1.875rem",
        "--origam-title---font-size-3xl": "2.25rem",
        "--origam-title---font-size-lg": "1.25rem",
        "--origam-title---font-size-md": "1.125rem",
        "--origam-title---font-size-sm": "1rem",
        "--origam-title---font-size-xl": "1.5rem",
        "--origam-title---font-size-xs": "0.875rem",
        "--origam-title---font-weight": "600",
        "--origam-title---letter-spacing": "-0.025em",
        "--origam-title---line-height": "1.25",
        "--origam-title---margin-block-end": "0px",
        "--origam-title---margin-block-start": "0px"
}

export const THEME_BUILDER_PRESET_DARK_VARS: Record<string, string> = {
        "--origam-alert---accent-width": "24px",
        "--origam-alert---background-color": "#262626",
        "--origam-alert---border-bottom-width": "0px",
        "--origam-alert---border-color": "rgba(0, 0, 0, 0)",
        "--origam-alert---border-left-width": "0px",
        "--origam-alert---border-radius": "0px",
        "--origam-alert---border-radius-rounded": "4px",
        "--origam-alert---border-right-width": "0px",
        "--origam-alert---border-style": "solid",
        "--origam-alert---border-top-width": "0px",
        "--origam-alert---box-shadow-elevated": "0px 6px 24px 0px rgba(0,0,0,0.05), 0px 0px 0px 1px rgba(0,0,0,0.08)",
        "--origam-alert---color": "#fafafa",
        "--origam-alert---density": "0px",
        "--origam-alert---margin-block-end": "0px",
        "--origam-alert---margin-block-start": "0px",
        "--origam-alert---margin-inline-end": "0px",
        "--origam-alert---margin-inline-start": "0px",
        "--origam-alert---padding-block-end": "16px",
        "--origam-alert---padding-block-start": "16px",
        "--origam-alert---padding-inline-end": "16px",
        "--origam-alert---padding-inline-start": "16px",
        "--origam-alert---position": "static",
        "--origam-avatar---background-color": "#262626",
        "--origam-avatar---border-color": "currentColor",
        "--origam-avatar---border-radius": "9999px",
        "--origam-avatar---border-radius-rounded": "4px",
        "--origam-avatar---border-radius-square": "0px",
        "--origam-avatar---border-style": "solid",
        "--origam-avatar---border-width": "0px",
        "--origam-avatar---box-shadow": "0px 0px 0px 0px rgba(0,0,0,0)",
        "--origam-avatar---box-shadow-elevated": "0px 6px 24px 0px rgba(0,0,0,0.05), 0px 0px 0px 1px rgba(0,0,0,0.08)",
        "--origam-avatar---color": "#a3a3a3",
        "--origam-avatar---density": "0px",
        "--origam-avatar---font-size": "1.5rem",
        "--origam-avatar---font-weight": "400",
        "--origam-avatar---letter-spacing": "0em",
        "--origam-avatar---line-height": "1",
        "--origam-avatar---margin-block-end": "0px",
        "--origam-avatar---margin-block-start": "0px",
        "--origam-avatar---margin-inline-end": "0px",
        "--origam-avatar---margin-inline-start": "0px",
        "--origam-avatar---overflow": "hidden",
        "--origam-avatar---padding-block-end": "0px",
        "--origam-avatar---padding-block-start": "0px",
        "--origam-avatar---padding-inline-end": "0px",
        "--origam-avatar---padding-inline-start": "0px",
        "--origam-badge__badge---background-color": "#8b5cf6",
        "--origam-badge__badge---border-bottom-width": "0px",
        "--origam-badge__badge---border-color": "currentColor",
        "--origam-badge__badge---border-left-width": "0px",
        "--origam-badge__badge---border-radius": "9999px",
        "--origam-badge__badge---border-right-width": "0px",
        "--origam-badge__badge---border-style": "solid",
        "--origam-badge__badge---border-top-width": "0px",
        "--origam-badge__badge---border-width": "0px",
        "--origam-badge__badge---box-shadow": "0px 0px 0px 0px rgba(0,0,0,0)",
        "--origam-badge__badge---box-shadow-elevated": "0px 6px 24px 0px rgba(0,0,0,0.05), 0px 0px 0px 1px rgba(0,0,0,0.08)",
        "--origam-badge__badge---color": "#ffffff",
        "--origam-badge__badge---font-size": "0.75rem",
        "--origam-badge__badge---font-weight": "500",
        "--origam-badge__badge---height": "1.25rem",
        "--origam-badge__badge---margin-block-end": "0px",
        "--origam-badge__badge---margin-block-start": "0px",
        "--origam-badge__badge---margin-inline-end": "0px",
        "--origam-badge__badge---margin-inline-start": "0px",
        "--origam-badge__badge---min-width": "20px",
        "--origam-badge__badge---padding-block-end": "0px",
        "--origam-badge__badge---padding-block-start": "0px",
        "--origam-badge__badge---padding-inline-end": "4px",
        "--origam-badge__badge---padding-inline-start": "4px",
        "--origam-btn---background-color": "#262626",
        "--origam-btn---background-color-disabled": "#262626",
        "--origam-btn---background-color-hover": "#404040",
        "--origam-btn---background-color-tonal": "#262626",
        "--origam-btn---border-color": "currentColor",
        "--origam-btn---border-radius": "4px",
        "--origam-btn---border-radius-icon": "9999px",
        "--origam-btn---border-radius-rounded": "24px",
        "--origam-btn---border-style": "solid",
        "--origam-btn---border-width": "0px",
        "--origam-btn---border-width-ghost": "1px",
        "--origam-btn---border-width-outlined": "1px",
        "--origam-btn---color": "#f5f5f5",
        "--origam-btn---color-disabled": "#525252",
        "--origam-btn---height": "36px",
        "--origam-btn---height-lg": "44px",
        "--origam-btn---height-md": "36px",
        "--origam-btn---height-sm": "28px",
        "--origam-btn---height-xl": "52px",
        "--origam-btn---height-xs": "20px",
        "--origam-btn---line-height": "1",
        "--origam-btn---max-height": "100%",
        "--origam-btn---max-width": "100%",
        "--origam-btn---min-width": "64px",
        "--origam-card---background": "#171717",
        "--origam-card---border-bottom-width": "0px",
        "--origam-card---border-color": "#262626",
        "--origam-card---border-end-end-radius": "0px",
        "--origam-card---border-end-start-radius": "0px",
        "--origam-card---border-left-width": "0px",
        "--origam-card---border-radius-rounded": "8px",
        "--origam-card---border-right-width": "0px",
        "--origam-card---border-start-end-radius": "0px",
        "--origam-card---border-start-start-radius": "0px",
        "--origam-card---border-style": "solid",
        "--origam-card---border-top-width": "0px",
        "--origam-card---color": "#fafafa",
        "--origam-card---margin-block-end": "0px",
        "--origam-card---margin-block-start": "0px",
        "--origam-card---margin-inline-end": "0px",
        "--origam-card---margin-inline-start": "0px",
        "--origam-card---opacity": "1",
        "--origam-card---opacity-disabled": "0.6",
        "--origam-card---overlay-opacity-disabled": "0",
        "--origam-card---overlay-opacity-hover": "0.12",
        "--origam-card---padding-block-end": "0px",
        "--origam-card---padding-block-start": "0px",
        "--origam-card---padding-inline-end": "0px",
        "--origam-checkbox---flex": "0 1 auto",
        "--origam-checkbox---min-height": "56px",
        "--origam-checkbox---transition-duration": "200ms",
        "--origam-checkbox---transition-easing": "cubic-bezier(0.4, 0, 0.2, 1)",
        "--origam-chip---background-color": "#262626",
        "--origam-chip---border-color": "currentColor",
        "--origam-chip---border-radius": "9999px",
        "--origam-chip---border-radius-label": "4px",
        "--origam-chip---border-style": "solid",
        "--origam-chip---border-width": "0px",
        "--origam-chip---color": "#fafafa",
        "--origam-chip---density": "0px",
        "--origam-chip---font-size": "0.875rem",
        "--origam-chip---font-size-lg": "1rem",
        "--origam-chip---font-size-md": "0.875rem",
        "--origam-chip---font-size-sm": "0.75rem",
        "--origam-chip---font-size-xl": "1.125rem",
        "--origam-chip---font-size-xs": "0.625rem",
        "--origam-chip---opacity-disabled": "0.32",
        "--origam-chip---overlay-opacity": "0",
        "--origam-chip---overlay-opacity-active": "0.12",
        "--origam-chip---overlay-opacity-focus": "0.12",
        "--origam-chip---overlay-opacity-hover": "0.24",
        "--origam-chip---padding-lg": "14px",
        "--origam-chip---padding-md": "12px",
        "--origam-chip---padding-sm": "10px",
        "--origam-chip---padding-xl": "17px",
        "--origam-chip---padding-xs": "8px",
        "--origam-color__feedback--danger---bg": "#ef4444",
        "--origam-color__feedback--danger---bgSubtle": "#171717",
        "--origam-color__feedback--danger---border": "#cf6679",
        "--origam-color__feedback--danger---fg": "#ffffff",
        "--origam-color__feedback--danger---fgSubtle": "#cf6679",
        "--origam-color__feedback--info---bg": "#2196f3",
        "--origam-color__feedback--info---bgSubtle": "#171717",
        "--origam-color__feedback--info---border": "#2196f3",
        "--origam-color__feedback--info---fg": "#ffffff",
        "--origam-color__feedback--info---fgSubtle": "#60a5fa",
        "--origam-color__feedback--success---bg": "#4caf50",
        "--origam-color__feedback--success---bgSubtle": "#171717",
        "--origam-color__feedback--success---border": "#4caf50",
        "--origam-color__feedback--success---fg": "#ffffff",
        "--origam-color__feedback--success---fgSubtle": "#4ade80",
        "--origam-color__feedback--warning---bg": "#fb8c00",
        "--origam-color__feedback--warning---bgSubtle": "#171717",
        "--origam-color__feedback--warning---border": "#fb8c00",
        "--origam-color__feedback--warning---fg": "#ffffff",
        "--origam-color__feedback--warning---fgSubtle": "#fbbf24",
        "--origam-divider---border-style": "solid",
        "--origam-divider---color": "#262626",
        "--origam-divider---margin-block": "0px",
        "--origam-divider---opacity": "1",
        "--origam-divider---padding-block-end": "0px",
        "--origam-divider---padding-block-start": "0px",
        "--origam-divider---padding-inline-end": "0px",
        "--origam-divider---padding-inline-start": "0px",
        "--origam-divider---thickness": "1px",
        "--origam-field---append-inner-icon-opacity": "0.7",
        "--origam-field---append-inner-icon-opacity-focused": "1",
        "--origam-field---background-color": "rgba(0, 0, 0, 0)",
        "--origam-field---border-color": "#404040",
        "--origam-field---border-opacity": "0.38",
        "--origam-field---border-radius": "4px",
        "--origam-field---border-width": "1px",
        "--origam-field---color": "#fafafa",
        "--origam-field---font-size": "16px",
        "--origam-field---letter-spacing": "0.0094em",
        "--origam-field---opacity-disabled": "0.5",
        "--origam-field---padding-bottom": "6px",
        "--origam-field---padding-end": "16px",
        "--origam-field---padding-start": "16px",
        "--origam-field---padding-top": "8px",
        "--origam-field---prepend-inner-icon-opacity": "0.7",
        "--origam-field---prepend-inner-icon-opacity-focused": "1",
        "--origam-field---transition-duration": "150ms",
        "--origam-field---transition-easing": "cubic-bezier(0.4, 0, 0.2, 1)",
        "--origam-field---variant-outlined-background-color": "rgba(0, 0, 0, 0)",
        "--origam-field---variant-solo-box-shadow": "0px 1px 3px 0px rgba(0,0,0,0.1), 0px 1px 2px -1px rgba(0,0,0,0.1)",
        "--origam-icon---color": "currentColor",
        "--origam-icon---color-danger": "#ef4444",
        "--origam-icon---color-disabled": "#525252",
        "--origam-icon---color-info": "#2196f3",
        "--origam-icon---color-primary": "#8b5cf6",
        "--origam-icon---color-success": "#4caf50",
        "--origam-icon---color-warning": "#fb8c00",
        "--origam-icon---font-size-2xl": "1.25rem",
        "--origam-icon---font-size-3xl": "1.5rem",
        "--origam-icon---font-size-4xl": "1.875rem",
        "--origam-icon---font-size-lg": "1rem",
        "--origam-icon---font-size-md": "0.875rem",
        "--origam-icon---font-size-sm": "0.75rem",
        "--origam-icon---font-size-xl": "1.125rem",
        "--origam-icon---font-size-xs": "0.625rem",
        "--origam-icon---transition-duration": "100ms",
        "--origam-icon---transition-timing-function": "cubic-bezier(0.4, 0, 0.2, 1)",
        "--origam-progress-linear---background": "rgba(0, 0, 0, 0)",
        "--origam-progress-linear---background-track-background": "currentColor",
        "--origam-progress-linear---background-track-opacity": "0.5",
        "--origam-progress-linear---background-track-position": "absolute",
        "--origam-progress-linear---indeterminate-duration": "2200ms",
        "--origam-progress-linear---overflow": "hidden",
        "--origam-progress-linear---position": "relative",
        "--origam-progress-linear---rounded-border-radius": "9999px",
        "--origam-progress-linear---transition-duration": "200ms",
        "--origam-progress-linear---transition-easing": "cubic-bezier(0.4, 0, 0.2, 1)",
        "--origam-progress-linear---width": "100%",
        "--origam-select---min-width": "150px",
        "--origam-select---no-data-color": "#a3a3a3",
        "--origam-select---no-data-font-size": "0.75rem",
        "--origam-select---no-data-padding": "16px",
        "--origam-select---no-data-text-align": "center",
        "--origam-switch---opacity-disabled": "0.32",
        "--origam-switch---transition-duration": "200ms",
        "--origam-switch---transition-timing-function": "cubic-bezier(0.4, 0, 0.2, 1)",
        "--origam-title---color": "#fafafa",
        "--origam-title---font-family": "Inter, \\'Helvetica Neue\\', Arial, sans-serif",
        "--origam-title---font-size-2xl": "1.875rem",
        "--origam-title---font-size-3xl": "2.25rem",
        "--origam-title---font-size-lg": "1.25rem",
        "--origam-title---font-size-md": "1.125rem",
        "--origam-title---font-size-sm": "1rem",
        "--origam-title---font-size-xl": "1.5rem",
        "--origam-title---font-size-xs": "0.875rem",
        "--origam-title---font-weight": "600",
        "--origam-title---letter-spacing": "-0.025em",
        "--origam-title---line-height": "1.25",
        "--origam-title---margin-block-end": "0px",
        "--origam-title---margin-block-start": "0px"
}

export const THEME_BUILDER_PRESETS: IThemeBuilderPreset[] = [
    {
        key: 'origam',
        labelKey: 'theming.preset.origam',
        labelFallback: 'Origam',
        light: THEME_BUILDER_PRESET_LIGHT_VARS,
        dark: THEME_BUILDER_PRESET_DARK_VARS
    },
    // Brands sourcés depuis leur objet IOrigamTheme (props-first).
    presetFromThemes('cartoon', 'Cartoon', cartoonThemes),
    presetFromThemes('apple', 'Apple', appleThemes),
    presetFromThemes('geek', 'Geek', geekThemes),
    presetFromThemes('glass', 'Glass', glassThemes),
    presetFromThemes('editorial', 'Editorial', editorialThemes),
    presetFromThemes('material', 'Material', materialThemes),
    presetFromThemes('ecom', 'E-commerce', ecomThemes),
    // `sobre` est exclu : c'est la baseline DS = le thème `origam` ci-dessus
    // (même identité), donc le lister en plus ferait un doublon.
    ...THEME_BUILDER_BRAND_PRESETS.filter(
        p => !['cartoon', 'apple', 'geek', 'glass', 'editorial', 'material', 'ecom', 'sobre'].includes(p.key)
    )
]
