/**
* THEME_BUILDER_TOKENS — editable CSS custom properties per core slug.
*
* GÉNÉRÉ depuis packages/ds/src/themes/origam.theme.ts (origamLightTheme.cssVars).
* Bloc-level (et field/badge composés) — valeurs RÉELLES du thème origam light.
* Régénérer si le thème change. Ne PAS inventer de variable.
*/
import type { IThemeBuilderToken } from '~/interfaces/theme-builder.interface'

export const THEME_BUILDER_TOKENS: Record<string, IThemeBuilderToken[]> = {
    "btn": [
        { cssVar: "--origam-btn---background-color", label: "background color", defaultValue: "#e6e6e6", kind: "color" },
        { cssVar: "--origam-btn---background-color-disabled", label: "background color disabled", defaultValue: "#e6e6e6", kind: "color" },
        { cssVar: "--origam-btn---background-color-hover", label: "background color hover", defaultValue: "#d4d4d4", kind: "color" },
        { cssVar: "--origam-btn---background-color-tonal", label: "background color tonal", defaultValue: "#f5f5f5", kind: "color" },
        { cssVar: "--origam-btn---border-color", label: "border color", defaultValue: "currentColor", kind: "text" },
        { cssVar: "--origam-btn---color", label: "color", defaultValue: "#262626", kind: "color" },
        { cssVar: "--origam-btn---color-disabled", label: "color disabled", defaultValue: "#a3a3a3", kind: "color" },
        { cssVar: "--origam-btn---border-radius", label: "border radius", defaultValue: "4px", kind: "text" },
        { cssVar: "--origam-btn---border-radius-icon", label: "border radius icon", defaultValue: "9999px", kind: "text" },
        { cssVar: "--origam-btn---border-radius-rounded", label: "border radius rounded", defaultValue: "24px", kind: "text" },
        { cssVar: "--origam-btn---border-style", label: "border style", defaultValue: "solid", kind: "text" },
        { cssVar: "--origam-btn---border-width", label: "border width", defaultValue: "0px", kind: "text" },
        { cssVar: "--origam-btn---border-width-ghost", label: "border width ghost", defaultValue: "1px", kind: "text" },
        { cssVar: "--origam-btn---border-width-outlined", label: "border width outlined", defaultValue: "1px", kind: "text" },
        { cssVar: "--origam-btn---height", label: "height", defaultValue: "36px", kind: "text" },
        { cssVar: "--origam-btn---height-lg", label: "height lg", defaultValue: "44px", kind: "text" },
        { cssVar: "--origam-btn---height-md", label: "height md", defaultValue: "36px", kind: "text" },
        { cssVar: "--origam-btn---height-sm", label: "height sm", defaultValue: "28px", kind: "text" },
        { cssVar: "--origam-btn---height-xl", label: "height xl", defaultValue: "52px", kind: "text" },
        { cssVar: "--origam-btn---height-xs", label: "height xs", defaultValue: "20px", kind: "text" },
        { cssVar: "--origam-btn---line-height", label: "line height", defaultValue: "1", kind: "text" },
        { cssVar: "--origam-btn---max-height", label: "max height", defaultValue: "100%", kind: "text" },
        { cssVar: "--origam-btn---max-width", label: "max width", defaultValue: "100%", kind: "text" },
        { cssVar: "--origam-btn---min-width", label: "min width", defaultValue: "64px", kind: "text" }
    ],
    "card": [
        { cssVar: "--origam-card---background", label: "background", defaultValue: "#ffffff", kind: "color" },
        { cssVar: "--origam-card---border-color", label: "border color", defaultValue: "#d4d4d4", kind: "color" },
        { cssVar: "--origam-card---color", label: "color", defaultValue: "#171717", kind: "color" },
        { cssVar: "--origam-card---border-bottom-width", label: "border bottom width", defaultValue: "0px", kind: "text" },
        { cssVar: "--origam-card---border-end-end-radius", label: "border end end radius", defaultValue: "0px", kind: "text" },
        { cssVar: "--origam-card---border-end-start-radius", label: "border end start radius", defaultValue: "0px", kind: "text" },
        { cssVar: "--origam-card---border-left-width", label: "border left width", defaultValue: "0px", kind: "text" },
        { cssVar: "--origam-card---border-radius-rounded", label: "border radius rounded", defaultValue: "8px", kind: "text" },
        { cssVar: "--origam-card---border-right-width", label: "border right width", defaultValue: "0px", kind: "text" },
        { cssVar: "--origam-card---border-start-end-radius", label: "border start end radius", defaultValue: "0px", kind: "text" },
        { cssVar: "--origam-card---border-start-start-radius", label: "border start start radius", defaultValue: "0px", kind: "text" },
        { cssVar: "--origam-card---border-style", label: "border style", defaultValue: "solid", kind: "text" },
        { cssVar: "--origam-card---border-top-width", label: "border top width", defaultValue: "0px", kind: "text" },
        { cssVar: "--origam-card---margin-block-end", label: "margin block end", defaultValue: "0px", kind: "text" },
        { cssVar: "--origam-card---margin-block-start", label: "margin block start", defaultValue: "0px", kind: "text" },
        { cssVar: "--origam-card---margin-inline-end", label: "margin inline end", defaultValue: "0px", kind: "text" },
        { cssVar: "--origam-card---margin-inline-start", label: "margin inline start", defaultValue: "0px", kind: "text" },
        { cssVar: "--origam-card---opacity", label: "opacity", defaultValue: "1", kind: "text" },
        { cssVar: "--origam-card---opacity-disabled", label: "opacity disabled", defaultValue: "0.6", kind: "text" },
        { cssVar: "--origam-card---overlay-opacity-disabled", label: "overlay opacity disabled", defaultValue: "0", kind: "text" },
        { cssVar: "--origam-card---overlay-opacity-hover", label: "overlay opacity hover", defaultValue: "0.12", kind: "text" },
        { cssVar: "--origam-card---padding-block-end", label: "padding block end", defaultValue: "0px", kind: "text" },
        { cssVar: "--origam-card---padding-block-start", label: "padding block start", defaultValue: "0px", kind: "text" },
        { cssVar: "--origam-card---padding-inline-end", label: "padding inline end", defaultValue: "0px", kind: "text" }
    ],
    "chip": [
        { cssVar: "--origam-chip---background-color", label: "background color", defaultValue: "#f5f5f5", kind: "color" },
        { cssVar: "--origam-chip---border-color", label: "border color", defaultValue: "currentColor", kind: "text" },
        { cssVar: "--origam-chip---color", label: "color", defaultValue: "#171717", kind: "color" },
        { cssVar: "--origam-chip---border-radius", label: "border radius", defaultValue: "9999px", kind: "text" },
        { cssVar: "--origam-chip---border-radius-label", label: "border radius label", defaultValue: "4px", kind: "text" },
        { cssVar: "--origam-chip---border-style", label: "border style", defaultValue: "solid", kind: "text" },
        { cssVar: "--origam-chip---border-width", label: "border width", defaultValue: "0px", kind: "text" },
        { cssVar: "--origam-chip---opacity-disabled", label: "opacity disabled", defaultValue: "0.32", kind: "text" },
        { cssVar: "--origam-chip---overlay-opacity", label: "overlay opacity", defaultValue: "0", kind: "text" },
        { cssVar: "--origam-chip---overlay-opacity-active", label: "overlay opacity active", defaultValue: "0.12", kind: "text" },
        { cssVar: "--origam-chip---overlay-opacity-focus", label: "overlay opacity focus", defaultValue: "0.12", kind: "text" },
        { cssVar: "--origam-chip---overlay-opacity-hover", label: "overlay opacity hover", defaultValue: "0.24", kind: "text" },
        { cssVar: "--origam-chip---padding-lg", label: "padding lg", defaultValue: "14px", kind: "text" },
        { cssVar: "--origam-chip---padding-md", label: "padding md", defaultValue: "12px", kind: "text" },
        { cssVar: "--origam-chip---padding-sm", label: "padding sm", defaultValue: "10px", kind: "text" },
        { cssVar: "--origam-chip---padding-xl", label: "padding xl", defaultValue: "17px", kind: "text" },
        { cssVar: "--origam-chip---padding-xs", label: "padding xs", defaultValue: "8px", kind: "text" },
        { cssVar: "--origam-chip---density", label: "density", defaultValue: "0px", kind: "text" },
        { cssVar: "--origam-chip---font-size", label: "font size", defaultValue: "0.875rem", kind: "text" },
        { cssVar: "--origam-chip---font-size-lg", label: "font size lg", defaultValue: "1rem", kind: "text" },
        { cssVar: "--origam-chip---font-size-md", label: "font size md", defaultValue: "0.875rem", kind: "text" },
        { cssVar: "--origam-chip---font-size-sm", label: "font size sm", defaultValue: "0.75rem", kind: "text" },
        { cssVar: "--origam-chip---font-size-xl", label: "font size xl", defaultValue: "1.125rem", kind: "text" },
        { cssVar: "--origam-chip---font-size-xs", label: "font size xs", defaultValue: "0.625rem", kind: "text" }
    ],
    "avatar": [
        { cssVar: "--origam-avatar---background-color", label: "background color", defaultValue: "#f5f5f5", kind: "color" },
        { cssVar: "--origam-avatar---border-color", label: "border color", defaultValue: "currentColor", kind: "text" },
        { cssVar: "--origam-avatar---color", label: "color", defaultValue: "#525252", kind: "color" },
        { cssVar: "--origam-avatar---border-radius", label: "border radius", defaultValue: "9999px", kind: "text" },
        { cssVar: "--origam-avatar---border-radius-rounded", label: "border radius rounded", defaultValue: "4px", kind: "text" },
        { cssVar: "--origam-avatar---border-radius-square", label: "border radius square", defaultValue: "0px", kind: "text" },
        { cssVar: "--origam-avatar---border-style", label: "border style", defaultValue: "solid", kind: "text" },
        { cssVar: "--origam-avatar---border-width", label: "border width", defaultValue: "0px", kind: "text" },
        { cssVar: "--origam-avatar---line-height", label: "line height", defaultValue: "1", kind: "text" },
        { cssVar: "--origam-avatar---margin-block-end", label: "margin block end", defaultValue: "0px", kind: "text" },
        { cssVar: "--origam-avatar---margin-block-start", label: "margin block start", defaultValue: "0px", kind: "text" },
        { cssVar: "--origam-avatar---margin-inline-end", label: "margin inline end", defaultValue: "0px", kind: "text" },
        { cssVar: "--origam-avatar---margin-inline-start", label: "margin inline start", defaultValue: "0px", kind: "text" },
        { cssVar: "--origam-avatar---padding-block-end", label: "padding block end", defaultValue: "0px", kind: "text" },
        { cssVar: "--origam-avatar---padding-block-start", label: "padding block start", defaultValue: "0px", kind: "text" },
        { cssVar: "--origam-avatar---padding-inline-end", label: "padding inline end", defaultValue: "0px", kind: "text" },
        { cssVar: "--origam-avatar---padding-inline-start", label: "padding inline start", defaultValue: "0px", kind: "text" },
        { cssVar: "--origam-avatar---box-shadow", label: "box shadow", defaultValue: "0px 0px 0px 0px rgba(0,0,0,0)", kind: "text" },
        { cssVar: "--origam-avatar---box-shadow-elevated", label: "box shadow elevated", defaultValue: "0px 6px 24px 0px rgba(0,0,0,0.05), 0px 0px 0px 1px rgba(0,0,0,0.08)", kind: "text" },
        { cssVar: "--origam-avatar---density", label: "density", defaultValue: "0px", kind: "text" },
        { cssVar: "--origam-avatar---font-size", label: "font size", defaultValue: "1.5rem", kind: "text" },
        { cssVar: "--origam-avatar---font-weight", label: "font weight", defaultValue: "400", kind: "text" },
        { cssVar: "--origam-avatar---letter-spacing", label: "letter spacing", defaultValue: "0em", kind: "text" },
        { cssVar: "--origam-avatar---overflow", label: "overflow", defaultValue: "hidden", kind: "text" }
    ],
    "alert": [
        { cssVar: "--origam-alert---background-color", label: "background color", defaultValue: "#e6e6e6", kind: "color" },
        { cssVar: "--origam-alert---border-color", label: "border color", defaultValue: "rgba(0, 0, 0, 0)", kind: "color" },
        { cssVar: "--origam-alert---color", label: "color", defaultValue: "#171717", kind: "color" },
        { cssVar: "--origam-alert---accent-width", label: "accent width", defaultValue: "24px", kind: "text" },
        { cssVar: "--origam-alert---border-bottom-width", label: "border bottom width", defaultValue: "0px", kind: "text" },
        { cssVar: "--origam-alert---border-left-width", label: "border left width", defaultValue: "0px", kind: "text" },
        { cssVar: "--origam-alert---border-radius", label: "border radius", defaultValue: "0px", kind: "text" },
        { cssVar: "--origam-alert---border-radius-rounded", label: "border radius rounded", defaultValue: "4px", kind: "text" },
        { cssVar: "--origam-alert---border-right-width", label: "border right width", defaultValue: "0px", kind: "text" },
        { cssVar: "--origam-alert---border-style", label: "border style", defaultValue: "solid", kind: "text" },
        { cssVar: "--origam-alert---border-top-width", label: "border top width", defaultValue: "0px", kind: "text" },
        { cssVar: "--origam-alert---margin-block-end", label: "margin block end", defaultValue: "0px", kind: "text" },
        { cssVar: "--origam-alert---margin-block-start", label: "margin block start", defaultValue: "0px", kind: "text" },
        { cssVar: "--origam-alert---margin-inline-end", label: "margin inline end", defaultValue: "0px", kind: "text" },
        { cssVar: "--origam-alert---margin-inline-start", label: "margin inline start", defaultValue: "0px", kind: "text" },
        { cssVar: "--origam-alert---padding-block-end", label: "padding block end", defaultValue: "16px", kind: "text" },
        { cssVar: "--origam-alert---padding-block-start", label: "padding block start", defaultValue: "16px", kind: "text" },
        { cssVar: "--origam-alert---padding-inline-end", label: "padding inline end", defaultValue: "16px", kind: "text" },
        { cssVar: "--origam-alert---padding-inline-start", label: "padding inline start", defaultValue: "16px", kind: "text" },
        { cssVar: "--origam-alert---box-shadow-elevated", label: "box shadow elevated", defaultValue: "0px 6px 24px 0px rgba(0,0,0,0.05), 0px 0px 0px 1px rgba(0,0,0,0.08)", kind: "text" },
        { cssVar: "--origam-alert---density", label: "density", defaultValue: "0px", kind: "text" },
        { cssVar: "--origam-alert---position", label: "position", defaultValue: "static", kind: "text" }
    ],
    "text-field": [
        { cssVar: "--origam-field---background-color", label: "background color", defaultValue: "rgba(0, 0, 0, 0)", kind: "color" },
        { cssVar: "--origam-field---border-color", label: "border color", defaultValue: "#a3a3a3", kind: "color" },
        { cssVar: "--origam-field---color", label: "color", defaultValue: "#171717", kind: "color" },
        { cssVar: "--origam-field---variant-outlined-background-color", label: "variant outlined background color", defaultValue: "rgba(0, 0, 0, 0)", kind: "color" },
        { cssVar: "--origam-field---append-inner-icon-opacity", label: "append inner icon opacity", defaultValue: "0.7", kind: "text" },
        { cssVar: "--origam-field---append-inner-icon-opacity-focused", label: "append inner icon opacity focused", defaultValue: "1", kind: "text" },
        { cssVar: "--origam-field---border-opacity", label: "border opacity", defaultValue: "0.38", kind: "text" },
        { cssVar: "--origam-field---border-radius", label: "border radius", defaultValue: "4px", kind: "text" },
        { cssVar: "--origam-field---border-width", label: "border width", defaultValue: "1px", kind: "text" },
        { cssVar: "--origam-field---opacity-disabled", label: "opacity disabled", defaultValue: "0.5", kind: "text" },
        { cssVar: "--origam-field---padding-bottom", label: "padding bottom", defaultValue: "6px", kind: "text" },
        { cssVar: "--origam-field---padding-end", label: "padding end", defaultValue: "16px", kind: "text" },
        { cssVar: "--origam-field---padding-start", label: "padding start", defaultValue: "16px", kind: "text" },
        { cssVar: "--origam-field---padding-top", label: "padding top", defaultValue: "8px", kind: "text" },
        { cssVar: "--origam-field---prepend-inner-icon-opacity", label: "prepend inner icon opacity", defaultValue: "0.7", kind: "text" },
        { cssVar: "--origam-field---prepend-inner-icon-opacity-focused", label: "prepend inner icon opacity focused", defaultValue: "1", kind: "text" },
        { cssVar: "--origam-field---font-size", label: "font size", defaultValue: "16px", kind: "text" },
        { cssVar: "--origam-field---letter-spacing", label: "letter spacing", defaultValue: "0.0094em", kind: "text" },
        { cssVar: "--origam-field---transition-duration", label: "transition duration", defaultValue: "150ms", kind: "text" },
        { cssVar: "--origam-field---transition-easing", label: "transition easing", defaultValue: "cubic-bezier(0.4, 0, 0.2, 1)", kind: "text" },
        { cssVar: "--origam-field---variant-solo-box-shadow", label: "variant solo box shadow", defaultValue: "0px 1px 3px 0px rgba(0,0,0,0.1), 0px 1px 2px -1px rgba(0,0,0,0.1)", kind: "text" }
    ],
    "select": [
        { cssVar: "--origam-select---no-data-color", label: "no data color", defaultValue: "#525252", kind: "color" },
        { cssVar: "--origam-field---background-color", label: "background color", defaultValue: "rgba(0, 0, 0, 0)", kind: "color" },
        { cssVar: "--origam-field---border-color", label: "border color", defaultValue: "#a3a3a3", kind: "color" },
        { cssVar: "--origam-field---color", label: "color", defaultValue: "#171717", kind: "color" },
        { cssVar: "--origam-field---variant-outlined-background-color", label: "variant outlined background color", defaultValue: "rgba(0, 0, 0, 0)", kind: "color" },
        { cssVar: "--origam-select---min-width", label: "min width", defaultValue: "150px", kind: "text" },
        { cssVar: "--origam-select---no-data-padding", label: "no data padding", defaultValue: "16px", kind: "text" },
        { cssVar: "--origam-field---append-inner-icon-opacity", label: "append inner icon opacity", defaultValue: "0.7", kind: "text" },
        { cssVar: "--origam-field---append-inner-icon-opacity-focused", label: "append inner icon opacity focused", defaultValue: "1", kind: "text" },
        { cssVar: "--origam-field---border-opacity", label: "border opacity", defaultValue: "0.38", kind: "text" },
        { cssVar: "--origam-field---border-radius", label: "border radius", defaultValue: "4px", kind: "text" },
        { cssVar: "--origam-field---border-width", label: "border width", defaultValue: "1px", kind: "text" },
        { cssVar: "--origam-field---opacity-disabled", label: "opacity disabled", defaultValue: "0.5", kind: "text" },
        { cssVar: "--origam-field---padding-bottom", label: "padding bottom", defaultValue: "6px", kind: "text" },
        { cssVar: "--origam-field---padding-end", label: "padding end", defaultValue: "16px", kind: "text" },
        { cssVar: "--origam-field---padding-start", label: "padding start", defaultValue: "16px", kind: "text" },
        { cssVar: "--origam-field---padding-top", label: "padding top", defaultValue: "8px", kind: "text" },
        { cssVar: "--origam-field---prepend-inner-icon-opacity", label: "prepend inner icon opacity", defaultValue: "0.7", kind: "text" },
        { cssVar: "--origam-field---prepend-inner-icon-opacity-focused", label: "prepend inner icon opacity focused", defaultValue: "1", kind: "text" },
        { cssVar: "--origam-select---no-data-font-size", label: "no data font size", defaultValue: "0.75rem", kind: "text" },
        { cssVar: "--origam-select---no-data-text-align", label: "no data text align", defaultValue: "center", kind: "text" },
        { cssVar: "--origam-field---font-size", label: "font size", defaultValue: "16px", kind: "text" },
        { cssVar: "--origam-field---letter-spacing", label: "letter spacing", defaultValue: "0.0094em", kind: "text" },
        { cssVar: "--origam-field---transition-duration", label: "transition duration", defaultValue: "150ms", kind: "text" }
    ],
    "checkbox": [
        { cssVar: "--origam-checkbox---min-height", label: "min height", defaultValue: "56px", kind: "text" },
        { cssVar: "--origam-checkbox---flex", label: "flex", defaultValue: "0 1 auto", kind: "text" },
        { cssVar: "--origam-checkbox---transition-duration", label: "transition duration", defaultValue: "200ms", kind: "text" },
        { cssVar: "--origam-checkbox---transition-easing", label: "transition easing", defaultValue: "cubic-bezier(0.4, 0, 0.2, 1)", kind: "text" }
    ],
    "switch": [
        { cssVar: "--origam-switch---opacity-disabled", label: "opacity disabled", defaultValue: "0.32", kind: "text" },
        { cssVar: "--origam-switch---transition-duration", label: "transition duration", defaultValue: "200ms", kind: "text" },
        { cssVar: "--origam-switch---transition-timing-function", label: "transition timing function", defaultValue: "cubic-bezier(0.4, 0, 0.2, 1)", kind: "text" }
    ],
    "title": [
        { cssVar: "--origam-title---color", label: "color", defaultValue: "#171717", kind: "color" },
        { cssVar: "--origam-title---line-height", label: "line height", defaultValue: "1.25", kind: "text" },
        { cssVar: "--origam-title---margin-block-end", label: "margin block end", defaultValue: "0px", kind: "text" },
        { cssVar: "--origam-title---margin-block-start", label: "margin block start", defaultValue: "0px", kind: "text" },
        { cssVar: "--origam-title---font-family", label: "font family", defaultValue: "Inter, \\", kind: "text" },
        { cssVar: "--origam-title---font-size-2xl", label: "font size 2xl", defaultValue: "1.875rem", kind: "text" },
        { cssVar: "--origam-title---font-size-3xl", label: "font size 3xl", defaultValue: "2.25rem", kind: "text" },
        { cssVar: "--origam-title---font-size-lg", label: "font size lg", defaultValue: "1.25rem", kind: "text" },
        { cssVar: "--origam-title---font-size-md", label: "font size md", defaultValue: "1.125rem", kind: "text" },
        { cssVar: "--origam-title---font-size-sm", label: "font size sm", defaultValue: "1rem", kind: "text" },
        { cssVar: "--origam-title---font-size-xl", label: "font size xl", defaultValue: "1.5rem", kind: "text" },
        { cssVar: "--origam-title---font-size-xs", label: "font size xs", defaultValue: "0.875rem", kind: "text" },
        { cssVar: "--origam-title---font-weight", label: "font weight", defaultValue: "600", kind: "text" },
        { cssVar: "--origam-title---letter-spacing", label: "letter spacing", defaultValue: "-0.025em", kind: "text" }
    ],
    "icon": [
        { cssVar: "--origam-icon---color", label: "color", defaultValue: "currentColor", kind: "text" },
        { cssVar: "--origam-icon---color-danger", label: "color danger", defaultValue: "#ef4444", kind: "color" },
        { cssVar: "--origam-icon---color-disabled", label: "color disabled", defaultValue: "#a3a3a3", kind: "color" },
        { cssVar: "--origam-icon---color-info", label: "color info", defaultValue: "#2196f3", kind: "color" },
        { cssVar: "--origam-icon---color-primary", label: "color primary", defaultValue: "#7c3aed", kind: "color" },
        { cssVar: "--origam-icon---color-success", label: "color success", defaultValue: "#4caf50", kind: "color" },
        { cssVar: "--origam-icon---color-warning", label: "color warning", defaultValue: "#fb8c00", kind: "color" },
        { cssVar: "--origam-icon---font-size-2xl", label: "font size 2xl", defaultValue: "1.25rem", kind: "text" },
        { cssVar: "--origam-icon---font-size-3xl", label: "font size 3xl", defaultValue: "1.5rem", kind: "text" },
        { cssVar: "--origam-icon---font-size-4xl", label: "font size 4xl", defaultValue: "1.875rem", kind: "text" },
        { cssVar: "--origam-icon---font-size-lg", label: "font size lg", defaultValue: "1rem", kind: "text" },
        { cssVar: "--origam-icon---font-size-md", label: "font size md", defaultValue: "0.875rem", kind: "text" },
        { cssVar: "--origam-icon---font-size-sm", label: "font size sm", defaultValue: "0.75rem", kind: "text" },
        { cssVar: "--origam-icon---font-size-xl", label: "font size xl", defaultValue: "1.125rem", kind: "text" },
        { cssVar: "--origam-icon---font-size-xs", label: "font size xs", defaultValue: "0.625rem", kind: "text" },
        { cssVar: "--origam-icon---transition-duration", label: "transition duration", defaultValue: "100ms", kind: "text" },
        { cssVar: "--origam-icon---transition-timing-function", label: "transition timing function", defaultValue: "cubic-bezier(0.4, 0, 0.2, 1)", kind: "text" }
    ],
    "badge": [
        { cssVar: "--origam-badge__badge---background-color", label: "background color", defaultValue: "#7c3aed", kind: "color" },
        { cssVar: "--origam-badge__badge---border-color", label: "border color", defaultValue: "currentColor", kind: "text" },
        { cssVar: "--origam-badge__badge---color", label: "color", defaultValue: "#ffffff", kind: "color" },
        { cssVar: "--origam-badge__badge---border-bottom-width", label: "border bottom width", defaultValue: "0px", kind: "text" },
        { cssVar: "--origam-badge__badge---border-left-width", label: "border left width", defaultValue: "0px", kind: "text" },
        { cssVar: "--origam-badge__badge---border-radius", label: "border radius", defaultValue: "9999px", kind: "text" },
        { cssVar: "--origam-badge__badge---border-right-width", label: "border right width", defaultValue: "0px", kind: "text" },
        { cssVar: "--origam-badge__badge---border-style", label: "border style", defaultValue: "solid", kind: "text" },
        { cssVar: "--origam-badge__badge---border-top-width", label: "border top width", defaultValue: "0px", kind: "text" },
        { cssVar: "--origam-badge__badge---border-width", label: "border width", defaultValue: "0px", kind: "text" },
        { cssVar: "--origam-badge__badge---height", label: "height", defaultValue: "1.25rem", kind: "text" },
        { cssVar: "--origam-badge__badge---margin-block-end", label: "margin block end", defaultValue: "0px", kind: "text" },
        { cssVar: "--origam-badge__badge---margin-block-start", label: "margin block start", defaultValue: "0px", kind: "text" },
        { cssVar: "--origam-badge__badge---margin-inline-end", label: "margin inline end", defaultValue: "0px", kind: "text" },
        { cssVar: "--origam-badge__badge---margin-inline-start", label: "margin inline start", defaultValue: "0px", kind: "text" },
        { cssVar: "--origam-badge__badge---min-width", label: "min width", defaultValue: "20px", kind: "text" },
        { cssVar: "--origam-badge__badge---padding-block-end", label: "padding block end", defaultValue: "0px", kind: "text" },
        { cssVar: "--origam-badge__badge---padding-block-start", label: "padding block start", defaultValue: "0px", kind: "text" },
        { cssVar: "--origam-badge__badge---padding-inline-end", label: "padding inline end", defaultValue: "4px", kind: "text" },
        { cssVar: "--origam-badge__badge---padding-inline-start", label: "padding inline start", defaultValue: "4px", kind: "text" },
        { cssVar: "--origam-badge__badge---box-shadow", label: "box shadow", defaultValue: "0px 0px 0px 0px rgba(0,0,0,0)", kind: "text" },
        { cssVar: "--origam-badge__badge---box-shadow-elevated", label: "box shadow elevated", defaultValue: "0px 6px 24px 0px rgba(0,0,0,0.05), 0px 0px 0px 1px rgba(0,0,0,0.08)", kind: "text" },
        { cssVar: "--origam-badge__badge---font-size", label: "font size", defaultValue: "0.75rem", kind: "text" },
        { cssVar: "--origam-badge__badge---font-weight", label: "font weight", defaultValue: "500", kind: "text" }
    ],
    "divider": [
        { cssVar: "--origam-divider---color", label: "color", defaultValue: "#d4d4d4", kind: "color" },
        { cssVar: "--origam-divider---border-style", label: "border style", defaultValue: "solid", kind: "text" },
        { cssVar: "--origam-divider---margin-block", label: "margin block", defaultValue: "0px", kind: "text" },
        { cssVar: "--origam-divider---opacity", label: "opacity", defaultValue: "1", kind: "text" },
        { cssVar: "--origam-divider---padding-block-end", label: "padding block end", defaultValue: "0px", kind: "text" },
        { cssVar: "--origam-divider---padding-block-start", label: "padding block start", defaultValue: "0px", kind: "text" },
        { cssVar: "--origam-divider---padding-inline-end", label: "padding inline end", defaultValue: "0px", kind: "text" },
        { cssVar: "--origam-divider---padding-inline-start", label: "padding inline start", defaultValue: "0px", kind: "text" },
        { cssVar: "--origam-divider---thickness", label: "thickness", defaultValue: "1px", kind: "text" }
    ],
    "progress-linear": [
        { cssVar: "--origam-progress-linear---background", label: "background", defaultValue: "rgba(0, 0, 0, 0)", kind: "color" },
        { cssVar: "--origam-progress-linear---background-track-background", label: "background track background", defaultValue: "currentColor", kind: "text" },
        { cssVar: "--origam-progress-linear---background-track-opacity", label: "background track opacity", defaultValue: "0.5", kind: "text" },
        { cssVar: "--origam-progress-linear---background-track-position", label: "background track position", defaultValue: "absolute", kind: "text" },
        { cssVar: "--origam-progress-linear---rounded-border-radius", label: "rounded border radius", defaultValue: "9999px", kind: "text" },
        { cssVar: "--origam-progress-linear---width", label: "width", defaultValue: "100%", kind: "text" },
        { cssVar: "--origam-progress-linear---indeterminate-duration", label: "indeterminate duration", defaultValue: "2200ms", kind: "text" },
        { cssVar: "--origam-progress-linear---overflow", label: "overflow", defaultValue: "hidden", kind: "text" },
        { cssVar: "--origam-progress-linear---position", label: "position", defaultValue: "relative", kind: "text" },
        { cssVar: "--origam-progress-linear---transition-duration", label: "transition duration", defaultValue: "200ms", kind: "text" },
        { cssVar: "--origam-progress-linear---transition-easing", label: "transition easing", defaultValue: "cubic-bezier(0.4, 0, 0.2, 1)", kind: "text" }
    ]
}
