export { default as OrigamIcon } from './OrigamIcon.vue'
export { default as OrigamClassIcon } from './OrigamClassIcon.vue'
export { default as OrigamComponentIcon } from './OrigamComponentIcon.vue'
export { default as OrigamLigatureIcon } from './OrigamLigatureIcon.vue'
export { default as OrigamSvgIcon } from './OrigamSvgIcon.vue'
