import { expect, test, type FrameLocator, type Page } from '@playwright/test'

/**
 * Phase 4 — Playwright spec for the global utility classes
 * generated by `scripts/build-tokens.mjs` into
 * `src/assets/css/tokens/origam-utilities.css`.
 *
 * Strategy
 * --------
 * - One test.describe per utility group (color, bg, shadow, rounded,
 *   border, padding, margin, gap, text).
 * - Each test navigates to the Histoire Utilities variant, locates the
 *   swatch via `data-cy="util-{group}-{value}"` and asserts:
 *   1. The utility class is on the element.
 *   2. The relevant computed style property is non-empty / non-transparent
 *      (i.e. the CSS variable actually resolved in the browser).
 * - `.origam--shadow-none` and `.origam--bg-ghost` are intentional
 *   zero-value classes; those assertions skip the "non-empty" check.
 * - Spacing (padding, margin, gap) and text-size tests use a structural
 *   assertion (the class lands on the element) plus a sanity check that
 *   the CSS var resolved to a px value != "0px" for non-zero steps.
 *
 * Assertions: 66 classes * 1 class-presence + per-group computed checks
 * → total assertion count documented at bottom of each describe block.
 */

const STORY_BASE = '/stories/story/components-stories-utilities-origamutilities-story-vue'

// Variant titles exactly as declared in OrigamUtilities.story.vue
const VARIANTS = {
    color:   'Foreground color (.origam--color-*)',
    bg:      'Background color (.origam--bg-*)',
    shadow:  'Elevation (.origam--shadow-*)',
    rounded: 'Border radius (.origam--rounded-*)',
    border:  'Border width (.origam--border-*)',
    padding: 'Padding (.origam--p-*)',
    margin:  'Margin (.origam--m-*)',
    gap:     'Gap (.origam--gap-*)',
    text:    'Font size (.origam--text-*)',
} as const

// Mirrors the constants in OrigamUtilities.story.vue
const INTENTS   = ['primary', 'secondary', 'success', 'warning', 'danger', 'info', 'neutral'] as const
const SHADOWS   = ['none', 'xs', 'sm', 'md', 'lg', 'xl'] as const
const ROUNDEDS  = ['none', 'xs', 'sm', 'md', 'lg', 'xl', 'full'] as const
const BORDERS   = ['none', 'thin', 'thick'] as const
const SPACES    = ['0', '1', '2', '3', '4', '5', '6', '8', '10', '12'] as const
const TEXT_SIZES = ['xs', 'sm', 'md', 'lg', 'xl', '2xl'] as const

// ─── Helpers ─────────────────────────────────────────────────────────────────

async function gotoVariant(page: Page, variantTitle: string): Promise<FrameLocator> {
    await page.goto(STORY_BASE)
    await page.waitForLoadState('networkidle')
    await page.getByText(variantTitle, { exact: true }).first().click()
    await page.waitForTimeout(600)
    return page.frameLocator('iframe[src*="__sandbox"]')
}

/** True when a computed style value represents "nothing" (0, transparent, none). */
function _isEmptyValue(v: string): boolean {
    return (
        v === '' ||
        v === 'none' ||
        v === '0px' ||
        v === 'rgba(0, 0, 0, 0)' ||
        v === 'normal'
    )
}

// ─── Foreground color (.origam--color-*) — 7 classes, 14 assertions ──────────

test.describe('Utility classes — foreground color (.origam--color-*)', () => {
    for (const intent of INTENTS) {
        test(`origam--color-${intent} — class present and color resolves`, async ({ page }) => {
            const sb = await gotoVariant(page, VARIANTS.color)
            const swatch = sb.locator(`[data-cy="util-color-${intent}"]`)
            await expect(swatch).toBeVisible({ timeout: 5000 })

            // 1. Class is on the element
            await expect(swatch).toHaveClass(new RegExp(`origam--color-${intent}`))

            // 2. Computed color is not transparent / empty
            const color = await swatch.evaluate(el => getComputedStyle(el).color)
            expect(color, `util-color-${intent} computed color`).not.toBe('')
            expect(color, `util-color-${intent} computed color`).not.toBe('rgba(0, 0, 0, 0)')
        })
    }
})

// ─── Background color (.origam--bg-*) — 7 classes, 14 assertions ─────────────

test.describe('Utility classes — background color (.origam--bg-*)', () => {
    for (const intent of INTENTS) {
        test(`origam--bg-${intent} — class present and background resolves`, async ({ page }) => {
            const sb = await gotoVariant(page, VARIANTS.bg)
            const swatch = sb.locator(`[data-cy="util-bg-${intent}"]`)
            await expect(swatch).toBeVisible({ timeout: 5000 })

            // 1. Class is on the element
            await expect(swatch).toHaveClass(new RegExp(`origam--bg-${intent}`))

            // 2. Computed background-color is not transparent
            // Note: `.origam--bg-ghost` would be the only intentional zero
            // value but `ghost` is not in the story matrix.
            const bg = await swatch.evaluate(el => getComputedStyle(el).backgroundColor)
            expect(bg, `util-bg-${intent} computed background-color`).not.toBe('')
            expect(bg, `util-bg-${intent} computed background-color`).not.toBe('rgba(0, 0, 0, 0)')
        })
    }
})

// ─── Elevation (.origam--shadow-*) — 6 classes, 11 assertions ───────────────

test.describe('Utility classes — elevation (.origam--shadow-*)', () => {
    for (const level of SHADOWS) {
        test(`origam--shadow-${level} — class present${level === 'none' ? ' (shadow-none is intentionally empty)' : ' and box-shadow resolves'}`, async ({ page }) => {
            const sb = await gotoVariant(page, VARIANTS.shadow)
            const swatch = sb.locator(`[data-cy="util-shadow-${level}"]`)
            await expect(swatch).toBeVisible({ timeout: 5000 })

            // 1. Class is on the element
            await expect(swatch).toHaveClass(new RegExp(`origam--shadow-${level}`))

            if (level !== 'none') {
                // 2. box-shadow resolves to something non-trivial
                const shadow = await swatch.evaluate(el => getComputedStyle(el).boxShadow)
                expect(shadow, `util-shadow-${level} computed box-shadow`).not.toBe('')
                expect(shadow, `util-shadow-${level} computed box-shadow`).not.toBe('none')
            }
            // shadow-none: skip computed check — intentional zero value
        })
    }
})

// ─── Border radius (.origam--rounded-*) — 7 classes, 13 assertions ───────────

test.describe('Utility classes — border radius (.origam--rounded-*)', () => {
    for (const r of ROUNDEDS) {
        test(`origam--rounded-${r} — class present${r === 'none' ? ' (radius-none is intentionally 0)' : ' and border-radius resolves'}`, async ({ page }) => {
            const sb = await gotoVariant(page, VARIANTS.rounded)
            const swatch = sb.locator(`[data-cy="util-rounded-${r}"]`)
            await expect(swatch).toBeVisible({ timeout: 5000 })

            // 1. Class is on the element
            await expect(swatch).toHaveClass(new RegExp(`origam--rounded-${r}`))

            if (r !== 'none') {
                // 2. border-top-left-radius resolves to a non-zero value
                const radius = await swatch.evaluate(el => getComputedStyle(el).borderTopLeftRadius)
                expect(radius, `util-rounded-${r} computed border-radius`).not.toBe('')
                expect(radius, `util-rounded-${r} computed border-radius`).not.toBe('0px')
            }
            // rounded-none: skip computed check — intentional 0px value
        })
    }
})

// ─── Border width (.origam--border-*) — 3 classes, 5 assertions ──────────────

test.describe('Utility classes — border width (.origam--border-*)', () => {
    for (const b of BORDERS) {
        test(`origam--border-${b} — class present${b === 'none' ? ' (border-none is intentionally 0)' : ' and border-width resolves'}`, async ({ page }) => {
            const sb = await gotoVariant(page, VARIANTS.border)
            const swatch = sb.locator(`[data-cy="util-border-${b}"]`)
            await expect(swatch).toBeVisible({ timeout: 5000 })

            // 1. Class is on the element
            await expect(swatch).toHaveClass(new RegExp(`origam--border-${b}`))

            if (b !== 'none') {
                // 2. border-top-width resolves to a non-zero value
                const borderWidth = await swatch.evaluate(el => getComputedStyle(el).borderTopWidth)
                expect(borderWidth, `util-border-${b} computed border-top-width`).not.toBe('')
                expect(borderWidth, `util-border-${b} computed border-top-width`).not.toBe('0px')
            }
        })
    }
})

// ─── Padding (.origam--p-*) — 10 classes, 10 assertions ─────────────────────

test.describe('Utility classes — padding (.origam--p-*)', () => {
    for (const n of SPACES) {
        test(`origam--p-${n} — class present on swatch`, async ({ page }) => {
            const sb = await gotoVariant(page, VARIANTS.padding)
            const swatch = sb.locator(`[data-cy="util-p-${n}"]`)
            await expect(swatch).toBeVisible({ timeout: 5000 })

            // 1. Class is on the element
            await expect(swatch).toHaveClass(new RegExp(`origam--p-${n}(?![0-9])`))

            // 2. For non-zero steps, padding-top resolves to a non-zero px
            if (n !== '0') {
                const pt = await swatch.evaluate(el => getComputedStyle(el).paddingTop)
                expect(pt, `util-p-${n} computed padding-top`).not.toBe('')
                expect(pt, `util-p-${n} computed padding-top`).not.toBe('0px')
            }
        })
    }
})

// ─── Margin (.origam--m-*) — 10 classes, 10 assertions ──────────────────────

test.describe('Utility classes — margin (.origam--m-*)', () => {
    for (const n of SPACES) {
        test(`origam--m-${n} — class present on swatch`, async ({ page }) => {
            const sb = await gotoVariant(page, VARIANTS.margin)
            const swatch = sb.locator(`[data-cy="util-m-${n}"]`)
            await expect(swatch).toBeVisible({ timeout: 5000 })

            // 1. Class is on the element
            await expect(swatch).toHaveClass(new RegExp(`origam--m-${n}(?![0-9])`))

            // 2. For non-zero steps, margin-top resolves to a non-zero px
            if (n !== '0') {
                const mt = await swatch.evaluate(el => getComputedStyle(el).marginTop)
                expect(mt, `util-m-${n} computed margin-top`).not.toBe('')
                expect(mt, `util-m-${n} computed margin-top`).not.toBe('0px')
            }
        })
    }
})

// ─── Gap (.origam--gap-*) — 10 classes, 10 assertions ───────────────────────

test.describe('Utility classes — gap (.origam--gap-*)', () => {
    for (const n of SPACES) {
        test(`origam--gap-${n} — class present on flex container`, async ({ page }) => {
            const sb = await gotoVariant(page, VARIANTS.gap)
            const swatch = sb.locator(`[data-cy="util-gap-${n}"]`)
            await expect(swatch).toBeVisible({ timeout: 5000 })

            // 1. Class is on the element
            await expect(swatch).toHaveClass(new RegExp(`origam--gap-${n}(?![0-9])`))

            // 2. For non-zero steps, gap resolves to a non-zero px value.
            // (CSS `gap` on a flex container shows as `row-gap` and `column-gap`
            //  in getComputedStyle — column-gap is reliable.)
            if (n !== '0') {
                const gap = await swatch.evaluate(el => getComputedStyle(el).columnGap)
                expect(gap, `util-gap-${n} computed column-gap`).not.toBe('')
                expect(gap, `util-gap-${n} computed column-gap`).not.toBe('0px')
                expect(gap, `util-gap-${n} computed column-gap`).not.toBe('normal')
            }
        })
    }
})

// ─── Font size (.origam--text-*) — 6 classes, 12 assertions ─────────────────

test.describe('Utility classes — font size (.origam--text-*)', () => {
    for (const size of TEXT_SIZES) {
        test(`origam--text-${size} — class present and font-size resolves`, async ({ page }) => {
            const sb = await gotoVariant(page, VARIANTS.text)
            const swatch = sb.locator(`[data-cy="util-text-${size}"]`)
            await expect(swatch).toBeVisible({ timeout: 5000 })

            // 1. Class is on the element
            await expect(swatch).toHaveClass(new RegExp(`origam--text-${size}`))

            // 2. font-size resolves to a non-empty px value
            const fs = await swatch.evaluate(el => getComputedStyle(el).fontSize)
            expect(fs, `util-text-${size} computed font-size`).not.toBe('')
            expect(fs, `util-text-${size} computed font-size`).not.toBe('0px')
        })
    }
})

// ─── Summary ─────────────────────────────────────────────────────────────────
// Total tests : 7 + 7 + 6 + 7 + 3 + 10 + 10 + 10 + 6 = 66 tests
// Total assertions: ~130 (1 visibility + 1 class-presence + 0–2 computed checks per test)
