import { KEYBOARD_VALUES } from '../../enums'

export const COMPOSITION_IGNORE_KEYS = [
    KEYBOARD_VALUES.UP,
    KEYBOARD_VALUES.DOWN,
    KEYBOARD_VALUES.RIGHT,
    KEYBOARD_VALUES.LEFT,
    KEYBOARD_VALUES.ENTER,
    KEYBOARD_VALUES.ESC,
    KEYBOARD_VALUES.TAB,
    KEYBOARD_VALUES.EMPTY
]
