/**
 * Minimal ambient shim for the `#app` Nuxt virtual module.
 *
 * `packages/ds` does not depend on `nuxt` at runtime — the nuxt sub-package
 * (`src/nuxt/`) is only activated by consumers who already have Nuxt installed.
 * The `#app` virtual path is generated by Nuxt's build toolchain and is never
 * present in the DS's own `node_modules`, which causes `vue-tsc --noEmit` to
 * emit TS2307 ("Cannot find module '#app'").
 *
 * This shim declares the subset of the `#app` module that the DS plugins
 * actually use, so the DS can be type-checked independently of a Nuxt project.
 * It is intentionally minimal — do NOT add members that the plugins don't use.
 *
 * Types are derived from `nuxt@4.x dist/app` but are inlined to avoid any
 * dependency on nuxt being present in this package's node_modules.
 *
 * tsconfig.json maps `#app` → this file via `compilerOptions.paths`.
 */

import type { App } from 'vue'
import type { Ref } from 'vue'

declare module '#app' {
    // ── Core Nuxt app instance ────────────────────────────────────────────

    interface NuxtApp {
        vueApp: App<Element>
    }

    // ── Plugin helpers ────────────────────────────────────────────────────

    type NuxtPluginReturn<T extends Record<string, unknown>> =
        | void
        | { provide?: T }
        | Promise<void>
        | Promise<{ provide?: T }>

    interface ObjectPlugin<T extends Record<string, unknown> = Record<string, unknown>> {
        name?: string
        enforce?: 'pre' | 'default' | 'post'
        setup?: (nuxtApp: NuxtApp) => NuxtPluginReturn<T>
        parallel?: boolean
    }

    function defineNuxtPlugin<T extends Record<string, unknown>>(
        plugin:
            | ((nuxtApp: NuxtApp) => NuxtPluginReturn<T>)
            | ObjectPlugin<T>
    ): ObjectPlugin<T>

    // ── Composables used by the DS nuxt plugins ───────────────────────────

    interface CookieOptions<T = unknown> {
        maxAge?: number
        sameSite?: 'strict' | 'lax' | 'none' | boolean
        path?: string
        readonly?: boolean
        default?: () => T | Ref<T>
        watch?: boolean | 'shallow'
    }

    interface CookieRef<T> extends Ref<T> {}

    function useCookie<T = string | null | undefined>(
        name: string,
        opts?: CookieOptions<T> & { readonly?: false }
    ): CookieRef<T>

    function useCookie<T = string | null | undefined>(
        name: string,
        opts: CookieOptions<T> & { readonly: true }
    ): Readonly<CookieRef<T>>

    function useRuntimeConfig(): Record<string, unknown> & {
        public: Record<string, unknown>
    }

    function useHead(input: Record<string, unknown>): void

    function useRequestHeaders<K extends string = string>(
        include: K[]
    ): { [key in Lowercase<K>]?: string }

    function useRequestHeaders(): Readonly<Record<string, string>>
}
