import type { IInterfaceDoc } from '~/interfaces/interfaces-catalog.interface'

export const I_DATA_TABLE_ITEM_SLOT_INTERFACE_DOC: IInterfaceDoc = {
    slug: 'i-data-table-item-slot',
    name: 'IDataTableItemSlot',
    category: 'Component Props',
    descriptionKey: 'interfaces.catalog.i_data_table_item_slot.description',
    descriptionFallback: 'Slot scope injected into every row-level slot of <OrigamDataTable> — exposes the raw item, its index, resolved columns, and the expand/select helpers.',
    definition: `export interface IDataTableItemSlot<T = any> extends IDataTableItemBase<T> {
    columns: IInternalDataTableHeader[]
    props: any
}`,
    extends: ['IDataTableItemBase'],
    props: [
        { name: 'columns', type: 'IInternalDataTableHeader[]', optional: false, descriptionFallback: 'Array of resolved header descriptors for this row — use them to iterate over cells in the correct column order.' },
        { name: 'props', type: 'any', optional: false, descriptionFallback: 'Merged props to spread onto the row root element (contains class, style, data-* attributes generated by rowProps).' },
        { name: 'index', type: 'number', optional: false, descriptionFallback: 'Zero-based row index in the current page.' },
        { name: 'item', type: 'T', optional: false, descriptionFallback: 'The original raw item object from the items array.' },
        { name: 'internalItem', type: 'IDataTableItem<T>', optional: false, descriptionFallback: 'Enriched internal item with key, index, columns and groupable metadata.' },
        { name: 'isExpanded', type: '(item: IDataTableItem) => boolean', optional: false, descriptionFallback: 'Returns true when the given item row is currently expanded.' },
        { name: 'toggleExpand', type: '(item: IDataTableItem) => void', optional: false, descriptionFallback: 'Toggles the expanded state of the given item row.' },
        { name: 'isSelected', type: '(items: IDataTableSelectableItem | Array<IDataTableSelectableItem>) => boolean', optional: false, descriptionFallback: 'Returns true when all passed items are currently selected.' },
        { name: 'toggleSelect', type: '(item: IDataTableSelectableItem) => void', optional: false, descriptionFallback: 'Toggles the selection state of the given item.' },
    ],
    usedBy: [
        { slug: 'data-table', name: 'DataTable', kind: 'component' },
    ],
    sourceFile: 'packages/ds/src/interfaces/DataTable/items.interface.ts',
    examples: [
        {
            titleKey: 'interfaces.detail.i_data_table_item_slot.example',
            titleFallback: 'Custom row slot using IDataTableItemSlot',
            code: `<OrigamDataTable :items="rows" :headers="headers">
    <template #item="{ item, columns, isSelected, toggleSelect }">
        <tr :class="{ selected: isSelected(item) }" @click="toggleSelect(item)">
            <td v-for="col in columns" :key="col.key">{{ item[col.key] }}</td>
        </tr>
    </template>
</OrigamDataTable>`,
            lang: 'vue',
        },
    ],
}
