import type { IInterfaceDoc } from '~/interfaces/interfaces-catalog.interface'

export const I_FIELD_DEFAULT_SLOT_PROPS_INTERFACE_DOC: IInterfaceDoc = {
    slug: 'i-field-default-slot-props',
    name: 'IFieldDefaultSlotProps',
    category: 'Slots',
    descriptionKey: 'interfaces.catalog.i_field_default_slot_props.description',
    descriptionFallback: 'Shape of the slot props injected into the default slot of OrigamField — exposes the id, aria-describedby, active/focused state, ref and focus handlers so inner input elements can wire up correctly.',
    definition: `export interface IFieldDefaultSlotProps {
    id: string
    'aria-describedby': string
    isActive: boolean
    isFocused: boolean | undefined
    ref: HTMLElement | undefined
    onBlur: () => void
    onFocus: () => void
}`,
    extends: [],
    props: [
        { name: 'id', type: 'string', optional: false, descriptionFallback: 'Unique DOM id generated by OrigamField for the inner input.' },
        { name: 'aria-describedby', type: 'string', optional: false, descriptionFallback: 'Space-separated list of ids of elements that describe this input (hint, error messages).' },
        { name: 'isActive', type: 'boolean', optional: false, descriptionFallback: 'True when the field is in an active (non-empty / focused) state.' },
        { name: 'isFocused', type: 'boolean | undefined', optional: false, descriptionFallback: 'True when the inner input is focused.' },
        { name: 'ref', type: 'HTMLElement | undefined', optional: false, descriptionFallback: 'Template ref to the underlying input element managed by OrigamField.' },
        { name: 'onBlur', type: '() => void', optional: false, descriptionFallback: 'Blur handler to be bound on the inner native input.' },
        { name: 'onFocus', type: '() => void', optional: false, descriptionFallback: 'Focus handler to be bound on the inner native input.' },
    ],
    usedBy: [
        { slug: 'field', name: 'Field', kind: 'component' },
    ],
    sourceFile: 'packages/ds/src/interfaces/Field/field.interface.ts',
    examples: [
        {
            titleKey: 'interfaces.detail.i_field_default_slot_props.example',
            titleFallback: 'Wiring a native input inside OrigamField',
            code: `<OrigamField>
    <template #default="{ id, isActive, onFocus, onBlur, ref }">
        <input :id="id" :ref="ref" @focus="onFocus" @blur="onBlur" />
    </template>
</OrigamField>`,
            lang: 'vue',
        },
    ],
}
